Gopkg.lock, Gopkg.toml, config/crd/aws.crossplane.io_providers.yaml, config/crd/cache.aws.crossplane.io_replicationgroupclasses.yaml, config/crd/cache.aws.crossplane.io_replicationgroups.yaml, config/crd/compute.aws.crossplane.io_eksclusterclasses.yaml, config/crd/compute.aws.crossplane.io_eksclusters.yaml, config/crd/database.aws.crossplane.io_rdsinstanceclasses.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml, config/crd/storage.aws.crossplane.io_s3bucketclasses.yaml, config/crd/storage.aws.crossplane.io_s3buckets.yaml
This PR updates our usage of controller-tools to the upstream now that https://github.com/kubernetes-sigs/controller-tools/pull/303 has been merged.
I have:
=> Use upstream controller-tools

aws/apis/compute/v1alpha2/types.go, aws/apis/network/v1alpha2/vpc_types.go, config/crd/compute.aws.crossplane.io_eksclusterclasses.yaml, config/crd/compute.aws.crossplane.io_eksclusters.yaml, config/crd/network.aws.crossplane.io_vpcs.yaml, pkg/clients/aws/ec2/fake/vpc.go, pkg/clients/aws/ec2/vpc.go, pkg/clients/aws/eks/eks.go, pkg/controller/aws/network/vpc/controller.go, pkg/controller/aws/network/vpc/controller_test.go
Addresses #684
When e2e testing the new managed resources for resource connectivity:
- [KeyName] doesn't need to be a required value. This is used to make it possible to remote login to eks workers, and to avoid unnecessary complexity can be ignored for now. If this turned out to be an actually required feature, a managed resource to create aws KeyPairs need to be developed
- [VPC] type is missing `EnableDNSHostNames` and `EnableDNSSupport` attributes. These attributes are required for RDS connectivity
I have:
[`clusterrole.yaml`]: …
=> Issue crossplane 684

pkg/clients/aws/rds/rds.go
Updates the RDS `IsAlreadyExistsError` function to check the correct AWS error for DB instance such that "already exists" failures will be ignored on creation.
Fixes #21 
I have:
=> rds client: check if db instance not cluster exists

Makefile
Signed-off-by: soorena776 <javad@upbound.io>
As part of the go module adaptation in build repoistory, I also moved manifests target to kubebuilder.mk library. Since the pr is merged there this change is needed to avoid a break in case anyone upgraded the build submodule
I have:
=> Move manifets target to `kubebuilder.mk` in build submodule

go.mod, go.sum, pkg/controller/aws.go, pkg/controller/compute/eks.go, pkg/controller/compute/eks_test.go, pkg/controller/compute/secret.go
Fixes #35
EKS connection secrets change frequently. We must propagate them from the managed resource connection secret to the resource claim connection secret.
TODO: Test this manually to confirm it fixes the problem.
I have:
=> Propagate EKS connection secret updates

apis/database/v1beta1/rdsinstance_types.go, config/crd/database.aws.crossplane.io_rdsinstanceclasses.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml
`dbsubnetGroupName` was used as jsontag instead of `dbSubnetGroupName` for some reason.
I have:
=> rds: typo fix for dbsubnetGroupName

config/stack/manifests/app.yaml, config/stack/manifests/install.yaml
This PR bumps the stack version to v0.2.0 in its internal metadata.
I have:
[skip ci]
=> build: bump stack version to v0.2.0

apis/database/v1beta1/rdsinstance_types.go, apis/database/v1beta1/zz_generated.deepcopy.go, config/crd/database.aws.crossplane.io_rdsinstanceclasses.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml
Remove unused  masterpassword field from spec. It's not used anywhere but somehow exists.
I have:
=> rds: remove unused  masterpassword field from spec

cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml
This PR bumps the internal stack references to the soon to be released version of v0.4.0, as well as updating the stack resource readmes to reference the soon to be released crossplane.io docs version 0.6.
I have:
[`app.yaml`]: https://github.com/crossplaneio/stack-gcp/blob/master/config/stack/manifests/app.yaml
=> Bump stack-aws version refs to v0.4.0

apis/storage/v1alpha3/bucket_types.go
https://github.com/crossplaneio/crossplane-runtime/issues/1
This function and the util package it lives in are deprecated. They'll be replaced by the new crossplane.io/external-name annotation once we port this controller to the managed resource reconciler. For now I'd like to remove it from crossplane-runtime/pkg/util as it is only used by the bucket controllers.
I have:
[`app.yaml`]: https://github.com/crossplaneio/stack-gcp/blob/master/config/stack/manifests/app.yaml
[stack resources documentation]: …
=> Rehome deprecated ConditionalStringFormat from crossplane-runtime

apis/compute/v1alpha3/types.go, config/crd/compute.aws.crossplane.io_eksclusterclasses.yaml, config/crd/compute.aws.crossplane.io_eksclusters.yaml, pkg/controller/compute/eks.go
Remove the check for EKS regions because it's hard to keep the list updated manually
The AWS API will tell us an error anyway (albeit only during runtime). 
Relevant discussion: https://crossplane.slack.com/archives/CEG3T90A1/p1582580141019500?thread_ts=1582578523.016300&cid=CEG3T90A1
I have:
=> remove check for EKS regions

AUTHENTICATION.md
Adds documentation for enabling IAM roles for `ServiceAccounts` when running on `EKS`.
I have:
=> Add doc for using IAM roles for ServiceAccounts

AUTHENTICATION.md
without the escaping of :r zsh ends up with
```
$ echo eks.amazonaws.com/role-arn=arn:aws:iam::$AWS_ACCOUNT_ID:role/$IAM_ROLE_NAME
eks.amazonaws.com/role-arn=arn:aws:iam::123456789ole/crossplane
```
I have:
=> add escaping to make it work in zsh

apis/compute/v1alpha3/types.go, config/crd/compute.aws.crossplane.io_eksclusterclasses.yaml, config/crd/compute.aws.crossplane.io_eksclusters.yaml, pkg/clients/eks/eks.go, pkg/controller/compute/eks.go, pkg/controller/compute/eks_test.go
For backup support, `status` should be purely observational and its loss should not recur any cost, if possible. This is necessary for [backup and restore](https://github.com/crossplane/provider-aws/issues/181) workflows.
This PR makes EKS controller:
* use external name annotation for cluster name,
* save cloud formation stack id in spec,
* use version retrieved from the server instead of the one saved in status,
* save the version into status continuously instead of one time.
Fix error checking bug for case where the err is nil.
I think we can use external name for both cloud formation stack identification and also cluster name but I didn't want to touch that part; it's working and all will change in v1beta1 anyway.
I have:
[documentation]: …
=> eks: move identification data out of status

apis/storage/v1alpha3/bucket_types.go, config/crd/storage.aws.crossplane.io_s3bucketclasses.yaml, config/crd/storage.aws.crossplane.io_s3buckets.yaml, pkg/clients/iam/iam.go, pkg/clients/s3/s3.go, pkg/clients/s3/s3_test.go, pkg/controller/s3/claim.go, pkg/controller/s3/claim_test.go, pkg/controller/s3/s3bucket.go, pkg/controller/s3/s3bucket_test.go
Removing operational identifiers from status as part of https://github.com/crossplane/provider-aws/issues/181
* IAMUsername is stored in `spec` now.
* External name annotation is used as bucket name.
I have:
=> s3: move identifiers out of status

apis/network/v1alpha3/internetgateway_referencers.go, apis/network/v1alpha3/internetgateway_referencers_test.go, apis/network/v1alpha3/internetgateway_types.go, apis/network/v1alpha3/routetable_types.go, apis/network/v1alpha3/securitygroup_referencers_test.go, apis/network/v1alpha3/securitygroup_types.go, apis/network/v1alpha3/subnet_referencers.go, apis/network/v1alpha3/subnet_referencers_test.go, apis/network/v1alpha3/subnet_types.go, apis/network/v1alpha3/vpc_referencers.go, apis/network/v1alpha3/vpc_referencers_test.go, apis/network/v1alpha3/vpc_types.go, config/crd/network.aws.crossplane.io_internetgateways.yaml, config/crd/network.aws.crossplane.io_routetables.yaml, config/crd/network.aws.crossplane.io_securitygroups.yaml, config/crd/network.aws.crossplane.io_subnets.yaml, config/crd/network.aws.crossplane.io_vpcs.yaml, examples/compute/kubernetescluster/iam.yaml, examples/compute/kubernetescluster/network.yaml, examples/compute/kubernetescluster/resource-class.yaml, pkg/controller/network/internetgateway/controller.go, pkg/controller/network/internetgateway/controller_test.go, pkg/controller/network/routetable/controller.go, pkg/controller/network/routetable/controller_test.go, pkg/controller/network/securitygroup/controller.go, pkg/controller/network/securitygroup/controller_test.go, pkg/controller/network/subnet/controller.go, pkg/controller/network/subnet/controller_test.go, pkg/controller/network/vpc/controller.go, pkg/controller/network/vpc/controller_test.go
Adds the `crossplane.io/external-name` annotation to all AWS network resources. Network resources are uniquely identified by strings that are generated by AWS when they are created, so unlike most controllers these ones must update the `external-name` annotation to match the identifier generated by AWS. This replaces the previous pattern of saving this identifier under status, which we must assume could be lost during the lifetime of a resource.
Tested by creating an EKS cluster using all of the network resources, backing all resources up with Velero, and then restoring it.
I have:
[release notes]: …
=> Support backup and restore of AWS network resources

README.md, config/stack/manifests/app.yaml, config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml
The `portable resource abstractions` link no longer exists (this change was already made in release). The docs api references no longer exist on `master` and the `v0.7` release was the last one in which they did. These changes also remove almost all updates required in our branch prep PRs.
I have:
=> Remove missing docs links and minimize release branch prep

cluster/images/provider-aws/Dockerfile
This updates the provider-gcp Dockerfile to run as non-root
as the Crossplane stack manager will refuse to run containers
as root by default per https://github.com/crossplane/crossplane/pull/1444
See https://github.com/crossplane/provider-gcp/pull/223 for testing
I have:
=> Run provider-aws controllers as non-root

pkg/clients/iam/iamrole.go, pkg/clients/iam/iamrole_test.go
Signed-off-by: sahil-lakhwani <sahilakhwani@gmail.com>
Fix for late initializing of Tag field for IAMRole. The current code appends to the existing list, indefinitely. 
I have:
=> iamrole: fix late initialization of tags

config/package/manifests/install.yaml
This re-enables support for IAM Roles for Service Accounts by passing an fsGroup,
meaning that the projected service account token volume will be owned by the GID and the GID will be added as a supplemental group to the container process.
Fixes #211 
Depends on https://github.com/crossplane/crossplane/pull/1577
I have:
=> Pass fsGroup in install.yaml

apis/eks/v1beta1/referencers.go, apis/eks/v1beta1/types.go, config/crd/eks.aws.crossplane.io_clusters.yaml
EKS Cluster was mistakenly resolving IAM role references by getting the
role name rather than its ARN. This updates the the reference resolver
and also make the roleArn omitempty so that updates that have a null ARN
(i.e. all of them before it is successfully resolved) will not fail. A
few instances of ID were also changed to Id.
I have:
=> Make EKS cluster get ARN from IAM role reference

apis/database/v1beta1/rdsinstance_types.go, apis/database/v1beta1/zz_generated.deepcopy.go, config/crd/database.aws.crossplane.io_rdsinstanceclasses.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml, pkg/clients/rds/rds.go
Removes `dbClusterParamterGroup` as it seems it's not used in any API call and backup retention call was given as `0` for all cases for some reason, that's also fixed.
I have:
=> Remove unused dbClusterParamterGroup field from RDS

apis/database/v1beta1/rdsinstance_types.go, apis/database/v1beta1/zz_generated.deepcopy.go, config/crd/database.aws.crossplane.io_rdsinstanceclasses.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml, pkg/clients/rds/rds.go, pkg/controller/database/rdsinstance.go, pkg/controller/database/rdsinstance_test.go
We already had plans to use `Secret`s as input for sensitive fields [per managed resource design](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#sensitive-input-fields) but I think there hasn't been actual implementation of it yet.
I have implemented it for RDS mainly to address the use case @kelvinwijaya described in https://github.com/crossplane/provider-aws/issues/267 ; it's not possible to create a read replica instance for aurora to join an existing DB cluster since the password is required to be empty.
I have tested creating an Aurora MySQL cluster with no IAM auth and used the following YAML to join that cluster:
```yaml
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
name: mvf-test-replica
spec: …
```
=> Add MasterPasswordSecretRef to allow specifying a password for RDS

pkg/clients/aws.go, pkg/clients/aws_test.go
Adds support for additional `aws_session_token` key.
Fixes #278 
I have:
=> aws_session_token key should be used when credentials are parsed

apis/acm/v1alpha1/zz_generated.managed.go, config/crd/acm.aws.crossplane.io_certificates.yaml, pkg/controller/acm/controller.go, pkg/controller/acm/controller_test.go
This updates ACM Certificate to use the Reference instead of
ObjectReference for its ProviderRef type. This is currently causing a
build failure because the PR that added it was not rebased on master
after change to crossplane-tools generation.
I have:
=> Use crossplane-runtime Reference type for Provider in ACM Cert

pkg/clients/rds/rds.go, pkg/clients/rds/rds_test.go, pkg/controller/database/rdsinstance.go
I have discovered that our skip list was missing some fields that should be skipped since they don't appear on `ModifyDBInstanceInput`.
Also, AWS seems to have a bug where `DescribeDBInstances` request always returns `0` for `DbInstancePort` which triggers an update if the user entered `3306` or any custom port. I have reproduced the bug via AWS CLI, too: console says 3306 but CLI returns 0. Apparently, this [happens in Java SDK](https://github.com/aws/aws-sdk-java/issues/924#issuecomment-658089792), too. Luckily, there is another field we can retrieve the port and it seems to be working.
Fixes #285 
I have:
[release …
=> rds: fix unnecessary update requests

pkg/clients/aws.go, pkg/clients/aws_test.go, pkg/clients/eks/fake/fake.go, pkg/controller/eks/cluster.go, pkg/controller/eks/cluster_test.go
The AWS SDK has separate methods for adding and removing tags from an
EKS cluster. This updates the update method of its controller to make
separate calls for adding and removing tags.
Fixes #276 #251 
cc @janwillies 
I have:
=> Separate add and remove tag operations for v1beta1 EKS cluster

Makefile
Fixes `make run` which was expecting the binary to be named `provider` instead of `provider-aws`
I have:
=> fix make run

pkg/clients/ec2/fake/securitygroup.go, pkg/clients/ec2/securitygroup.go, pkg/controller/ec2/securitygroup/controller.go, pkg/controller/ec2/securitygroup/controller_test.go
`SecurityGroup` creates an inital egress rule and if user's egress rule corresponds to this existing one, no change is propagated such as description so it always returned that the resource is not up-to-date. Additionally, `-1` value for `fromPort` and `toPort` is special for AWS and they return `nil` for values of those fields if you had submitted `-1` and that'd cause not up-to-date error since spec has `-1` but observed value seems to be `nil`.
Fixes #296 
I have:
[`app.yaml`]: …
=> security group: remove the default egress and fix comparison issue

apis/ec2/v1beta1/common.go, apis/ec2/v1beta1/securitygroup_types.go, config/crd/ec2.aws.crossplane.io_securitygroups.yaml, pkg/clients/ec2/securitygroup.go, pkg/controller/ec2/securitygroup/controller.go
There is a `GenerateEC2Permissions` that covers all fields but it's not used; another one with less fields is used. So, I made a change to make it use the full one and implemented its missing correspondent conversion.
Fixes #304 
I have:
=> security group: implement full-fledged conversion functions for ip permissions

apis/cache/v1beta1/referencers.go, apis/cache/v1beta1/replication_group_types.go, apis/cache/v1beta1/zz_generated.deepcopy.go, config/crd/cache.aws.crossplane.io_replicationgroupclasses.yaml, config/crd/cache.aws.crossplane.io_replicationgroups.yaml
Fixes #313
I have:
- [✅] Run `make reviewable` to ensure this PR is ready for review.
- [✅] Ensured this PR contains a neat, self documenting set of commits.
- [✅] Updated any relevant [documentation], [examples], or [release notes].
- [✅] Updated the dependencies in [`app.yaml`] to include any new role permissions.
=> Referencer for SubnetGroup AWS ElasticCache

apis/v1alpha3/provider_types.go
Fixes a nil pointer dereference possibility. cc @frezbo
I have:
=> provider: fix deep copy nil pointer dereference possibility

apis/notification/v1alpha1/snstopic_types.go, config/crd/notification.aws.crossplane.io_snstopics.yaml, pkg/clients/sns/snstopic.go, pkg/clients/sns/snstopic_test.go
Fixes #347 
This PR just adds a field in the SNS Topic to store the ARN. The main reason this is important is so that when other functions require the ARN string, they can simply access the value in the status as opposed to querying the API.
I have:
=> Adds the ARN to the AtProvider for the SNS Topic

cluster/images/provider-aws/Dockerfile, cluster/images/provider-aws/Makefile, cluster/local/integration_tests.sh
Updates the provider package image to only include a single static
package.yaml file that can be parsed by the package manager.
Draft until https://github.com/crossplane/crossplane/pull/1795 is merged, which is required for integration tests to pass. Integration tests will also have to be updated to support loading the package image into the cache dir due to the fact that the package manager will no longer be able to pull from local docker (for the package image, loading into kind will still work for provider controller). This process
I have:
Integration tests demonstrate the functionality we are testing here, see https://github.com/crossplane/crossplane/pull/1807 for more info.
=> Build provider package with static content

pkg/clients/resourcerecordset/resourcerecordset.go
@skmcgrail [informed](https://github.com/aws/aws-sdk-go-v2/issues/803#issuecomment-706436385) that the array here is expected to be `nil` if it's empty. The issue doesn't exist in the newer versions of AWS SDK but until we update to the new versions, this fix is necessary.
Fixes https://github.com/crossplane/provider-aws/issues/372
Fixes #
I have:
Manually tested with an alias target.
=> Adopt AWS SDK behavior for resource record array

examples/s3/bucket.yaml, pkg/controller/s3/bucket.go, pkg/controller/s3/bucket/CORSConfig.go, pkg/controller/s3/bucket/accelerateConfig.go, pkg/controller/s3/bucket/accelerateConfig_test.go, pkg/controller/s3/bucket/lifecycleConfig.go, pkg/controller/s3/bucket/loggingConfig.go, pkg/controller/s3/bucket/loggingConfig_test.go, pkg/controller/s3/bucket/notificationConfig.go, pkg/controller/s3/bucket/notificationConfig_test.go, pkg/controller/s3/bucket/replicationConfig.go, pkg/controller/s3/bucket/requestPaymentConfig.go, pkg/controller/s3/bucket/sseConfig.go, pkg/controller/s3/bucket/taggingConfig.go, pkg/controller/s3/bucket/versioningConfig.go, pkg/controller/s3/bucket/versioningConfig_test.go, pkg/controller/s3/bucket/websiteConfig.go
Removes the `Delete` implementations of S3 subresources that do not have corresponding deletion call and fixes some bugs related to versioning and tagging.
Fixes https://github.com/crossplane/provider-aws/issues/368
Fixes https://github.com/crossplane/provider-aws/issues/379
Fixes #
I have:
Manually with `examples/s3/bucket.yaml`
=> s3: subresources that cannot be deleted should not have deletion implemented

pkg/controller/ec2/routetable/controller.go, pkg/controller/ec2/routetable/controller_test.go
Because the object returned by the api-server may not be latest, hence, causing spec update to fail which in turn creates additional routetable whose track is lost.
Keep in mind that this should not happen as status update already updates the local `cr` variable. However, we see this happening in some environments.
The actual solution to this problem is to have `Create` operations whose result has to be saved to be atomic, i.e. if spec update didn't go through then delete the created external resource.
Fixes #392
Fixes https://github.com/crossplane/provider-aws/issues/210
Fixes https://github.com/upbound/platform-ref-aws/issues/3
I have:
Manually.
=> routetable: do not issue status update before create 

pkg/clients/s3/bucket.go, pkg/controller/s3/bucket/accelerateConfig.go
Rig the `AccelerateConfigurationClient` such that it will not panic if the method or parameter is not allows for Acceleration Configuration similar to the Terraform Provider. This is necessary for some regions which does not have S3 acceleration support.
Fixes #388
I have:
Manually tested with bucket creation in region `us-gov-west-1`.
s3.yaml
```
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
name: crossplane-bucket
spec:
forProvider:
locationConstraint: us-gov-west-1
acl: private
versioningConfiguration:
status: Enabled
name: default
```
Output:
```
Normal   CreatedExternalResource  5s                 managed/bucket.s3.aws.crossplane.io  Successfully requested creation of external resource
```
=> S3 Acceleration Parameter Optional

go.mod, go.sum, pkg/clients/aws.go
We will be using ACK code generation pipeline to add new [resources](https://github.com/aws/aws-controllers-k8s/pull/444) to `provider-aws` but ACK and generated code works with AWS Go SDK v1 whereas we use v2. One place they differ is how they authorize. This PR adds a function specific to v1.
Fixes #
I have:
Not tested yet with an actual controller.
=> AWS Go SDK v1 connection method for ACK-generated resources

pkg/controller/s3/bucket/lifecycleConfig.go
This updates the GenerateLifecycleConfig method to not assume that a
non-nil Date is provided for every transition. This was causing a panic
if Days and/or StorageClass was provided but no Date was provided.
I have:
Unit tests.
=> Do not panic on missing date in bucket lifecycleConfig

examples/acm/certificate.yaml
when trying out the certificate example i got the following Warning: 
```
Warning  CannotCreateExternalResource  2s (x6013 over 5m2s)  managed/certificate.acm.aws.crossplane.io  
(combined from similar events): failed to create the Certificate resource: ValidationException: 
1 validation error detected: Value 'disabled' at 'options.certificateTransparencyLoggingPreference' failed to satisfy constraint: 
Member must satisfy enum value set: [ENABLED, DISABLED]
```
`Member must satisfy enum value set: [ENABLED, DISABLED]`
after changing the value like this: `certificateTransparencyLoggingPreference: DISABLED` the previous Warning is gone
```
Status:
At Provider:
Conditions:
Last Transition Time:  2020-11-13T21:23:39Z
Reason:                Creating
Status:                False
Type: …
```
=> fix examples/acm/certificate.yaml

pkg/controller/s3/bucket/lifecycleConfig.go, pkg/controller/s3/bucket/lifecycleConfig_test.go
Signed-off-by: Krish Chowdhary <krish@redhat.com>
Fixes #430 
This PR makes the filter in the s3 bucket lifecycle empty by default, as opposed to `nil`. This is because S3 expects an empty dictionary as opposed to nil if no filter is provided. 
I have:
Manual testing with an S3 Bucket, and updated unit-tests
=> s3 bucket: make the filter an empty dictionary by default

apis/ec2/v1beta1/referencers.go, apis/ec2/v1beta1/securitygroup_types.go, apis/ec2/v1beta1/zz_generated.deepcopy.go, package/crds/ec2.aws.crossplane.io_securitygroups.yaml
I just realized that we have `VPCID` but no reference or selector fields for it.
Fixes #
I have:
Not tested manually yet.
=> securitygroup: add reference and selector fields to UserIDGroupPair

pkg/clients/sqs/queue.go, pkg/clients/sqs/queue_test.go
AWS does not expect FifoQueue attribute if it is false and a `nil` map should be sent if no attribute is defined.
Fixes https://github.com/crossplane/provider-aws/issues/457
I have:
Tested with the following YAMLs:
```yaml
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
name: test-fifo.fifo
spec:
forProvider:
fifoQueue: true
name: default
---
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
name: test-fifo.fifo
spec:
forProvider:
fifoQueue: false
name: default
---
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
name: test-fifo.fifo
spec:
forProvider:
name: default
```
=> Queue API exceptions

apis/cache/v1alpha1/referencer.go
The referencer for the CacheCluster and ResolveReferences was previously removed by accident. This PR aims to add that functionality back in. There are no changes to the API, only to the referencer.
I have:
Manual testing with an ElastiCache replicationgroup.
=> cache: add referencer for subnet group and cluster

apis/s3/v1beta1/bucket_types.go, examples/s3/bucket.yaml, package/crds/s3.aws.crossplane.io_buckets.yaml, pkg/controller/s3/bucket.go, pkg/controller/s3/bucket_test.go, pkg/controller/s3/testing/testHelper.go
This PR fixes an issue outlined on the Crossplane slack channel regarding the ACL field in the bucket resource. Additionally, one piece of functionality that we lost when bringing the s3 bucket to v1beta1 was the connection secret containing the endpoint of the bucket. This is something that I am adding back in this PR.
Slack Conversation: https://crossplane.slack.com/archives/CEG3T90A1/p1607034420017100?thread_ts=1607033622.011100&cid=CEG3T90A1
I have:
Updated unit tests, manual testing via the examples manifest.
=> Optional ACL, Endpoint secret

pkg/controller/s3/bucket/sseConfig.go, pkg/controller/s3/bucket/sseConfig_test.go
Make sure we compare KMSMasterKeyID correctly in the s3/sseConfig subresource
When Observing the server side encryption configuration the code was comparing string pointers when checking whether the KMSMasterKeyID needs updating.
Fixes #496 
I have:
As this is a fairly trivial fix, I haven't done additional tests. Used TDD to verify the test failure first.
=> Make sure we compare KMSMasterKeyID correctly in the s3/sseConfig subresource

pkg/clients/sqs/queue.go, pkg/clients/sqs/queue_test.go, pkg/controller/sqs/queue/controller.go, pkg/controller/sqs/queue/controller_test.go
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
Per the [provider-aws docs](https://doc.crds.dev/github.com/crossplane/provider-aws/sqs.aws.crossplane.io/Queue/v1beta1@v0.16.0#spec-writeConnectionSecretToRef) Queue supports `writeConnectionSecretToRef` but does not write any connection details.  This PR writes the queue URL to the endpoint value in the connection secret.
I have:
- [X ] Read and followed Crossplane's [contribution process].
- [X ] Run `make reviewable test` to ensure this PR is ready for review.
Unit tests and manual testing
=> write sqs queue url to connection secret ref

Makefile, cluster/images/provider-aws/Makefile, package/crossplane.yaml
I would like to run a custom build of the AWS provider and for this I would like to upload the built Docker images to my own Docker registry.
The current setup has the following limitations:
- the value of DOCKER_REGISTRY can not be overridden when running make targets - this is just an inconvenience as it's easy to tag the built images
- the Docker image name for the controller is baked in as `crossplane/provider-aws-controller:VERSION` - this is again a minor inconvenience because you can override the image using the ControllerConfig CRD.
Still it's more convenient if I can do a full build, upload both images and I only have to update the spec.package on the Provider object.
For reference I was running the following commands:
```
PLATFORMS=linux_amd64 DOCKER_REGISTRY=quay.io/acme …
```
=> Support custom Docker registry when building the Docker images

pkg/controller/s3/bucket/subresources.go
Fixes #553 
I have:
- [] Run `make reviewable test` to ensure this PR is ready for review.
Previously the reconciliation would be blocked since the versioning could never complete because of a replication error based on the fact that there is no versioning. This is resolved now by fixing the ordering in the `subresource.go` folder.
I did manual testing with two S3 buckets, I can provide the gists if that would be helpful. But essentially, the first was a regular S3 bucket, and the second was an S3 bucket with versioning enabled, as well as a replication configuration pointing to the first bucket. There was a role that had access to both buckets, set up on the replication configuration as well. 
Previously, the 2nd bucket would never finish reconciling, but that is resolved now. …
=> bucket: versioning + replication configuration sub resource ordering fix

pkg/controller/ec2/internetgateway/controller.go, pkg/controller/identity/iamrole/controller.go
Using semgrep I found som additional places where awsclient.Wrap was not
used on an error from the AWS API.
docker run --rm -v "${PWD}:/src" returntocorp/semgrep --force-color -f ./err.yaml --lang=go ./pkg/controller/
err.yaml:
rules:
- id: unclean-aws-err
patterns:
- pattern-either:
- patterns:
- pattern: |
return managed.ExternalCreation{}, errors.Wrap(err, ...);
- pattern-inside: |-
func ($T $TYPE) Create(...) {
...
}
patterns:
- pattern: |
return managed.ExternalUpdate{}, errors.Wrap(err, ...);
- pattern-inside: |-
func ($T $TYPE) Update(...) {
...
}
patterns:
- pattern: |
return errors.Wrap(...);
- pattern-inside: |-
func ($T $TYPE) Delete(...)  {
...
}
- pattern-not-inside: |
if err := $X.preCreate(...); err != nil {
...
}
- pattern-not-inside: |
if err := $X.preUpdate(...); err != …
=> iamrole, internetgateway: use awsclient err wrapper

examples/database/rdsinstance.yaml, pkg/clients/rds/rds.go
Seems like it wasn't used in late-init because observation object returns an array. It's safe to assign the first value since there is more than value only during a change and that doesn't happen in creation where late-init is used.
Fixes https://github.com/crossplane/crossplane/issues/2187
I have:
=> database.rdsinstance: add DBSubnetParameterGroupName to late init

AUTHENTICATION.md
Update authentication documentation with serviceAccount recommendation for provider upgrade
We use pod-iam which requires assigning the service account name to the aws role.  The problem is that the service account name is the provider-aws revision and it changes during the release, breaking crossplane permissions
Ex.  v.0.16.0 - provider-aws-6b36ca882d8e and v.0.17.0 - provider-aws-4ebd5d8c7cb7
Using a static `StringEquals` condition with a hard coded provider will break when the `SERVICE_ACCOUNT_NAME` changes when the provider is upgraded
```
"StringEquals": {
"${OIDC_PROVIDER}:sub": "system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:${SERVICE_ACCOUNT_NAME}"
}
```
This condition can be avoided by using an alternative IAM policy which …
=> Update authentication documentation

pkg/clients/ec2/vpc.go, pkg/controller/ec2/vpc/controller.go, pkg/controller/ec2/vpc/controller_test.go
Signed-off-by: chris <cvodak@ea.com>
Fixes #558 Only send vpc attributes if set. Also added lateInitialization as EnableDnsSupport has a default of true if not set.
I have:
Ran and added to unit tests. Created a test vpc setting neither enableDnsHostNames or  enableDnsSupport of the values in the issue. Modified the vpc changing values to ensure they were updated in aws correctly.
=> Fix for 558, only send vpc attributes if set

pkg/clients/ec2/securitygroup.go, pkg/clients/ec2/securitygroup_test.go
When ipProtocol is -1, fromPort/toPort will be nil. This causes a panic
when sorting ingress/egress rules. We just need a stable sort so we can
use an aws helper to get 0 for the value in that case.
Also add a normal test for the sort functions (have more than one item so we will sort something).
Fixes #616
I have:
* Unit test
* YAML from #616
=> ec2.securitygroup: Handle nil fromPort/toPort (ipProtocol -1)

pkg/clients/ec2/fake/securitygroup.go, pkg/clients/ec2/securitygroup.go, pkg/controller/ec2/securitygroup/controller.go
Fixes #504
Use tag helper function to detect added/removed/updated tags, and call the delete tag API before we call the create tag API.
I have:
- created object with tags
- mutated one tag
- delete multiple tags
- delete all tags (fails, see #625)
=> ec2.securitygroup: fix update/delete/add tags

pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticache_test.go
At the moment, it is only possible to send in version 6.x for redis
engine version on redis 6, but AWS will return back a specific version
like 6.0.5.
In this case, redis will never become ready.
Change the controller to consider the resource up to date when we
specify 6.x and have 6.0.5.
Fixes #622
I have:
* added unit test
* created redis 6.x cluster and check that it is ready
```
k get replicationgroup 
NAME                               READY   SYNCED   STATE       VERSION   AGE
redis-s9c9r-vw7mx                  True    True     available   6.x       3h3m
```
=> cache.replicationgroup: Support pattern matching for engine version

apis/kms/v1alpha1/zz_types.go, go.mod, go.sum, pkg/controller/lambda/function/setup.go
It got added because I merged a PR that's been generated by an older version of ACK that included it. Added a small fix as well.
I have:
`make reviewable`
=> go.mod: regenerate to remove ack dependency

.gitignore, Makefile
Added support for AWS service code-generator in Makefile. Fixes #526
Usage:
make service SERVICE_ID=<some aws service name>
Signed-off-by: Nitin Rajput <nitinrajput706021@gmail.com>
=> Add AWS code-generator to makefile targets

pkg/controller/ec2/vpccidrblock/controller.go
Signed-off-by: Amna Irfan <amirfan@ea.com>
CIDR blocks are attached to VPCs so deleting a VPC in Crossplane automatically deletes the CIDR block in AWS. However the CIDR resource does not get deleted in Crossplane. The deletion gets stuck in a loop since AWS first tries to get the VPC and when the VPC doesn't exist it sends a VPC not found error while the code is waiting for a CIDR not found error.
We just need to account for the VPC not found error while deleting a CIDR block.
Fixes #677
I have:
1. Create a VPC in Crossplane
2. Create a CIDR block for that VPC
3. Delete the VPC in Crossplane (it wont ask you to delete the CIDR block)
4. Delete the CIDR block in Crossplane (it will no longer give an error that vpc doesn't exist)
=> Fix VPC CIDR Block Deletion

pkg/controller/rds/dbcluster/setup.go
Endpoint was not being copied into the connection details of the generated RDS `DBCluster` reconciler. This adds the endpoint field as it is trivially available in the `status` of the resource, and returns the FQDN (minus port) of the instance.
This does _not_ set the port as well, as it is not exposed by the status. I suspect in most cases this is defaulted from the AWS side, and it doesn't look like late init is implemented for this reconciler yet (so we potentially have no value to populate).
Fixes #695 
I have:
Test suite passes but I don't think this particular method is directly targeted. Will be using the built image to test on a live cluster.
=> Add endpoint to RDS DBCluster connection details

apis/route53/v1alpha1/hostedzone_types.go, examples/servicediscovery/httpnamespace.yaml, examples/servicediscovery/publicdnsnamespace.yaml, package/crds/route53.aws.crossplane.io_hostedzones.yaml
This PR ensures working examples for the resources mentioned [here](https://github.com/cncf/crossplane-conformance/issues/4#issuecomment-856232337).
It also marks HostedZone `status.atProvider` as optional for Crossplane Conformance.
I have:
1. Deploy crossplane 1.2.2 and provider-aws with these changes.
1. Setup a ProviderConfig
1. Create a VPC (e.g. using `examples/ec2/vpc.yaml`) and provide its `id` in `examples/servicediscovery/privatednsnamespace.yaml`
1. Create example resources under `examples/servicediscovery` and ensure they are reporting ready/synced.
=> Add Examples for Service Discovery

pkg/clients/ecr/repository_policy.go, pkg/clients/ecr/repository_policy_test.go
Resolves a couple of issues around detecting changes on the ECR
`RepositoryPolicy` type:
1. Converts `awsAccountId` principals that were not specified as an
ARN into the ARN format, as AWS always returns in this format from
the API.
2. Makes sure to sort string slices within the policy document during
comparison, to avoid issues where AWS returns values in a different
order.
Fixes #700
Signed-off-by: Ben Agricola <bagricola@squiz.co.uk>
I have:
Additional test added to compare policies with defined principals as a string slice, that tests both of these cases.
That test fails without the fixes applied.
=> Fix ECR Repo policy eternally updating

cluster/local/integration_tests.sh
We're seeing increase in e2e test failures due to conditions being not met after a specific duration. Increasing the timeout would just make it take longer because the checks were not done periodically. So, I changed it to run periodically and use the related tools' waiting mechanisms wherever possible, like `helm`'s `--wait` flag and `kubectl wait --timeout=60s` command.
I have:
Manually with `make e2e`
=> e2e: replace sleep commands with wait directives of the related tools

apis/cache/v1beta1/referencers.go, apis/cache/v1beta1/replication_group_types.go, apis/cache/v1beta1/zz_generated.deepcopy.go, examples/cache/replicationgroup.yaml, package/crds/cache.aws.crossplane.io_replicationgroups.yaml
This PR adds a `cacheSubnetGroupNameRef` (singular) reference. The existing (accidentally) plural `cacheSubnetGroupNameRefs` field is maintained for backward compatibility.
I have:
I've created a `ReplicaGroup` using the examples under`examples/cache` and validated that that:
* If both reference fields are set we get an error.
* If the deprecated plural field is set, we use that.
* Otherwise we use the new singular field.
=> Use singular, not plural cacheSubnetGroupNameRef in ReplicaGroup

go.mod, go.sum
Pinning this dependency in preparation to release v0.19.
I have:
I've just run `make reviewable`. It looks like in practice this bump only pulls in one change to crossplane-runtime, which pertains to the package parser (that is not used by this provider) per https://github.com/crossplane/crossplane-runtime/compare/ded177829557...v0.14.0.
=> Pin crossplane-runtime to v0.14.0

apis/sfn/v1alpha1/generator-config.yaml, pkg/controller/sfn/activity/zz_conversions.go, pkg/controller/sfn/statemachine/zz_conversions.go
fixed ressources exeptions errors in generator-config.yaml for sfn
Fixes #725
I have:
statemachine:
```
➜  sfn git:(master) ✗ kubectl apply -f statemachine.yaml 
statemachine.sfn.aws.crossplane.io/sample-statemachine created
➜  sfn git:(master) ✗ kubectl delete -f statemachine.yaml
statemachine.sfn.aws.crossplane.io "sample-statemachine" deleted
```
activity:
```
➜  sfn git:(master) ✗ kubectl apply -f activity.yaml 
activity.sfn.aws.crossplane.io/sample-activity created
➜  sfn git:(master) ✗ kubectl delete -f activity.yaml 
activity.sfn.aws.crossplane.io "sample-activity" deleted
```
output from deletion:
statemachine:
```
2021-06-17T10:05:26.162+0200	DEBUG	controller-runtime.manager.events	Normal	{"object": …
```
=> fix sfn 404 for deletion

pkg/controller/acm/controller.go
Fixes #735
I have:
```
NAME                                                DOMAINNAME                     STATUS   READY   SYNCED   AGE
certificate.acm.aws.crossplane.io/poc-certificate   *.mesh-pca.svc.cluster.local   ISSUED   True    True     3m19s
```
```
kubectl describe certificate.acm.aws.crossplane.io/poc-certificate
Name:         poc-certificate
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-name: arn:aws:acm:eu-central-1:255932642927:certificate/19b93893-59e9-4fd5-bf11-6fbfc8d34625
API Version:  acm.aws.crossplane.io/v1alpha1
Kind:         Certificate
Metadata:
Creation Timestamp:  2021-06-26T20:18:13Z
Finalizers:
finalizer.managedresource.crossplane.io
Generation:        2
Resource Version: …
```
=> Fixes #735 acm - fixed synced false when using private ca

pkg/controller/aws.go, pkg/controller/config/config.go
The polling interval is currently being passed to the ProviderConfig
controller, which does not use it.
Follow up to #741 
I have:
Non-functional change.
=> Do not pass poll interval to ProviderConfig controller

apis/ec2/v1beta1/address_types.go, package/crds/ec2.aws.crossplane.io_addresses.yaml
Update a few of the descriptions for the `addresses.ec2.aws.crossplane.io` CRD.
Refer to EIPs instead of VPC.  
I have:
Since it is just documentation I have not done any testing
=> Fix Address descriptions

pkg/clients/rds/rds.go
When a version upgrade is pending, this was excluded (presumably by accident) from the status of RDSInstance.
I have:
Deploy PG 13.1
Upgrade to 13.2
Verified the status during upgrade
=> database.rdsinstance: show pending EngineVersion

apis/s3/v1beta1/replicationConfiguration_types.go, package/crds/s3.aws.crossplane.io_buckets.yaml
Add storage class STANDARD as an option.
I have:
Created replication rule and check the console.
=> s3: replication storage class STANDARD was missing

pkg/clients/iam/iamrole.go, pkg/clients/iam/iamrole_test.go, pkg/controller/identity/iamrole/controller.go
The issue I'm having is that I have a resource that is out-of-sync, and I am having a hard time debugging the reason it keeps getting flagged as out-of-sync. I would like to add the option of an additional debug level log that details why a resource's observed state does not match its desired state.
I have created a PR to update the crossplane-runtime library with https://github.com/crossplane/crossplane-runtime/pull/272 . This PR of provider-aws is dependent on that being merged, and provider-aws updating to use the new version of crossplane-runtime. (Unit tests in this PR will only pass once that has been done)
In that PR I added the option for an ExternalObservartion to have a debug level message. This PR takes advantage of that and adds details describing the change. It also shows the …
=> Add Observation Debug logs

examples/servicediscovery/httpnamespace.yaml, examples/servicediscovery/privatednsnamespace.yaml, examples/servicediscovery/publicdnsnamespace.yaml, pkg/controller/servicediscovery/commonnamespace/hooks.go
Fixes #738 
if description is empty the status is READY=FALSE because of lateInited = true,
also removed description in examples because it's not required
before the fix:
```
NAME                                                                                      READY   SYNCED   EXTERNAL-NAME
privatednsnamespace.servicediscovery.aws.crossplane.io/example-privatednsnamespace        True    True     ns-ngfbsrd3zfnp3qnj
privatednsnamespace.servicediscovery.aws.crossplane.io/testnamespace.svc.cluster.local    False   True     ns-oslzgdargwixvklp
privatednsnamespace.servicediscovery.aws.crossplane.io/testnamespace2-svc-cluster-local   False   True     ns-vbcc5n6l5wel5vfr
```
after the fix:
```
NAME                                                                                      READY …
```
=> Fixes #738: servicediscovery (common)namespace READY=FALSE

.github/ISSUE_TEMPLATE/new_resource_request.md
Adds an issue template for new resource requests to automate labelling and ask the usual questions we ask in such issues.
cc @luebken
I have:
N/A
=> github: add issue template for new resource request

apis/database/v1beta1/rdsinstance_types.go, pkg/controller/database/rdsinstance.go
Add some more "known good" states in which an RDS instance can receive
requests:
* Modifying
* Backing Up
* Configuring Enhanced Monitoring
Fixes #760
I have:
In AWS
=> database.rdsinstance: Add more ready states (can receive requests)

pkg/controller/s3/bucket/replicationConfig.go
The filter part of a replication rule is as far as I can tell optional in the documentation. However, it was not possible to create a filter-less replication rule similar to the XML examples.
Using cloud trail and the console noticed that if you create a rule in the s3 console, cloud trail says `filter: ""`. With `aws s3api get-bucket-replicaton` I see `"Filter": {},`. However, in the XML examples, there is no filter:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-add-config.html#replication-config-min-rule-config
It turns out that if you don't want a filter, you still have to include the filter element to the Go SDK.
Question: I'm not sure if this is an issue with the Go SDK, or if the documentation is simply wrong, that you need a filter XML tag? If we can dump the …
=> s3: replication configuration - allow user to drop Filter similar AWS documentation

AUTHENTICATION.md
Simplify using IRSA by using `eksctl` for creating IAM role and IAM role trust relationship.
=> Use eksctl when creating the IAM role and trust relationship

apis/ecr/v1alpha1/policy_types.go, package/crds/ecr.aws.crossplane.io_repositorypolicies.yaml, pkg/controller/ecr/repositorypolicy/controller.go, pkg/controller/ecr/repositorypolicy/controller_test.go
Amazon ECR's `GetRepositoryPolicyRequest` API appears to return policy
statement entries in any order it feels like - this is properly handled
by Crossplane when identifying if a policy needs an update, but we fall
foul of Kubernetes' handling of resource watches, where the changing
`policyText` contents of the resource trigger a new reconcile straight
after the previous one.
This causes constant API observations, and with enough ECR policies and
a short enough poll interval, blows out the connection pool of the AWS
SDK.
Removing the `policyText` observation field and using the data available
from the API response call to detect updates avoids this situation from 
occurring.
Signed-off-by: Ben Agricola <bagricola@squiz.co.uk>
Fixes #780 
I have:
Extra test added to make sure the resource …
=> Remove ECR policyText observation

pkg/clients/hostedzone/hostedzone.go
obs.DelegationSet.Id  status is nil for example for privateHostedZones - added check
Fixes #797
I have:
create hostedZone without error in provider-aws
=> fix(hostedzone): fix DelegationSet.id can be nil panic

pkg/clients/aws.go, pkg/clients/aws_test.go, pkg/clients/ecr/repository_policy.go, pkg/clients/ecr/repository_policy_test.go, pkg/clients/iam/iamrole.go, pkg/clients/iam/iamrole_test.go, pkg/controller/ecr/repositorypolicy/controller.go
Reuse the improved code for IAM policy comparision from the ECR package.
Currently two IAM assume role policy documents do not match when they
use maps in condition keys, because JSON-encoded Go maps are not ordered.
This has already been handled in the ECR package, so we can reuse this
code. It should probably be moved to a common package.
Add a test to trigger a diff in a policy, and also verify that the error
code from diff is as expected.
Updates #704
Fixes #792
cc @benagricola 
I have:
* existing unit test works
* "for ever updating" IAMRole in test env is now synced and ready
* modified iam policy in aws console, verified that it was rolled back to the desired state
=> iam.iamrole: Use improved policy comparision function

pkg/clients/acm/certificate.go, pkg/clients/ec2/address.go, pkg/clients/ec2/instance.go, pkg/clients/ec2/internetgateway.go, pkg/clients/ec2/natgateway.go, pkg/clients/ec2/routetable.go, pkg/clients/ec2/securitygroup.go, pkg/clients/ec2/subnet.go, pkg/clients/ec2/vpc.go, pkg/clients/ec2/vpccidrblock.go, pkg/clients/ecr/repository.go, pkg/clients/ecr/repository_policy.go, pkg/clients/iam/iam.go, pkg/clients/resourcerecordset/resourcerecordset.go, pkg/clients/s3/bucket.go, pkg/clients/s3/bucketpolicy.go, pkg/clients/sqs/queue.go
Fixes #868
I have:
Tested ec2.SecurityGroup, ECR.Repository, ECR.RepositoryPolicy and S3.Bucket.
Tested ok in our environment with a fork, where it previously failed.
We are not running all the affected types, so not every change has been thoroughly tested.
=> #868 Fix broken handling of errors after aws-sdk-v2 migration

examples/dynamodb/backup.yaml, examples/dynamodb/globaltable.yaml, examples/dynamodb/table.yaml, pkg/controller/dynamodb/table/hooks.go
- implemented postUpdate
- implemented connectionSecret
- implemented in preUpdate SSESpecification, BillingMode
- implemented for SSESpecification lateInit to get kms keyarn
Fixes #580 #637
I have:
added new examples from #580 and tested create, update & deletion
```
kubectl get tables
NAME                       READY   SYNCED   EXTERNAL-NAME
sample-table-ppr           True    True     sample-table-ppr
sample-table-with-sse      True    True     sample-table-with-sse
sample-table-with-stream   True    True     sample-table-with-stream
sample-table-without-sse   True    True     sample-table-without-sse
```
connection secret is now possible: for LatestStreamArn, LatestStreamLabel, TableArn, TableName
stream_enabled = true
``` …
```
=> fix(dynamodb-table): dynamodb-table sync & reconcile

pkg/controller/dynamodb/table/hooks.go
Fixes #580 (some more)
Fixes #637
This PR follows on from #839. which recently fixed the DynamoDB table controller such that it was possible to configure PAY_PER_REQUEST and SSE, but part of doing this involved potentially making a no-op update and ignoring the resulting error. This commit avoids the no-op update by (hopefully) improving the logic that determines which update(s) are needed.
It also switches the connection details from `PascalCase` to `camelCase`. This isn't codified anywhere but `camelCase` is more idiomatic. Note that this shouldn't be a breaking change because the `PascalCase` connection details were never included in a release.
I have:
I've tested using the examples added in #839. I've also checked that I can:
* Update the …
=> Tweak DynamoDb table update logic and connection secret keys

pkg/clients/aws.go
added region for `config.LoadDefaultConfig` since it was dropped after v2 migration
v0.19.0:
https://github.com/crossplane/provider-aws/blob/release-0.19/pkg/clients/aws.go#L343
v0.20.0:
https://github.com/crossplane/provider-aws/blob/release-0.19/pkg/clients/aws.go#L234
Fixes Community Question from Slack:
```
Kelly Ferrone: For some reason all my aws resources end up in only one region? Why would this happen? Even though I say region: us-east-1
it is always
region: us-west-2
I see on provider-aws pod it does have AWS_REGION: us-west-2
Is this because of using the injected Identity
Milan Laketic: I can now confirm that I have the same behavior. On provider v0.19.1 I can normally provision in another region, but on latest I get resources …
```
=>  fix multi-region with injected identity -  after v2 migration v0.20.0

examples/dynamodb/table.yaml, pkg/clients/aws.go, pkg/controller/dynamodb/table/hooks.go, pkg/controller/dynamodb/table/hooks_test.go
The diff and update methods aren't generated for that field since its name and type is different in `UpdateTableInput` from `CreateTableInput`. So, we had to manually implement the whole mechanism.
Fixes a few small things like getting rid of cmpopts for `isUpToDate` and making sure we strip off the request ID from v1 SDK errors.
Fixes https://github.com/crossplane/provider-aws/issues/927
Note that it turned out `ReplicaUpdates` is only for `GlobalTable` resource and it's already implemented.
I have:
Manually with the example YAML by;
* Create a normal table without Global Secondary Index (GSI).
* Add a new GSI.
* Delete the GSI by making that array zero-length.
=> dynamodb.table: implement update for global secondary indexes

README.md
Adds release policy to README. I didn't want to add a release table like in Crossplane because there is no official active verisons or support policy around provider versions yet.
Fixes https://github.com/crossplane/provider-aws/issues/878
I have:
N/A
=> readme: add release policy

apis/ec2/manualv1alpha1/common.go, package/crds/ec2.aws.crossplane.io_instances.yaml
Signed-off-by: vaspahomov <vas2142553@gmail.com>
Make Name and Arn fields of IAMInstanceProfileSpecification optional.
Aws api required only one of this fields specified but not both. 
I have:
Manually tested on my crossplane/provider-aws installation
=> Make ec2 Instance IAMInstanceProfileSpecification fields optional

apis/s3/v1beta1/referencers.go, apis/s3/v1beta1/replicationConfiguration_types.go, examples/iam/role.yaml, examples/iam/rolepolicyattachment.yaml, examples/s3/bucket.yaml, package/crds/s3.aws.crossplane.io_buckets.yaml
The replication destination bucket should resolve to an ARN, not a bucket name.
Fixes #745
I have:
With blood, sweat and tears. Fixed three other issues first.
This is a "minimal" configuration (excluding role and policy):
```yaml
---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
annotations:
crossplane.io/external-name: repl-src.2021-06-07
name: repl-src
spec:
forProvider:
acl: private
locationConstraint: eu-north-1
paymentConfiguration:
payer: BucketOwner
serverSideEncryptionConfiguration:
rules:
- applyServerSideEncryptionByDefault:
sseAlgorithm: AES256
versioningConfiguration:
status: Enabled
replicationConfiguration:
role: arn:aws:iam::...:role/s3-replication-test # assumable by s3 svc, I just tested with an s3 admin role
rules:
- destination: …
```
=> s3: resolve bucket ARN in replication config references

apis/ec2/v1beta1/natgateway_types.go, examples/ec2/private-natgateway.yaml, package/crds/ec2.aws.crossplane.io_natgateways.yaml, pkg/controller/ec2/natgateway/controller.go, pkg/controller/ec2/natgateway/controller_test.go
added option to create private-natgateway - to use the natgateway for transit-gateway without internet-gateway
https://aws.amazon.com/de/about-aws/whats-new/2021/06/aws-removes-nat-gateways-dependence-on-internet-gateway-for-private-communications/
I have:
```
kubectl apply -f examples/ec2/private-natgateway.yaml  
kubectl apply -f examples/ec2/natgateway.yaml 
```
```
kubectl delete -f examples/ec2/private-natgateway.yaml  
kubectl delete -f examples/ec2/natgateway.yaml 
```
```
kubectl describe natgateway.ec2.aws.crossplane.io/private-natgateway
Name:         private-natgateway
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2021-10-20T22:12:00+02:00
crossplane.io/external-create-succeeded: …
```
=> Implements private nat-gateway

pkg/clients/aws.go, pkg/clients/aws_test.go, pkg/controller/cloudfront/cachepolicy/lateinit.go, pkg/controller/cloudfront/cachepolicy/lateinit_test.go, pkg/controller/cloudfront/cachepolicy/setup.go, pkg/controller/cloudfront/distribution/lateinit.go, pkg/controller/cloudfront/distribution/lateinit_test.go, pkg/controller/cloudfront/distribution/setup.go
Fixes https://github.com/crossplane/provider-aws/issues/894
CloudFront Distributions and CachePolicies were built to use a generic reflect based late initialization library that can match two similar structs. While this approach is probably good for simpler APIs and is much more scalable than hand writing code as I've done here, we found that it was tricky to debug and customise the late-init logic and the IsUpToDate functions that use it.
Notably, the Distribution API seems to:
* Always return CloudFrontDefaultCertificate: nil, which causes false positives in IsUpToDate.
* Not return slices in the order they were supplied, making it impossible to late init slices of structs based on index alone.
* Require some slices of structs (e.g. Origins) to be late initialized.
I believe the reflect …
=> Manually late-init CloudFront Distributions 

pkg/controller/s3/bucket/requestPaymentConfig.go, pkg/controller/s3/bucket/requestPaymentConfig_test.go, pkg/controller/s3/bucket_test.go
Fixes https://github.com/crossplane/provider-aws/issues/784
In aws-sdk-go-v2 the `Payer` property for `GetBucketRequestPaymentOutput` has changed.
Previously it was a string:
https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#GetBucketRequestPaymentOutput
But in v2 it is a type:
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#GetBucketRequestPaymentOutput
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3@v1.18.0/types#Payer
Perhaps it was set via `LateInitialize` previously?   Either way, the comparison functionality is broken now.
What is currently happening is if `PayerConfiguration` is not set it will ALWAYS need an update due to this code block:
```
case config == nil && len(external.Payer) != 0:
return NeedsUpdate, nil
```
This fixes the comparison …
=> fix s3 nil paymentConfiguration preventing bucket from being ready

pkg/controller/s3/bucket/notificationConfig.go, pkg/controller/s3/bucket/notificationConfig_test.go
fixes s3 notificationConfiguration continually being updated.
Updates `IsUpToDate` comparisons for `notificationConfiguration` - most notably ignore the `Id` and ignore ordering when there are multiple configurations.
Adds additional unit tests.
Note: this excludes the `Id` properties during the comparison.  This *should* be fine because the actual rules are being compared. 
Per the docs https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-notification-configuration.html
> Id -> (string)
An optional unique identifier for configurations in a notification configuration.  If you don't provide one, Amazon S3 will assign an ID.
Ignoring the `Id` in the comparison is workaround since these properties are not `LateInitialized`
Fixes …
=> fix s3 notificationConfiguration

apis/s3/v1beta1/replicationConfiguration_types.go, package/crds/s3.aws.crossplane.io_buckets.yaml, pkg/controller/s3/bucket/replicationConfig.go, pkg/controller/s3/bucket/replicationConfig_test.go
See - https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-add-config.html
Adds support for `DeleteMarkerReplication` with status of `Enabled`.  Previously only `Disabled` was supported but `Enabled` is a valid value.
Fixes #
As part of the aws sdk go v2 bucket it appears replicationConfiguration without specifying a filter no longer results in valid XML.  
Previously when a filter was defined as `filter: {}` the provider would send XML similar to 
```
<ReplicationConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Rule>
<ID>1</ID>
<Priority>0</Priority>
<Status>Enabled</Status>
<DeleteMarkerReplication>
<Status>Enabled</Status>
</DeleteMarkerReplication>
<Filter/>
<Destination> …
```
=> support for s3 replicationConfiguration with delete marker enabled (and fixes)

apis/ec2/v1beta1/referencers.go, apis/ec2/v1beta1/securitygroup_types.go, apis/ec2/v1beta1/zz_generated.deepcopy.go, package/crds/ec2.aws.crossplane.io_securitygroups.yaml, pkg/clients/ec2/fake/securitygroup.go, pkg/clients/ec2/securitygroup.go, pkg/clients/ec2/securitygroup_diff.go, pkg/clients/ec2/securitygroup_diff_test.go, pkg/clients/ec2/securitygroup_test.go, pkg/controller/ec2/securitygroup/controller.go, pkg/controller/ec2/securitygroup/controller_test.go
Implement a "diff rules" function.
When adding a rule, we should not send the complete rule set, only the
new rule.
When updating a rule, we must first delete it. And with that done, we
also support deleting rules.
Fixes #503
Fixes #300
I have:
- manually added/modified/removed simple ingress rules with cidr blocks.
- unit tests (for IP-ranges)
TODO
=> ec2.securitygroup: fix add, implement revoke/update ingress and egress rules

examples/dynamodb/table.yaml, pkg/clients/aws.go, pkg/controller/dynamodb/table/hooks.go, pkg/controller/dynamodb/table/hooks_test.go
Fixes https://github.com/crossplane/provider-aws/issues/946
Fixes https://github.com/crossplane/provider-aws/issues/953
This PR fixes a class of bugs that were causing Crossplane to think it needed to update a DynamoDB Table when it did not. Crossplane thought it needed to make updates because its desired state appeared to differ from the actual observed state of the table. In fact there was no difference - the problem was that some of the actual state was implied. For example the DynamoDB `DescribeTable` API only includes a billingMode in its response when the mode is `PAY_PER_REQUEST`. When the mode is `PROVISIONED` (the implied default) it's simply not included in the `DescribeTable` output. The same is true for `streamEnabled` - if it's not enabled there's just no …
=> Accomodate DynamoDB API's implied defaults

examples/iam/policy.yaml, pkg/clients/iam/fake/iampolicy.go, pkg/clients/iam/iampolicy.go, pkg/controller/identity/iampolicy/controller.go, pkg/controller/identity/iampolicy/controller_test.go
When `provider-aws` attempts to observe an iam policy which already exists, it fails with this error:
```
{
"object": {
"kind": "IAMPolicy",
"name": "crossplane-lateinitialize-test",
"uid": "some-uid",
"apiVersion": "identity.aws.crossplane.io/v1alpha1",
"resourceVersion": "49576502"
},
"reason": "CannotCreateExternalResource",
"message": "failed to create the IAM Policy: EntityAlreadyExists: A policy called my-iam-test-policy already exists. Duplicate names are not allowed."
}
```
Since the external name is not set `Observe` skips lookup of the resource and it goes to `Create`.  For other types of resources (ex. iam role) even when the external name is not set crossplane is able to detect and take ownership of the resource.   The reason …
=> observe iampolicy which already exists

pkg/controller/identity/iampolicy/controller.go
CI tests for two individual PRs were OK, but after the merge, CI fails
due to the combined cyclomatic complexity of the function.
Since every PR from master at this point will fail until it is fixed, I
think the lowest risk now is to disable this lint check.
I have:
No code changes.
=> identity.iampolicy: Disable gocyclo after two merges broke CI

pkg/controller/ec2/natgateway/controller.go
fixed 
` failed to create the NATGateway resource: api error InvalidParameter: Tag specification must have at least one tag`
- skip tagSpecification if tags nil - then nat-gateway is created without error message
Fixes https://github.com/crossplane/provider-aws/issues/684
I have:
kubectl apply -f examples/ec2/natgateway-without-tags.yaml 
```
[...]
Spec:
Deletion Policy:  Delete
For Provider:
Allocation Id:  eipalloc-0386dc8235394d295
Allocation Id Ref:
Name:     sample-eip
Region:     us-east-1
Subnet Id:  subnet-0bea8bdb2151f4fbe
Subnet Id Ref:
Name:  sample-subnet1
Provider Config Ref:
Name:  example
Status:
At Provider:
Create Time:  2021-11-24T07:49:32Z
Nat Gateway Addresses:
Allocation Id:         eipalloc-0386dc8235394d295
Network …
```
=> fix(nat): make tagSpecification optional to fits nat-gateway without tags

apis/eks/manualv1alpha1/nodegroup_types.go, package/crds/eks.aws.crossplane.io_nodegroups.yaml
aws shipped: https://aws.amazon.com/de/about-aws/whats-new/2021/10/amazon-eks-nodes-groups-bottlerocket/
https://github.com/aws/containers-roadmap/issues/950
* added in crd information for bottlerocket ami-id
for setting up custom options in bottlerocket nodes we need launch-template support in crossplane https://github.com/crossplane/provider-aws/issues/338
I have:
```
kubectl describe nodegroup.eks.aws.crossplane.io/my-bottlerocket-group
Name:         my-bottlerocket-group
Namespace:    
Labels:       example=true
Annotations:  crossplane.io/external-create-pending: 2021-10-30T15:13:53+02:00
crossplane.io/external-create-succeeded: 2021-10-30T15:13:55+02:00
crossplane.io/external-name: my-bottlerocket-group
API Version: …
```
=> feat(bottlerocket): added informations for eks-bottlerocket-nodegroup

apis/servicediscovery/v1alpha1/custom_types.go, pkg/controller/servicediscovery/commonnamespace/hooks_test.go, pkg/controller/servicediscovery/httpnamespace/setup.go, pkg/controller/servicediscovery/privatednsnamespace/setup.go, pkg/controller/servicediscovery/publicdnsnamespace/setup.go
Fixes #944
This PR moves the storage of the OperationID returned by the AWS Cloud Map [API call](https://docs.aws.amazon.com/cloud-map/latest/api/API_CreatePublicDnsNamespace.html) into an annotation so that it is persisted.  
I have:
I created and deleted the following AWS resources, ensuring the resources were created and deleted in the AWS console. 
- HTTPNamespace
- PrivateDNSNamespace (with VPC)
- PublicDNSNamespace
=> Servicediscovery delete fix

INSTALL.md
Add basic install instruction for the aws provider
I have:
=> add basic install command

pkg/clients/aws.go, pkg/clients/elasticache/elasticache.go
Signed-off-by: Sergen Yalçın <yalcinsergen97@gmail.com>
Fixes: https://github.com/crossplane/provider-aws/issues/909
This PR addresses the constantly update requests problem of replicationgroup. `snapshotRetentionLimit` field set to 0 in the sdk side when it is skipped in MR manifest. During `LateInitialization`, since `nil` and `0` values are considered the same value in the function used, the value `0` is not written to CR and the value in CR remains `nil`. Therefore, the update call is repeated in each reconcile loop. Reference: https://github.com/crossplane/provider-aws/blob/1e29728f989c14d07b5325e3cc4fa8d6d298c51a/pkg/clients/aws.go#L589
I have:
A ReplicationGroup resource was provisioned without setting `snapshotRetentionLimit`. Then I noticed that, this field set to 0 after late …
=> Fixing constantly update requests problem of replicationgroup

apis/glue/v1alpha1/generator-config.yaml, apis/glue/v1alpha1/zz_generated.deepcopy.go, apis/glue/v1alpha1/zz_types.go, apis/lambda/v1alpha1/generator-config.yaml, pkg/controller/glue/crawler/setup.go, pkg/controller/lambda/function/setup.go, pkg/controller/lambda/function/zz_controller.go
Due to https://github.com/aws-controllers-k8s/community/issues/1078 , we cannot use the code generated to set these fields. To unblock code-generator upgrade, we can ignore them so that their getter/setter logic is not generated and handwritten by us in `setup.go` 
I have:
=> Ignore fields in `glue.Crawler` and `lambda.Function` that block code-generator bump

apis/v1beta1/providerconfig_types.go, apis/v1beta1/zz_generated.deepcopy.go, package/crds/aws.crossplane.io_providerconfigs.yaml, pkg/clients/aws.go
added option assumeRoleARN for ProviderConfig #912
1.) In the absence of `assumeRoleARN`, we simply call `config.LoadDefaultConfig(ctx)`, as this will automatically grant us access to the `current` AWS account / configured `WebIdentity` / `Credentials`
2.) `assumeRoleARN` allows us to assume a role via `sts:AssumeRole` via our configured `WebIdentity` / `Credentials`
- default role is assumed by `config.LoadDefaultConfig(ctx)` - `WebIdentity` /  `Credentials`
- `sts:AssumeRole` is done by `stscreds.NewAssumeRoleProvider(assumeRoleARN)`
Fixes #606 
Implemented Parts of: #597 
I have:
for go-sdk-v1 ressources (code-generator)
for go-sdk-v2 ressources (manual implemented ressources)
create providers:
local:
```
apiVersion: …
```
=> assumeRoleARN for ProviderConfig

apis/acmpca/v1beta1/certificateauthoritypermission_types.go, package/crds/acmpca.aws.crossplane.io_certificateauthoritypermissions.yaml
Removes the deprecation warning from certificate authority permission
v1beta1 as it should only exist on v1alpha1.
Fixes https://github.com/crossplane/provider-aws/issues/1030
I have:
Install `provider-aws` and make sure deprecation warning is not surfaced for this resource.
=> Remove inaccurate deprecation warning from v1beta1 type

apis/iam/v1beta1/role_types.go, package/crds/iam.aws.crossplane.io_roles.yaml
`IAMRole` was renamed to `Role` as part of https://github.com/crossplane/provider-aws/pull/996
When you `kubectl get Role` it will default to native kubernetes Role since Role kind exists in multiple apis -
```
kubectl get Role
NAME               CREATED AT
crossplane-admin   2021-03-03T21:51:54Z
crossplane-edit    2021-03-03T21:51:54Z
crossplane-view    2021-03-03T21:51:54Z
```
_Hey but I wanted IAM Roles!!!!!_
```
kubectl api-resources | grep -e " Role$"
roles                              iamrole            iam.aws.crossplane.io/v1beta1                                            false        Role
roles                                                 rbac.authorization.k8s.io/v1                                             true         Role …
```
=> Role - add iamrole shortname

pkg/controller/iam/role/controller.go, pkg/controller/iam/role/controller_test.go
This PR adds the default Crossplane tags ("crossplane-kind", "crossplane-name", "crossplane-providerconfig") to IAMRoles
I have:
- Unit-tests
- Manual testing:
- spin up a new kind cluster (`kind create cluster --name crossplane-aws`)
- install CRDs (`kubectl apply -f package/crds`)
- *create resource scenario*:
- create an iam.Role in the cluster (`kubectl apply -f examples/iam/role.yaml`)
- start `crossplane-aws` controller
- verify that the tags "crossplane-kind", "crossplane-name", "crossplane-providerconfig" are added as expected
- *modify resource scenario*:
- delete tags from the resource: `kubectl patch role.iam.aws.crossplane.io/somerole  --type=json -p='[{"op": "remove", "path":"/spec/forProvider/tags"}]'`
- verify that the tags "crossplane-kind", "crossplane-name", …
=> Add default tags to iam.Role

apis/ec2/v1beta1/vpc_types.go, apis/ec2/v1beta1/zz_generated.deepcopy.go, package/crds/ec2.aws.crossplane.io_vpcs.yaml, pkg/clients/ec2/vpc.go, pkg/controller/ec2/vpc/controller.go
Signed-off-by: vaspahomov <vas2142553@gmail.com>
Add support IpV6CIDRBlock, AmazonProvidedIpv6CIDRBlock options in VPC. Feature allows create ipv6 nets in aws. 
I have:
Manualy tested on my crossplane/provider-aws installation
=> Add Ipv6CIDRBlock support in VPC

pkg/controller/glue/classifier/setup.go, pkg/controller/glue/connection/setup.go, pkg/controller/glue/crawler/setup.go, pkg/controller/glue/database/setup.go, pkg/controller/glue/job/setup.go
as followup for https://github.com/crossplane/provider-aws/pull/992 
cleanup cr.Name to external.name 
Fixes #1018
I have:
setup complete all needed resources:
```
NAME                                          READY   SYNCED   ID                         VPC                     CIDR          AGE
NAME                                                     READY   SYNCED   EXTERNAL-NAME
classifier.glue.aws.crossplane.io/glue-classifier-csv    True    True     glue-classifier-csv
classifier.glue.aws.crossplane.io/glue-classifier-grok   True    True     glue-classifier-grok
classifier.glue.aws.crossplane.io/glue-classifier-json   True    True     glue-classifier-json
classifier.glue.aws.crossplane.io/glue-classifier-xml    True    True …
```
=> feat(glue): followup cleanup cr.name to external.name

pkg/controller/transfer/user/setup.go
fixed: never use cr.Name, the source of truth is always the annotation for transfer/user
Fixes #1051
I have:
```
apiVersion: transfer.aws.crossplane.io/v1alpha1
kind: User
metadata:
annotations:
crossplane.io/external-name: testwithannotation
name: test
spec:
forProvider:
homeDirectory: /crossplane-example-bucket/example
homeDirectoryType: PATH
roleRef:
name: somerole
serverIDRef:
name: example
sshPublicKeyBody: "ssh-rsa xxx"
tags:
- key: myKey
value: myValue
name: example
```
=> fix(name): fix transfer/user &cr.name and use annotation

pkg/controller/kms/key/setup.go
- fixed following problem:
in kms alias:`cannot create Alias in AWS: NotFoundException: Invalid keyId my-key`
in rds dbcluster: ` KMSKeyNotAccessibleFault: The specified KMS key [rg-test-cluster-5bp8r-zzp65] does not exist, is not enabled or you do not have permissions to access it.`
Fixes #902 #1049
I have:
created in one shot:
```
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
name: my-key
spec:
forProvider:
region: us-west-2
pendingWindowInDays: 21 
tags:
- tagKey: app
tagValue: test
name: example
---
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Alias
metadata:
name: my-test
spec:
forProvider:
region: us-west-2
targetKeyIdRef:
name: my-key …
```
=> fix(init): #1049 fix problem that kms-key ref picks wrong metadata.name

apis/s3/v1beta1/bucket_types.go, package/crds/s3.aws.crossplane.io_buckets.yaml
Added 
aws-exec-read
bucket-owner-read
bucket-owner-full-control
log-delivery-write s3 
canned-acls from supported list here https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl
Fixes #
I have:
=> add support for all s3 canned-acls

pkg/controller/ec2/transitgateway/setup.go, pkg/controller/ec2/transitgatewayvpcattachment/setup.go
tags not published for 
- transitgateway
- transitgatewayvpcattachment
Fixes #
I have:
=> fix(tagger): tagger fixed for tgw/tgwvpcattachment

apis/v1beta1/providerconfig_types.go, apis/v1beta1/zz_generated.deepcopy.go, package/crds/aws.crossplane.io_providerconfigs.yaml, pkg/clients/aws.go
Signed-off-by: Hanlin Shi <shihanlin9@gmail.com>
Added support for external ID when assuming aws role.
Fixes #1012
I have:
Manually created IAM role that can be assumed when passing an external ID, and create a provider config containing that IAM info. Created an S3 bucket using that provider config successfully.
=> Add support for external ID when assume role

pkg/controller/eks/addon/setup.go, pkg/controller/eks/addon/setup_test.go
Fixes #1067 
This removes the `ListTagsForResource` call from the `Addon` controller in `isUpToDate` and replaces it with `DescribeAddon` in `postUpdate`.
Unfortunately AWS does not include a `Tag` field in `UpdateAddon` so the `postUpdate` method cannot be further simplified.
I have:
Manually
=> fix(eks-addon): Replace ListTagsForResource with DescribeAddon to save one API call

apis/ec2/manualv1alpha1/common.go, examples/ec2/instance.yaml, package/crds/ec2.aws.crossplane.io_instances.yaml
Signed-off-by: Mario Bris <bris.mario@gmail.com>
I've changed some of EC2 CRD fields from mandatory to optional. 
Fixes #1088
I have:
I've tested with new instance which extends [examples/ec2/instance.yaml](https://github.com/crossplane/provider-aws/blob/master/examples/ec2/instance.yaml)  manifest with EBS section
```
spec:
forProvider:
...
blockDeviceMappings:
- deviceName: /dev/sdx
ebs:
volumeSize: 100
...
```
delete the instnace also delete the volume.
=> fix(ec2-instance): make some blockDevicMapping fields in CRD optional

pkg/controller/rds/dbinstance/setup.go
copied the strategy used in dbcloud of reading the endpoint info
from the dbinstance status rather than the aws api out result
in order to get the endpoint info. A manual test confirms that
this results in the secret containing the host
Fixes #1090 
I have:
- [x ] Read and followed Crossplane's [contribution process].
- [ x] Run `make reviewable test` to ensure this PR is ready for review.
Manually  ran the controller locally and created a new db instance and the endpoint host was then contained in the output secret which it previously wasn't.
=> read endpoint info from dbinstance status rather than aws out values

AUTHENTICATION.md, examples/providerconfig/assumeRoleARN-injected.yaml, examples/providerconfig/assumeRoleARN.yaml
added documentation for assumeRoleARN and externalID with provider-aws as followup for https://github.com/crossplane/provider-aws/pull/912
Fixes #1065 
I have:
=> doc(assumeRoleARN): #1065 added documentation for assumeRoleARN

pkg/controller/secretsmanager/secret/setup.go
Always return `false, nil` in `isUpToDate` if resource is marked as deleted.
Fixes #1094 
I have:
Manually
=> fix(secretsmanager): Ignore isUpToDate if resource was deleted

apis/ec2/manualv1alpha1/common.go, apis/ec2/manualv1alpha1/instances_types.go, examples/ec2/instance_spot.yaml, package/crds/ec2.aws.crossplane.io_instances.yaml
changed SpotMarketOptions to fits API - and added example 
Fixes #1079
I have:
```
k get instances
NAME                   READY   SYNCED   ID                    STATE     AGE
sample-instance        True    True     i-08e2b57a6c7873a1e   running   5m35s
sample-instance-spot   True    True     i-00001a3bbbb156e28   running   10m
```
=> fix(ec2-instance): changed SpotMarketOptions for Spot Instances

pkg/controller/transfer/user/setup.go
set correct `managed.WithInitializers` missed a local commit in #1053 sorry
Fixes #1102
I have:
```
kubectl get users.transfer
NAME      READY   SYNCED   EXTERNAL-NAME
example   True    True     example
```
=> fix(transfer/user): fix WithInitializers and removed postCreate

Makefile, apis/docdb/v1alpha1/zz_db_cluster.go, apis/docdb/v1alpha1/zz_db_cluster_parameter_group.go, apis/docdb/v1alpha1/zz_db_instance.go, apis/docdb/v1alpha1/zz_db_subnet_group.go, apis/docdb/v1alpha1/zz_types.go, pkg/controller/docdb/dbcluster/setup_test.go, pkg/controller/docdb/dbcluster/zz_controller.go, pkg/controller/docdb/dbclusterparametergroup/zz_controller.go, pkg/controller/docdb/dbinstance/setup_test.go, pkg/controller/docdb/dbinstance/zz_controller.go, pkg/controller/docdb/dbsubnetgroup/zz_controller.go
This adds `docdb` to the list of generated services.
I have:
Unit tests
=> Add docdb to generated services

CODE_GENERATION.md, Makefile
Signed-off-by: Daniel Werdermann <daniel.werdermann@gmail.com>
The variable in the Makefile is now generated from the paths of the generatec-config.yaml files. So no more editingof the Makefile and no merge conflicts.
Fixes #861
Fixes #862
I have:
`make reviewable` works without changes.
=> chore: dynamically generate GENERATED_SERVICES var

Makefile
Signed-off-by: Daniel Werdermann <daniel.werdermann@gmail.com>
Adjust the shell find command, because on MacOS the output differs a little bit from linux. It works on two machines now. (Thanks @haarchri )
I have:
It worked perfect on my machine. A typically  environment. Windows 11 with wsl and debian 10  ;-)
=> fix(Makefile) adjust command 'find' to be zshell compatible

pkg/clients/eks/nodegroup.go, pkg/clients/eks/nodegroup_test.go
fixed error both or either addOrUpdateLabels or removeLabels must not be empty which leads in Ready false for NodeGroup
also our friends from terraform did it this way https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/eks/node_group.go#L806 and add nil if nothing changed for addOrUpdateLabels / removeLables ;)
Fixes #975
I have:
NodeGroup Scaling Config is updated with this fix in our environment
=> fix(lables): eks-nodegroup - both or either addOrUpdateLabels or removeLabels must not be empty

apis/database/v1beta1/rdsinstance_types.go, apis/database/v1beta1/zz_generated.deepcopy.go, package/crds/database.aws.crossplane.io_rdsinstances.yaml, pkg/clients/rds/rds.go, pkg/controller/database/rdsinstance.go, pkg/controller/database/rdsinstance_test.go
Add storage autoscaling parameter MaxAllocatedStorage.
This parameter defines the upper limit to which Amazon RDS can automatically
scale the storage of the DB instance.
For more information about this setting, including limitations that apply
to it, see Managing capacity automatically with Amazon RDS storage autoscaling
(https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIOPS.StorageTypes.html#USER_PIOPS.Autoscaling)
in the Amazon RDS User Guide.
Make rds.CreatePatch exclude AllocatedStorage if autoscaling is enabled,
and the requested AllocatedStorage is lower than was is currently
allocated.
This allows a user to manually scale *up* storage even if autoscaling is
enabled, and prevents crossplane from attempting to scale *down* if
AWS has performed autoscaling.
One problem is …
=> rds.rdsinstance: Add storage autoscaling (MaxAllocatedStorage)

apis/secretsmanager/v1alpha1/custom_types.go, pkg/controller/secretsmanager/secret/setup.go
Fixes #668
The controller now creates a K8s with the value from AWS if it does not already exist.
I have:
Manually
=> Secretsmanager: Implement LateInitialize of a K8s secret when AWS secret already exists

package/crds/secretsmanager.aws.crossplane.io_secrets.yaml, pkg/controller/secretsmanager/secret/setup.go
Follow-up for https://github.com/crossplane/provider-aws/pull/669#pullrequestreview-876202252
cc @MisterMX 
I have:
Manually tested by creating a secret, deleting it via orphan policy and importing it to see if it creates the input secret. I tested the normal flow of creation as well to make sure we don't late-init in all cases.
=> secretsmanager.secret: make late init work only if the input secret does not exist

pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticache_test.go, pkg/clients/elasticache/fake/fake.go, pkg/controller/cache/managed.go, pkg/controller/cache/managed_test.go
Scale up and down replication groups as requested by the user.
On scale down, the AWS API requires us to pick the nodes to remove. I have not considered what the best option is, I picked the first node in the list.
Co-authored-by: sb1-oscar <sb1-oscar@users.noreply.github.com>
Fixes #531
I have:
Tested changing the CR to scale up/down. I will have to retest since this PR has been rebased and it's a while since I wrote it.
=> elasticache: Scale replicationgroup shards

pkg/controller/s3/bucket/websiteConfig.go
When no routing rules are defined for a website configuration, we must
avoid sending an empty XML attribute as AWS refuses this as part of the
schema validation:
<WebsiteConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><ErrorDocument><Key>techdocs-docs/index.html</Key></ErrorDocument><IndexDocument><Suffix>index.html</Suffix></IndexDocument><RoutingRules></RoutingRules></WebsiteConfiguration>
cannot create or update: api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
for the input:
websiteConfiguration:
errorDocument:
key: 'techdocs-docs/index.html'
indexDocument:
suffix: 'index.html'
Fixes bug reported on slack. https://github.com/crossplane/provider-aws/issues/1155
I have:
Created bucket, verified in the console …
=> s3: Empty routing rules refused by AWS

pkg/controller/acmpca/certificateauthority/controller.go, pkg/controller/acmpca/certificateauthority/controller_test.go
Signed-off-by: Cecilia Bernardi <cbernardi@expediagroup.com>
This PR adds the default tags to `acmpca.CertificateAuthority` resource ("crossplane-kind", "crossplane-name", "crossplane-providerconfig") 
Fixes #1143
I have:
- Unit Tests
- Manual Test on a kind cluster:
- spin up a new kind cluster (kind create cluster --name crossplane-aws)
- install CRDs (kubectl apply -f package/crds)
- create resource scenario:
- create an acmpca.CertificateAuthority in the cluster (kubectl apply -f examples/acmpca/certificateauthority.yaml)
- start crossplane-aws controller
- verify that the tags "crossplane-kind", "crossplane-name", "crossplane-providerconfig" are added as expected
- modify resource scenario:
- delete tags from the resource: kubectl patch …
=> Added default tags to CertificateAuthority

apis/s3/v1beta1/notificationConfiguration_types.go, apis/s3/v1beta1/zz_generated.deepcopy.go, apis/s3/v1beta1/zz_generated.resolvers.go, package/crds/s3.aws.crossplane.io_buckets.yaml, pkg/controller/s3/bucket/notificationConfig.go, pkg/controller/s3/bucket/notificationConfig_test.go
This changes the referencer implementation for `spec.forProvider.noficationConfiguration.queueConfigurations[].queueArn` for `Bucket` so it will extract the ARN from the `Queue` resource instead of the default external name annotation.
Fixes #1160 
It will also make the field optional, because it can be filled using referencers.
Additionally, I updated the put bucket notification configuration error message to give a
hint about missing IAM credentials. (Because the AWS error message is incomplete and might be misleading).
I have:
Manually using the following YAML:
```yaml
---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
name: repl-dest
annotations:
crossplane.io/external-name: crossplane-example-repl-dest-123455
spec:
forProvider:
acl: private …
```
=> fix(s3): Extract QueueARN instead of external name

apis/iam/v1beta1/openidconnectprovider_types.go, apis/iam/v1beta1/zz_generated.deepcopy.go, package/crds/iam.aws.crossplane.io_openidconnectproviders.yaml, pkg/clients/iam/fake/openidconnectprovider.go, pkg/clients/iam/openidconnectprovider.go, pkg/clients/iam/openidconnectprovider_test.go, pkg/clients/iam/role.go, pkg/clients/iam/role_test.go, pkg/clients/iam/tags.go, pkg/clients/iam/tags_test.go, pkg/controller/iam/openidconnectprovider/controller.go, pkg/controller/iam/openidconnectprovider/controller_test.go
Added tags management to OpenIDConnectProvider.
Fixes #
I have:
This PR was tested by: 
- Unit Tests
- The following manual testing was performed in a local kind cluster configured with an AWS account:
- OIDCProvider creation: the provider was correctly created and  the default tags were added
- OICDProvider update: 
- New tags were added to the CR and they were successfully created in the external AWS resource
- Tags values were modified in the CR, and they were successfully modified in the external AWS resource
- Tags were removed from the CR and they were successfully removed from the external AWS resource
- The default tags were removed from the CR, and they were restored in the CR and NOT removed from the external AWS resource
=> Add tags management to OpenIDConnectProvider (iam)

apis/eks/v1beta1/types.go, package/crds/eks.aws.crossplane.io_clusters.yaml, pkg/clients/eks/eks.go, pkg/clients/eks/eks_test.go
Fixes #955
I have:
Added unit test for the new field introduced.
=> Expose eks cluster certificate authority data in status

apis/ec2/manualv1alpha1/common.go, apis/ec2/manualv1alpha1/zz_generated.deepcopy.go, apis/ec2/manualv1alpha1/zz_generated.resolvers.go, package/crds/ec2.aws.crossplane.io_instances.yaml
feat(ec2): add kmsKeyID Ref & Selector in ec2-instance ebs dbm
added kmsKeyID Ref & Selector for kmsKeyID
Fixes #
I have:
created ec2 instance with blockDeviceMappings-ebs
=> feat(ec2): add kmsKeyID Ref & Selector in ec2-instance ebs dbm

apis/s3/v1beta1/serverSideEncryption_types.go, package/crds/s3.aws.crossplane.io_buckets.yaml, pkg/controller/s3/bucket/sseConfig.go, pkg/controller/s3/bucket/sseConfig_test.go
implemented bucketKeyEnabled in sseConfig
Fixes https://github.com/crossplane/provider-aws/issues/1154
I have:
t.b.d
=> feat(s3): bucketKeyEnabled implemented

examples/rds/db-instance.yaml, pkg/controller/rds/dbinstance/setup.go
DBInstance is in the example is never "up to date"
```
2022/03/09 22:26:23   &v1alpha1.DBInstanceParameters{
... // 4 ignored and 40 identical fields
TDECredentialPassword: nil,
Timezone:              nil,
CustomDBInstanceParameters: v1alpha1.CustomDBInstanceParameters{
... // 14 ignored and 2 identical fields
- 		ApplyImmediately: nil,
+ 		ApplyImmediately: &true,
},
}
2022-03-09T22:26:24.297+0100	DEBUG	provider-aws	Successfully requested update of external resource
```
ApplyImmediately is not an observable field, but an option for the modify API call,
so we should not compare it.
With the fix:
```
2022-03-09T22:31:55.197+0100	DEBUG	provider-aws	External resource is up to date	{"controller": "managed/dbinstance.rds.aws.crossplane.io", "request": "/example-dbinstance", "uid": …
```
=> rds.DBInstance - fix "up to date" when using ApplyImmediately

pkg/controller/rds/dbcluster/setup.go, pkg/controller/rds/dbinstance/setup.go
- change connectionDetails from postCreate to postObserve - because connectionDetails not published from time to time
- fix issue in db-instance if instance is a cluster-member
```
Warning  CannotUpdateExternalResource  5m14s (x22 over 19m)  managed/dbinstance.rds.aws.crossplane.io  cannot update DBInstance in AWS: InvalidParameterCombination: The specified DB instance is a member of a DB cluster. Storage grows based on usage. You don't need to set it explicitly.
status code: 400, request id:
```
Fixes #1169 #776
I have:
rollout rds-cluster & rds-instance and checked the secrets
```
NAME                                                           READY   SYNCED   EXTERNAL-NAME
dbcluster.rds.aws.crossplane.io/example-aurora-mysql-cluster …
```
=> fix rds connection secret move to observe and fix issue in dbinstance 

pkg/clients/iam/fake/policy.go, pkg/controller/iam/policy/controller.go, pkg/controller/iam/policy/controller_test.go
Signed-off-by: Cecilia Bernardi <cbernardi@expediagroup.com>
Fixes #1206
I have:
- Unit Tests
- Manual tests on a kind cluster configured with an AWS account:
- Create resource scenario: a new iam.policy crossplane resource was created and the default tags were added in the kubernetes cluster; the policy was successfully created in the configured AWS account with the default tags
- Add custom tags scenario: custom tags were added to the crossplane resources, and the AWS policy was successfully tagged with the new tags
- Modify custom tags scenario: custom tags were modified on the kubernetes resource, and the modification was successfully reconciled with the AWS resource (could observe tags values being modified)
- Remove custom tags scenario: custom tags were removed from the kubernetes …
=> add default Crossplane tags to iam.Policy

Makefile, cluster/local/integration_tests.sh
Updates CI to extract package contents into a gzipped file compatible with Crossplane's package cache format.
I have:
`make build` and `make e2e` and verified success
```
>>>>>>> --- INTEGRATION TESTS ---
>>>>>>> installing provider-aws into "crossplane-system" namespace
provider.pkg.crossplane.io/provider-aws created
>>>>>>> check kind node cache dir contents
total 408
drwxrwxr-x 2 1000 1000   4096 Mar 30 02:48 .
drwxr-xr-x 1 root root   4096 Mar 30 02:48 ..
-rw-r--r-- 1 1000 1000 406797 Mar 30 02:47 provider-aws.gz
>>>>>>> waiting for provider to be installed
provider.pkg.crossplane.io/provider-aws condition met
>>>>>>> uninstalling provider-aws
provider.pkg.crossplane.io "provider-aws" deleted
waiting for provider to be deleted for another 3 seconds
waiting for provider to be deleted …
```
=> Update CI to work with Crossplane v1.7.0

pkg/clients/aws.go, pkg/version/version.go
Signed-off-by: Clare Liguori <liguori@amazon.com>
Sets the user agent to crossplane-provider-aws with the provider version number
Fixes #1241
I have:
I ran the provider locally in KinD and created an ECR repo through it using `examples/ecr/repository`.
In CloudTrail, I can now see the CreateRepository call with:
```
"userAgent": "aws-sdk-go-v2/1.11.2 os/linux lang/go/1.17 md/GOOS/linux md/GOARCH/amd64 api/ecr/1.9.0 crossplane-provider-aws/v0.26.0-rc.0.18.ge6ac32da.dirty",
```
=> Set Crossplane user agent on AWS clients

.github/workflows/ci.yml
Otherwise it uses go1.18 which doesn't work for us yet. Here is a failed linter job https://github.com/crossplane/provider-aws/runs/5859214191?check_suite_focus=true
I have:
Through GH PR.
=> linter: make sure it uses the version given in GH action file

pkg/clients/resourcerecordset/resourcerecordset.go, pkg/controller/route53/resourcerecordset/controller.go
Signed-off-by: Bob Haddleton <bob.haddleton@nokia.com>
Updated the ResourceRecordSet controller to handle the case where the HostedZone has been deleted before the ResourceRecordSet, to prevent the ResourceRecordSet from being permanently stuck.
If the HostedZone does not exist then the ResourceRecordSet cannot exist and so this case can be handled as equivalent to a "NotFound".
Fixes #1251 
I have:
Tested in a local Kind environment.  Reproduced the problem locally, then applied the changes and verified that the ResourceRecordSet gets deleted when the HostedZone has already been deleted.
=> Handle NoSuchHostedZone errors on ResourceRecordSet delete

apis/cloudfront/generator-config.yaml, apis/cloudfront/v1alpha1/zz_generated.deepcopy.go, apis/cloudfront/v1alpha1/zz_types.go, package/crds/cloudfront.aws.crossplane.io_distributions.yaml, pkg/controller/cloudfront/distribution/lateinit.go, pkg/controller/cloudfront/distribution/setup.go, pkg/controller/cloudfront/distribution/zz_controller.go, pkg/controller/cloudfront/distribution/zz_conversions.go
Signed-off-by: ezgidemirel <ezgidemirel91@gmail.com>
This change lateInitialize the "CallerReference" value for import scenarios. 
Fixes #1260 
I have:
- Created a CF distribution resource with `example.yaml`
- Changed `spec.deletionPolicy` to `Orphan` and deleted the managed resource
- Imported the same resource with following manifest 
```
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
annotations:
crossplane.io/external-name: <external-name>
name: ezgi
spec:
forProvider:
distributionConfig: {}
```
- Updated `spec.forProvider.distributionConfig.comment`
- Applied the same steps with `callerReference` field set 
=> Store CallerReference value for import scenarios

pkg/controller/lambda/permission/policy.go, pkg/controller/lambda/permission/policy_test.go
On reconciliation the AWS API returns the resulting policy document for the lambda. This includes the Principal and it can be in two forms: A plain string or an object with a `Service` key. I.e.:
```json
"Principal": "foo"
```
vs.
```json
"Prinicpal": {
"Service": "foo"
}
```
The current code breaks on the first one. This PR fixes that.
I have:
Unit tests are included, code changes are very local.
=> fix(permission): Fix dealing with Pricipal being just a string

pkg/controller/ec2/securitygroup/controller.go, pkg/controller/ec2/securitygroup/controller_test.go
This allows transferring ownership of an existing SecurityGroup.
Signed-off-by: Otto Nordander <otto.nordander@resurs.se>
Check if a SecurityGroup exists during `controller.Observe` to allow transferring ownership of SGs.
Fixes #1175 
I have:
Tested with local Kind cluster.
```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
name: test-security-group
spec:
deletionPolicy: Orphan
name: local
forProvider:
region: eu-central-1
groupName: test-security-group
description: Test security group
vpcId: <vpc-id>
```
```bash
kubectl apply -f securitygroup.yaml
kubectl get securitygroup test-security-group # ID: sg-<ID>
kubectl delete -f securitygroup.yaml
kubectl get securitygroup # No resources found
kubectl apply -f securitygroup.yaml
kubectl get …
```
=> ec2.SecurityGroup: Observe existing SecurityGroup

pkg/clients/ec2/routetable.go, pkg/clients/ec2/routetable_test.go, pkg/controller/ec2/routetable/controller.go, pkg/controller/ec2/routetable/controller_test.go
This is just a rebase + conflict resolution of PR https://github.com/crossplane/provider-aws/pull/893 which appears to be abandoned. Credit for this fix should go to @vaspahomov.
Signed-off-by: vaspahomov <vas2142553@gmail.com>
Signed-off-by: Jesse Suen <jessesuen@gmail.com>
Fixes https://github.com/crossplane/provider-aws/issues/795
I have:
I was encountering the panic in https://github.com/crossplane/provider-aws/issues/795 when creating route tables in a VPC with ipv6 enabled. The panic causes the provider-aws controller to crashloop and will not recover. With this fix, the panic no longer happens.
=> fix(routetable): fix panic on sorting both v4 and v6 routes

apis/cache/v1beta1/replication_group_types.go, apis/cache/v1beta1/zz_generated.deepcopy.go, package/crds/cache.aws.crossplane.io_replicationgroups.yaml, pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticache_test.go, pkg/clients/elasticache/fake/fake.go, pkg/controller/cache/managed.go, pkg/controller/cache/managed_test.go
This PR adds functionality to update multiAZ and tags for ElastiCache Replication groups. 
Fixes #914
I have:
- Created a replication group and changed Tags and MultiAZenabled.
```yaml
apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroup
metadata:
name: redis-replication-group
spec:
forProvider:
replicationGroupDescription: "A redis replication group"
applyModificationsImmediately: true
engine: "redis"
engineVersion: "5.0.6"
port: 6379
cacheSubnetGroupName: borrelli-cache-test
#cacheSubnetGroupName: default
numCacheClusters: 2
cacheParameterGroupName: default.redis5.0
cacheNodeType: cache.t3.medium
securityGroupIds:
- sg-xxxxxyyyyy 
automaticFailoverEnabled: true
multiAZEnabled: false
tags:
- key: Name
value: redis-replication-group
#- key: VS
- key: …
```
=> Replication group fixes: multiAz and Tag update support

pkg/controller/ec2/route/setup.go
Fixes #1272
I have:
```
kubectl get managed
Warning: Please use v1beta1 version of SNS group.
NAME                                                           READY   SYNCED   ID                      VPC                     AGE
internetgateway.ec2.aws.crossplane.io/sample-internetgateway   True    True     igw-0b2e5ca49cf012bae   vpc-0af0af423f4605041   21m
NAME                                          READY   SYNCED   ID                         VPC                     CIDR          AGE
subnet.ec2.aws.crossplane.io/sample-subnet1   True    True     subnet-04a6eac5948aba708   vpc-0af0af423f4605041   10.0.1.0/24   28m
subnet.ec2.aws.crossplane.io/sample-subnet2   True    True     subnet-06180c0fdbc20dcc4   vpc-0af0af423f4605041   10.0.2.0/24 …
```
=> bugfix(panic): fix panic route resource in CIDRBlocksEqual

pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticache_test.go, pkg/clients/elasticache/fake/fake.go, pkg/controller/cache/managed.go, pkg/controller/cache/managed_test.go
This PR is a follow up of https://github.com/crossplane/provider-aws/pull/1277 and adds the ability to update the number of cache clusters in an Elasticache Replication group. 
I have:
Modified the `numCacheClusters` field of the following Managed resource and observed changes in the AWS UI:
```yaml
apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroup
metadata:
name: redis-replication-group
spec:
forProvider:
replicationGroupDescription: "A redis replication group"
applyModificationsImmediately: true
engine: "redis"
engineVersion: "5.0.6"
port: 6379
cacheSubnetGroupName: borrelli-cache-test
numCacheClusters: 2
cacheParameterGroupName: default.redis5.0
cacheNodeType: cache.t3.medium
securityGroupIds:
- sg-123456
automaticFailoverEnabled: true …
```
=> feat (CloudFront): Add support to update Elasticache ReplicationGroup number of cache clusters

pkg/controller/rds/dbcluster/setup.go
The connection details secret is missing the port.
Some other Crossplane providers expect the port to be in the secret, like, for example, the Provider SQL.
This relates to: https://github.com/crossplane-contrib/provider-sql/issues/76
Fixes #1296
I have:
I had some issues running the `make` command:
- initially, the `make` commands were mangling my working copy and I had to `export ROOT_DIR=$(pwd)` to get it to work properly.
- running `make reviewable` resulted in an error:
```
Error: open /Users/luisdavim/.cache/ack-generate/src/aws-sdk-go/models/apis/servicecatalog/2015-12-10/api-2.json: too many open files
```
I tried running `make -j1 reviewable` and it still failed.
- Running `make test` worked.
- When the `make` execution stopped with the error mentioned above, `goimports` had …
=> fix(rds): include the port number in the connection details

apis/ec2/v1beta1/securitygroup_types.go, apis/ec2/v1beta1/zz_generated.resolvers.go
Security group resolvers was missing during a refactor when changing other parts of the ec2 package. I think we should consider backporting this change.
Fixes #1312
I have:
Tested with ingress rule by @petteja 
=> ec2.securitygroup: Fix missing resolvers by using code gen

apis/sns/v1beta1/topic_types.go, apis/sns/v1beta1/zz_generated.deepcopy.go, package/crds/sns.aws.crossplane.io_topics.yaml, pkg/clients/sns/topic.go, pkg/clients/sns/topic_test.go
Adds `FifoTopic` property to SNS-Topic.
Partly fixes https://github.com/crossplane/provider-aws/issues/1139
I have:
Code has been tested on a mid-sized company-scale dev-cluster. 
e2e-tests were fine. I added small unit-test.
=> Introduce fifoTopic option for sns

pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticache_test.go
Relates to https://github.com/crossplane/provider-aws/issues/1023
We discovered a state where `provider-aws` was repeatedly modifying the elasticache cluster without it becoming available, as described in #1023. Tracked the issue down to the use of a PreferredMaintenanceWindow argument that included capitalized day names: `Fri:04:20-Fri:16:20`. 
This is invalid according to [aws docs](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateReplicationGroup.html), as day names are supposed to be lowercased, however the AWS API accepts uppercased day names, and normalizes them behind the scenes to lowercased. This ends up breaking the `cacheClusterNeedsUpdate` check, which tests for exact equality between the declared maintenance window in the resource spec (which will …
=> fix(elasticache) normalize preferred maintenance window

AUTHENTICATION.md
I follow the direction in the documentation and hit the following error:
```
Not authorized to perform sts:AssumeRoleWithWebIdentity
```
I noticed we are creating an OIDC provider in the target account but we don't use it. Switching to `TARGET_AWS_ACCOUNT_ID` solved the permission issue and I was able to create resources.
I have:
- [N/A] Run `make reviewable test` to ensure this PR is ready for review.
N/A
=> [Documentation] update trust relationship in assumeRoleWithWebIdentity

pkg/controller/cloudwatchlogs/loggroup/setup.go
DescribeLogGroup returns maximum 50 loggroups pr default, which can lead to cases where loggroup exists but doesn't get returned and Crossplane will then attempt to create the resource, rather than taking ownership of the loggroup.
This adds the external name as LogGroupNamePrefix to the Describe call which will return loggroups that has external name as prefix.
Fixes #1188 
I have:
This has been tested out of cluster and also in our test- and production environments.
=> fix(LogGroup): Fix observe in case of more than 50 loggroups

pkg/clients/iam/fake/user.go, pkg/clients/iam/user.go, pkg/controller/iam/user/controller.go, pkg/controller/iam/user/controller_test.go
Signed-off-by: Cecilia Bernardi <cbernardi@expediagroup.com>
Fixes #1232
Fixes #1233
I have:
- Unit Tests
- Manual Tests (in a kind cluster configured with an AWS account)
- Creation scenario: a `iam.User` was created with a "k1":"v1" tag. All the default tags were added and Crossplane created the User successfully, reconciling all the 4 tags (3 default tags + 1 custom tag)
- Update scenario: the same `iam.User` created above was patched to:
- change the custom tag from "k1":"v1" to "k1":"v2" (the value change was correctly applied to the AWS resource)
- change the custom tag from "k1":"v1" to "k2":"v1" (a new tag was added to the AWS resource, and the previous one was removed)
- add a new "k3":"v3" tag. The AWS resource was tagged with the new tag
- remove the tag with key "k2". The AWS …
=> Added default tags to iam.User

pkg/clients/eks/eks.go, pkg/clients/eks/eks_test.go, pkg/controller/eks/cluster.go
Signed-off-by: Adrien Zieba <adrien.zieba@splashthat.com>
AWS CLI prevents us from updating the VPC config and the Logging in the same call. This PR is splitting the method `GenerateUpdateClusterConfigInput` in 2 distinct ones: `GenerateUpdateClusterConfigInputForLogging`, `GenerateUpdateClusterConfigInputForVPC`
Fixes #1014
I have:
Create a cluster with Logging enabled
```
...
forProvider:
logging:
clusterLogging:
- enabled: true
types:
- api
- audit
- authenticator
- controllerManager
- scheduler
...
```
Then change the configuration to disable one of the type
```
...
forProvider:
logging:
clusterLogging:
- enabled: true
types:
- api
- audit
- authenticator
- controllerManager
- scheduler
- enabled: false
types:
- controllerManager
...
```
*NOTE*: I noticed that the types needs to be in …
=> split GenerateUpdateClusterConfigInput in 2 methods: Logging and VPC

pkg/clients/aws.go, pkg/clients/aws_test.go
Although changes introduced in https://github.com/crossplane-contrib/provider-aws/pull/1329 allow for IAM and Route53 resources to be provisioned in non `aws` partitions, it requires specific endpoint configurations in `ProviderConfig` to do so. 
This PR aims to allow for non `aws` partition users who run this provider in EKS with IRSA to provision global resources without endpoint configuration. 
Some background:
1. Cross partition assume role is not possible. e.g. assume role from IAM principals in `aws` partition to `aws-cn` is not possible.
2. If IRSA is used, EKS injects token and some [AWS specific environment variables into pod](https://github.com/aws/amazon-eks-pod-identity-webhook#eks-walkthrough)
Given these, I think it makes sense to let AWS SDK detect region and correct …
=> let aws go sdk detect partition and region in irsa

pkg/clients/resourcerecordset/resourcerecordset.go, pkg/controller/route53/resourcerecordset/controller_test.go
Signed-off-by: Manabu Mccloskey <manabu.mccloskey@gmail.com>
Route53 does not return the `*` character if it sees it as a wildcard. e.g. For a record `*.crossplane.io`, the string for its name returned by Route53 API is `\052.crossplane.io`. 
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html?shortFooter=true#domain-name-format-asterisk
Fixes #1115
I have:
Ran this code against my private Route53 zone with the following yaml:
```yaml
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
name: 'test-dns'
annotations:
crossplane.io/external-name: "*.crossplane.manabu.com"
spec:
forProvider:
type: A
ttl: 300
zoneId: <ZONEID>
resourceRecords:
- value: 1.2.3.4
name: aws-provider-config
```
It used to never reach the …
=> fix route53 wildcard handling

pkg/clients/s3/bucketpolicy.go
Signed-off-by: Bob Haddleton <bob.haddleton@nokia.com>
Refactor the handling of the BucketNotFound error for BucketPolicy query.  The previous code was not recognizing the error when it happened.
Fixes #1353 
I have:
Code was run in our local environment and cleaned up several dozen stuck BucketPolicy objects that were in this condition.
=> refactor bucketnotfound error for bucketpolicy

examples/cache/replicationgroup.yaml, pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticache_test.go
Starting with the 6.x version of Redis clusters, Elasticache now only uses the first 2 digits or a wildcard to specify the engine version. (i.e., 6.2, or 6.x to generate a 6.2.6 cluster). See [redis-version-6.0](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/supported-engine-versions.html#redis-version-6.0).  
This PR updates the Engineversion check to match the API behavior. 
I have:
Created a replication group using the examples/cache/replicationGroup.yaml
with versions:
- 6.2
- 6.x
And ensured the cluster was created and did not enter an UpdateRequired loop. 
=> Update handling of Elasticache versions

pkg/controller/kafka/cluster/setup.go
provider-aws would panic if the CR did not contain the optional
configurationInfo field. Add nil check.
I have:
@petteja / @niralmehtasb1 did you test this or do you always want a config object from now on?
=> kafka cluster: configurationInfo is optional

pkg/clients/iam/fake/openidconnectprovider.go, pkg/clients/iam/openidconnectprovider.go, pkg/controller/iam/openidconnectprovider/controller.go, pkg/controller/iam/openidconnectprovider/controller_test.go
Allow Crossplane to transfer ownership of previously
created OpenIDConnectProvider. The provider instance is derived from
the Crossplane tags.
Signed-off-by: Otto Nordander <otto.nordander@resurs.se>
Check for existing OpenIDConnectProviders with the same `crossplane-name` tag during `Observe` to allow transferring ownership of the provider.
Fixes #1280 
I have:
Added unittests and manual testing using:
```yaml
apiVersion: iam.aws.crossplane.io/v1beta1
kind: OpenIDConnectProvider
metadata:
name: test-oidc-provider
spec:
deletionPolicy: Orphan
name: example
forProvider:
thumbprintList:
- 9e99a48a9960b14926bb7f3b02e22da2b0ab7280
url: https://mytesturl.provider.aws.crossplane
```
```bash
kubectl apply -f oidc-provider.yaml
kubectl get …
```
=> Observe existing OpenIDConnectProvider

pkg/clients/aws.go
Signed-off-by: Bob Haddleton <bob.haddleton@nokia.com>
Add Route 53 to the IAM exception case in service discovery so that no region is used in the URL, and remove the space from the service name.
Fixes #1408 
I have:
Tested the changes in a local cluster and verified that the ResourceRecordSet resource can be Observed and reconciled when dynamic endpoint discovery is enabled in the ProviderConfig,
=> Handle Route 53 service discovery - Fixes #1408

pkg/clients/rds/rds.go, pkg/controller/database/rdsinstance_test.go
We already have special case handling for BackupRetentionPeriod when AWS
Backup is enabled. Add similar handling for PreferredBackupWindow. This
attribute is ready only when AWS Backup is enabled.
We run into issues like this because of late initialization which sets
fields into the spec which in some cases are more like status fields.
Related: #1356
I have:
* unit test
* ran against real cluster and checked that the error is gone
=> rdsinstance: AWS Backup might also manage PreferredBackupWindow

pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticache_test.go, pkg/controller/cache/managed.go
NumCacheClusters should not be set in many cases, so we should not
assume nil = 0.
Also update the error message to quickly be able to find which API call fails, it reused the error from another API call and cloud trail was not helpful in this case either (no log entry).
cc @stevendborrelli 
Fixes #1384
Related #1294
I have:
Unit tests updated. Ran on real installation and checked that unsynced cluster is now synced.
=> replicationgroup: Allow unmanaged NumCacheClusters

pkg/clients/sns/topic.go
I did miss something on: https://github.com/crossplane-contrib/provider-aws/pull/1291 
There is a wrong check which results in the `fifoTopic`-property never stored in by k8s-api.
Fixes #
I have:
- [/] Read and followed Crossplane's [contribution process].
- [/] Run `make reviewable test` to ensure this PR is ready for review.
=> [FIX] `fifoTopic`-property doesn't get properly stored in k8s

apis/rds/v1alpha1/custom_types.go, package/crds/rds.aws.crossplane.io_dbclusters.yaml, pkg/controller/rds/dbcluster/setup.go
When a secret with the master password is not given, the resource will autogenerate an initial password
Fixes #667
Replaces #671 which seems to be stuck
I have:
Compiled locally and tested in a sandbox cluster launching a few Aurora databases
=> DBCluster auto generates password

pkg/controller/rds/dbcluster/setup.go
Updated the handling of DBCluster updates, now several properties are taken into account when checking if an update is needed:
* PreferredMaintenanceWindow
* PreferredBackupWindow
* BacktrackWindow
* BackupRetention
* CopyTagsToSnapshot
* DeletionProtection
* EngineVersion
* Port
* ScalingConfiguration
* Tags
Deletion of a Cluster is updated to not send FinalDBSnapshotIdentifier and SkipFinalSnapshot at the same time: if SkipFinalSnapshot is set to true, FinalDBSnapshotIdentifier is skipped
Fixes #1423
Fixes #1421 
I have:
=> Updated Handling of DBCluster Update

apis/ec2/manualv1alpha1/securitygrouprule_types.go, package/crds/ec2.aws.crossplane.io_securitygrouprules.yaml
Updated the status output of securitygrouprules to show ready, synced, id and sg
I have:
=> fix: Updated status output of sgr to show ready, synced, id and sg

apis/ec2/v1beta1/vpc_types.go, package/crds/ec2.aws.crossplane.io_vpcs.yaml, pkg/clients/ec2/vpc.go, pkg/clients/ec2/vpc_test.go
Signed-off-by: Harvey Xia <harvey.xia@reddit.com>
Exports the VPC ID to the VPC status. This is a slightly more readable + ergonomic way to retrieve the VPC's ID than using the `crossplane.io/external-name` annotation.
I have:
I added a test for the new field and executed them with `make test`.
=> Export VPC ID to VPC status

apis/ec2/generator-config.yaml, apis/ec2/v1alpha1/custom_types.go, apis/ec2/v1alpha1/zz_flow_log.go, apis/ec2/v1alpha1/zz_generated.deepcopy.go, package/crds/ec2.aws.crossplane.io_flowlogs.yaml, pkg/controller/ec2/flowlog/setup.go, pkg/controller/ec2/flowlog/zz_conversions.go
Due to a mismatching upper and lowercase letters, the DeliverLogsPermissionArn property was not filled when creating a flow log. This pull request fixes this.
I have:
=> fix: Fixed generation of flowlog

apis/rds/v1alpha1/custom_types.go, package/crds/rds.aws.crossplane.io_dbclusters.yaml
Signed-off-by: Guilherme Souza <101073+guilhermef@users.noreply.github.com>
When PR #1413 was tested, we noticed that the  `masterUserPasswordSecretRef` was still required since it's used as a reference to the secret that will hold the generated DBCluster password.
This PR will make it required again.
I have:
A new DBCluster was created in our environment with an empty password.
The provider created a random password and stored it on the Secret.
=> Ensure masterUserPasswordSecretRef is still required

pkg/controller/eks/identityproviderconfig/controller.go, pkg/controller/eks/identityproviderconfig/controller_test.go
Fixes #1422
I have:
Unit testing
=> fix(eks/identityproviderconfig): Reset status field to retry create

pkg/controller/ec2/securitygrouprule/controller.go, pkg/controller/ec2/securitygrouprule/controller_test.go
Signed-off-by: Kamil Dudek <kamil.dudek@gmail.com>
Updated SecurityGroupRule controller to honor the SourceSecurityGroup spec field.
Fixes #1442
I have:
=> feat: Handle SourceSecurityGroup field from the spec

CODE_GENERATION.md
The GENERATED_SERVICES variable is automatically set in Makefile
(https://github.com/crossplane-contrib/provider-aws/blob/master/Makefile#L11).
So there is no need to manually update it whenever we create a new
service, as the documentation suggests.
Fixes: #1456
I have:
No testing required, it's a doc fix.
=> doc: removed comment about updating GENERATED_SERVICES manually

apis/rds/v1alpha1/referencers.go, pkg/controller/rds/dbinstance/setup.go
The describe endpoint of aws for dbinstance returns the full arn for kmskeyid. If an dbinstance is created with an keyed only, Crossplane tries to update the instance. 
This update uses only the key id part of the returned are, if the user uses only an id for the kmykeyid field.
#1348 
I have:
We used the following yaml for testing:
```yaml
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
name: example
spec:
forProvider:
region: eu-central-1
allocatedStorage: 20
dbInstanceClass: db.t3.medium
preferredBackupWindow: "02:46-03:16"
preferredMaintenanceWindow: "Wed:00:12-wed:00:42"
dbName: prada
vpcSecurityGroupIDs:
- sg-88d8e3fc
dbSubnetGroupName: sample-subnet-group
backupRetentionPeriod: 30
engine: postgres
engineVersion: "14.1"
masterUsername: …
```
=> fix: Adjusting returned keyarn to match input value

CODE_GENERATION.md
Signed-off-by: Romain Dauby <romain.dauby@gmail.com>
Minor fix on the CODE_GENERATION documentation. 
While contributing to #1482 I encountered non working examples because the provider is not labeled `example`.
I have:
N/A
=> fix: same name as examples for ProviderConfig

apis/glue/v1alpha1/custom_types.go, apis/glue/v1alpha1/zz_generated.resolvers.go
Adds line to extract ARN from Role to be used for `Crawler`
I miss of my part, when I enhanced the Glue service here.
Role reference for the resource `Crawler` should use the ARN:
1. for consistency -> same as the Glue resource `Job`
2. with ARN through refs, users don't have to think about possible path, if other fields only take ARN
I have:
Manually with the relating example.
=> fix(crawler): RoleRef should extract ARN

apis/s3/v1beta1/notificationConfiguration_types.go, apis/s3/v1beta1/zz_generated.resolvers.go
Signed-off-by: Michael Duffy <mike@stunthamster.com>
This PR fixes an issue where SNS notifications cannot be added to S3 buckets using topicRef names. Currently, the topicRef attempts to find a SNSTopic object from the deprecated notification.aws.crossplane.io API group. This PR changes it to use the correct SNS API group. 
I have:
- [ x] Read and followed Crossplane's [contribution process].
- [ x] Run `make reviewable test` to ensure this PR is ready for review.
N/A
=> Fixes an issue with S3 notifications

examples/ec2/securitygroup.yaml
added example for securityGroup with `ipProtocol: -1`
Fixes #1400 #1138
I have:
```
kubectl get managed
NAME                                                    READY   SYNCED   ID                     VPC                     AGE
securitygroup.ec2.aws.crossplane.io/db-security-group   True    True     sg-099d50bb8084771f4   vpc-03359a2baaabf1704   12s
securitygroup.ec2.aws.crossplane.io/sample-cluster-sg   True    True     sg-08e483bec56b040fa   vpc-03359a2baaabf1704   12s
NAME                                    READY   SYNCED   ID                      CIDR          IPV6CIDR   AGE
vpc.ec2.aws.crossplane.io/sample-vpc    True    True     vpc-03359a2baaabf1704   10.0.0.0/16              33s
vpc.ec2.aws.crossplane.io/sample-vpc2   True    True …
```
=> feat(sg): added example for ipProtocol -1

go.mod, go.sum
added latest `crossplane-runtime` version to add paused annotation for resources
```
apiVersion: efs.aws.crossplane.io/v1alpha1
kind: FileSystem
metadata:
annotations:
crossplane.io/external-create-pending: "2022-10-02T10:58:03Z"
crossplane.io/external-create-succeeded: "2022-10-02T10:58:04Z"
crossplane.io/external-name: fs-0e6772a4e20d76a8c
crossplane.io/paused: "true"
creationTimestamp: "2022-10-02T10:58:03Z"
finalizers:
- finalizer.managedresource.crossplane.io
generation: 1
name: example
resourceVersion: "515627"
uid: e289916c-6842-417e-972d-5e49d9a54059
spec:
forProvider:
name: default
status:
atProvider:
creationTime: "2022-10-02T10:58:04Z"
creationToken: …
```
=> feat(runtime): bump runtime to latest version for paused annotation

apis/ec2/manualv1alpha1/securitygrouprule_types.go, apis/ec2/v1beta1/securitygroup_types.go, apis/ec2/v1beta1/zz_generated.deepcopy.go, package/crds/ec2.aws.crossplane.io_securitygrouprules.yaml, pkg/clients/ec2/securitygroup.go, pkg/controller/ec2/securitygroup/controller.go
This PR increases the documentation for SecurityGroupRules by adding an important hint to securityGroupId.
Without it users might miss that they need to set the option ignoreIngress and/or ignoreEgress and it will lead to repeated recreation of SecurityGroupRules.
Fixes #1516
I have:
Will be tested by running locally with `make run`
=> Add docs for SecurityGroupRule to fix #1516

Makefile
- Compile code-generator to avoid link overhead per service
- Run AWS ACK code-generator with go.mod --aws-sdk-go-version
Fixes #1414
Fixes https://github.com/aws-controllers-k8s/community/issues/1441
I have:
* No changes w/ make services.all
* Compiling code (not tested) with `go get github.com/aws/aws-sdk-go@v1.43.43 && go mod tidy`. Testing new SDKs will still be the responsibility of the change bumping the SDK
=> Run AWS ACK code-generator with go.mod --aws-sdk-go-version

README.md
Signed-off-by: Pete Lumbis <pete@upbound.io>
The Crossplane docs were recently restructured and the link to the `latest` version changed. This updates the readme to point to the correct URL
=> Updates link to the latest version of Crossplane docs

Makefile
bump submodule & add mkdir for ${WORK_DIR}
Fixes failing ci-run for check-diff
https://github.com/crossplane-contrib/provider-aws/actions/runs/3296907421/jobs/5531645950#step:8:21
I have:
=> feat(submodule): bump submodule & add mkdir for ${WORK_DIR}

apis/elbv2/manualv1alpha1/target.go, pkg/controller/elbv2/target/controller.go
=> fix(elbv2/target): Retry registration if target is unused

AUTHENTICATION.md
Signed-off-by: Bob Haddleton <bob.haddleton@nokia.com>
Updated links in the AUTHENTICATION.md file to point at Crossplane v1.10 docs instead of v1.6.
It would be better to point at a "latest" link rather than a specific release, but that will require updates in Crossplane docs.
I have:
Verified that the links are correct
=> Fix documentation links in AUTHENTICATION.md

pkg/controller/rds/dbinstance/setup.go
Signed-off-by: Lyuben Dimitrov <l.dimitrov@reply.de>
Late initialize the engineVersion for db Instance in case it is running within a DB cluster.
I noticed a lot of my managed `dbinstance.rds.aws.crossplane.io` resource were not Syncing. After inspection I got an error message:
```shell
update failed: cannot update DBInstance in AWS: InvalidParameterCombination: 
The specified DB Instance is a member of a cluster. Modify the DB engine version for the DB Cluster using the ModifyDbCluster API 
```
In my setup, I have a DB Clusters with multiple DB Instances and a lot of the parameters can be only updated for the DB Cluster. I believe the engineVersion belongs also here in this check.
I have:
=> feat: late init engineVersion if DBInstance is running within DBCluster

apis/eks/v1beta1/types.go, examples/eks/cluster.yaml, package/crds/eks.aws.crossplane.io_clusters.yaml
> 1.6686110160807893e+09    ERROR    controller.managed/cluster.eks.aws.crossplane.io    Reconciler error    {"reconciler group": "eks.aws.crossplane.io", "reconciler kind": "Cluster", "name": "baum-dev-cluster-76fz7", "namespace": "", "error": "cannot update managed resource status: Cluster.eks.aws.crossplane.io \"baum-dev-cluster-76fz7\" is invalid: status.atProvider.outpostConfig.outpostArns: Required value"}
This change fixes the above error, which resulted in no `status` of the resource being delivered.
I have:
manually with the example
=> fix(eks/cluster): outpost status fields optional

pkg/controller/rds/dbinstance/setup.go
If the field `engineVersion` is not set or unset by the user, the `dbInstance` controller would have a panic runtime error due to nil pointer dereference in `isUpToDate`.
This change should fix this possibly rare occasion. 
I have:
manually with the db_instance.yaml example
=> fix(rds/dbinstance): possible nil pointer panic

apis/cache/v1beta1/replication_group_types.go, package/crds/cache.aws.crossplane.io_replicationgroups.yaml, pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticache_test.go
Populate cache status with endpoint correctly, and correct json tag for node group. 
fixes: #1358 
This should probably move to elasticache in the future like Christopher mentioned in the issue.
Signed-off-by: Manabu McCloskey <manabu.mccloskey@gmail.com>
I have:
Tested against my cluster. 
Before:
```yaml
status:
atProvider:
automaticFailoverStatus: enabled
configurationEndpoint: {}
```
After:
```yaml
status:
atProvider:
automaticFailoverStatus: enabled
configurationEndpoint:
address: master.sgonly-w92q6-mjsjl.pqeclz.usw2.cache.amazonaws.com
port: 6380
```
=> fix(cache/endpoint): populate cache status with endpoint

apis/s3/v1beta1/bucket_types.go, package/crds/s3.aws.crossplane.io_buckets.yaml
Just add a bit of documentation in the field locationConstraint for S3 buckets, to help people to debug some "error dialing" given by AWS and not by the provider
Fixes #
I have:
=> chore: Document field error on S3 Bucket types

pkg/controller/cognitoidentityprovider/groupusermembership/controller.go, pkg/controller/cognitoidentityprovider/groupusermembership/controller_test.go
Signed-off-by: abacus3 <57175410+abacus3@users.noreply.github.com>
- Fixed incorrect `FindAttachedGroupObject` function call in https://github.com/crossplane-contrib/provider-aws/blob/095bdea17800049a200d7dbfbcc95f57870c3ada/pkg/controller/cognitoidentityprovider/groupusermembership/controller.go#L154 by swapping username and userPoolId invokation parameter
- Extended automatic test case: in https://github.com/crossplane-contrib/provider-aws/blob/02b4ddc8c5cadddbff93b86e37924321f6166732/pkg/controller/cognitoidentityprovider/groupusermembership/controller_test.go#L110-L136
Fixes #1586
I have:
Exsiting automated test cases have been extended.
Manual testing of the valid test case has been performed.
=> fix(cognitoidentity): Update broken AWS API function call for GroupUserMembership

pkg/clients/elasticloadbalancing/elb/elb.go
If multiple listeners are added to an ELB, the controller compares the current state with the desired state, but the listeners' list is not sorted, causing endless updates.
Each time the controller updates, the listeners are removed and added again, causing the AWS API rate limit to be exceeded.
Fixes #
I have added a sort function for the current state and the desired state and tested it using my local Kind cluster.
I have:
- [V] Read and followed Crossplane's [contribution process].
- [V] Run `make reviewable test` to ensure this PR is ready for review.
This code has been tested using Kind cluster.
=> Bug - ELB updates every reconcile when running multiple listeners 

apis/rds/generator-config.yaml, apis/rds/v1alpha1/custom_types.go, apis/rds/v1alpha1/zz_db_cluster.go, apis/rds/v1alpha1/zz_db_instance.go, apis/rds/v1alpha1/zz_generated.deepcopy.go, examples/rds/db-aurora-cluster.yaml, examples/rds/db-instance.yaml, package/crds/rds.aws.crossplane.io_dbclusters.yaml, package/crds/rds.aws.crossplane.io_dbinstances.yaml, pkg/controller/rds/dbcluster/setup.go, pkg/controller/rds/dbcluster/setup_test.go, pkg/controller/rds/dbcluster/zz_conversions.go, pkg/controller/rds/dbinstance/setup.go, pkg/controller/rds/dbinstance/zz_conversions.go
to both DBInstance and DBCluster
- add field/flag `allowMajorVersionUpgrade` (+ special update handling needed for DBCluster)
- make condition.status partly include AWS resource status (willing to revert parts here, if considered too redundant)
- implement controllers updating `VPCSecurityGroupIDs` and `DBParameterGroupName`/`DBClusterParameterGroupName`
Fixes #1330
I have:
manual tests (DBInstance; DBCluster with DBInstance)
=> feat(rds): instance + cluster allowMajorVersionUpgrade

pkg/controller/docdb/dbcluster/setup.go, pkg/controller/docdb/dbcluster/setup_test.go
The controller for docdb/DBCluster checks if the field `DBSubnetGroup` isUpToDate. However it is not updatable. (e.g. see [AWS CLI docdb - modify-db-cluster](https://docs.aws.amazon.com/cli/latest/reference/docdb/modify-db-cluster.html) and [AWS DocDB DBCluster docs](https://docs.aws.amazon.com/documentdb/latest/developerguide/db-cluster-parameters.html))
This change removes that check (+ unnecessary tests).
I have:
only through `make reviewable test`
=> fix(docdb/dbcluster): remove unwanted dbsubnetgroup isuptodate-check

apis/docdb/v1alpha1/custom_types.go, examples/docdb/cluster-autogenPassword.yaml, package/crds/docdb.aws.crossplane.io_dbclusters.yaml, pkg/controller/docdb/dbcluster/setup.go, pkg/controller/docdb/dbcluster/setup_test.go
Signed-off-by: Steven Borrelli <steve@borrelli.org>
Add `autogenPassword` functionality (similar to RDS) to docdb clusters.
I have:
Tested using an EC2 instance mongo client with the generated password:
```console
mongosh --tls --host example-cluster-autogen-password.cluster-czjq0bppekwt.us-east-1.docdb.amazonaws.com:27017 --tlsCAFile rds-combined-ca-bundle.pem --username master --password $PW
Current Mongosh Log ID:	63b8ab77e42f14df6bca2c7a
Connecting to:		mongodb://<credentials>@example-cluster-autogen-password.cluster-czjq0bppekwt.us-east-1.docdb.amazonaws.com:27017/?directConnection=true&tls=true&tlsCAFile=rds-combined-ca-bundle.pem&appName=mongosh+1.6.1
Using MongoDB:		4.0.0
Using Mongosh:		1.6.1
rs0 [direct: primary] test> 
```
=> Add autogen-password support to docdb

pkg/clients/resourcerecordset/resourcerecordset.go, pkg/clients/resourcerecordset/resourcerecordset_test.go
When setting `AliasTarget` in `v1alpha1.ResourceRecordSetParameters`, `IsUpToDate()` will always return false since it does not fill up the field `AliasTarget` then `CreatePatch` will contain the part about `AliasTarget` when comparing with the expected state.
This will make it always try to do a useless update after observing the state.
I have:
Add unit test.
Note before fixing it, the first call of `IsUpToDate` in the added test case should be true, but it return false.
=> resourcerecordset: Should set AliasTarget when check if it is up to date

cmd/provider/main.go, go.mod
Signed-off-by: Christopher Paul Haar <christopherpaul.haar@dkb.de>
changed logger to ISO8601TimeEncoder
old:
```
1.6656692709539523e+09     DEBUG   provider-aws    External resource is up to date {"controller": "managed/subnet.ec2.aws.crossplane.io", "request": "/sample-subnet2", "uid": "99db324c-c44b-4395-b626-b1cbd543255e", "version": "1317437", "external-name": "subnet-0111adcde1b842c07", "requeue-after": "1.6656692755539544e+09 "}
```
new:
```
2023-01-10T09:43:02.292+0100    DEBUG   provider-aws    External resource is up to date {"controller": "managed/subnet.ec2.aws.crossplane.io", "request": "/sample-subnet2", "uid": "99db324c-c44b-4395-b626-b1cbd543255e", "version": "1317437", "external-name": "subnet-0111adcde1b842c07", "requeue-after": "2023-01-10T09:44:02.292+0100"}
```
Fixes # …
=> feat(logger): changed logger to ISO8601TimeEncoder

apis/kafka/generator-config.yaml, apis/kafka/v1alpha1/zz_cluster.go, apis/kafka/v1alpha1/zz_generated.deepcopy.go, examples/kafka/cluster.yaml, package/crds/kafka.aws.crossplane.io_clusters.yaml, pkg/controller/kafka/cluster/setup.go, pkg/controller/kafka/cluster/zz_controller.go, pkg/controller/kafka/cluster/zz_conversions.go
Signed-off-by: Christopher Paul Haar <christopherpaul.haar@dkb.de>
fix(kafka): add clusterName because of api-changes
Fixes #1612
replace: #1620
I have:
```
kubectl get managed
NAME                                      READY   SYNCED   EXTERNAL-NAME
cluster.kafka.aws.crossplane.io/example   True   True     arn:aws:kafka:us-east-1:12345678910:cluster/example/cef294f9-8e22-4342-9bfd-9635fcaeaebb-9
NAME                                                          READY   SYNCED   EXTERNAL-NAME
configuration.kafka.aws.crossplane.io/example-configuration   True    True     arn:aws:kafka:us-east-1:12345678910:configuration/example-configuration/73a88bf4-8aee-485e-b004-a788735643d4-9
```
=> fix(kafka): add clusterName because of api-changes

apis/servicediscovery/v1alpha1/custom_types.go, pkg/clients/servicediscovery/fake/fake.go, pkg/controller/servicediscovery/commonnamespace/hooks.go, pkg/controller/servicediscovery/commonnamespace/hooks_test.go, pkg/controller/servicediscovery/httpnamespace/setup.go, pkg/controller/servicediscovery/privatednsnamespace/setup.go, pkg/controller/servicediscovery/publicdnsnamespace/setup.go
Implemented update and observe function to namespace controller for AWS Servicediscovery.
Remove write back option from AWS to “ForProvider" object.
This PR is based on #1433, which seems to be stale.
httpnamespace
- Description
- Tags
privatednsnamespace, publicdnsnamespace
- Description
- Tags
- TTL
Fixes #1395 
I have:
Added unit test for tag update. All resources were tested manually (create, update, delete).
=> feat(servicediscovery): Add Update function for namespaces

pkg/controller/kinesis/stream/setup.go
Signed-off-by: Alex Last <alexrichardlast@gmail.com>
Fixes #1246 an index out of range panic in the Kinesis controller, caused when `spec.forProvider.EnhancedMetrics` is not defined:
```
panic: runtime error: index out of range [0] with length 0
goroutine 830 [running]:
github.com/crossplane-contrib/provider-aws/pkg/controller/kinesis/stream.(*updater).isUpToDate(0xc000d613e0?, 0xc000f82900, 0xc00044e3f8)
github.com/crossplane-contrib/provider-aws/pkg/controller/kinesis/stream/setup.go:146 +0x66d
github.com/crossplane-contrib/provider-aws/pkg/controller/kinesis/stream.(*external).Observe(0xc0007d2070, {0x3d491f0, 0xc000a65260}, {0x3d6a9a0?, 0xc000f82900})
github.com/crossplane-contrib/provider-aws/pkg/controller/kinesis/stream/zz_controller.go:91 +0x2b0 …
```
=> fix(kinesis): panic when enhanced metrics not defined

pkg/clients/eks/nodegroup.go
When LaunchTemplate is nil at aws, but not nil at resource, this will panic.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x3662412]
goroutine 5134 [running]:
github.com/crossplane-contrib/provider-aws/pkg/clients/eks.LateInitializeNodeGroup(0xc03cb6d2c8, 0xc031b40fc0)
github.com/crossplane-contrib/provider-aws/pkg/clients/eks/nodegroup.go:287 +0x432
github.com/crossplane-contrib/provider-aws/pkg/controller/eks/nodegroup.(*external).Observe(0xc03da49780, {0x6a47570, 0xc0418b7620}, {0x6a7ce58?, 0xc03cb6d180})
github.com/crossplane-contrib/provider-aws/pkg/controller/eks/nodegroup/controller.go:114 +0x207
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc00064 …
```
=> Fix panic when ng.LaunchTemplate is nil

pkg/clients/eks/nodegroup.go, pkg/clients/eks/nodegroup_test.go, pkg/controller/eks/nodegroup/controller.go
Signed-off-by: Adam Johnson <adamjohnson01@gmail.com>
This change enables updates to EKS NodeGroups that use custom AMIs. 
According to the [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html) on using `LaunchTemplates` with managed nodegroups
The following fields can't be set in the API if you specify an AMI ID:
- amiType
- releaseVersion
- version
I have updated the code to ignore releaseVersion and version when amiType is `CUSTOM` and  update the `NodeGroup` object in k8s with updated values when running `Observe`.
Fixes #1632
I have:
I have run the code in my local cluster and confirmed that it is now possible to update NodeGroups that use custom AMIs
=> fix(eks): Add checks for custom AMIs to enable updates

pkg/clients/resourcerecordset/resourcerecordset.go, pkg/clients/resourcerecordset/resourcerecordset_test.go
Fix CAN NOT update `AliasTarget`
In Observe():
...
resourcerecordset.LateInitialize(&cr.Spec.ForProvider, rrs)
...
So the AliasTarget will be overwritten as the value observe from aws if
we update it.
Introduced by #1621 
I have:
- unit test
-  deploy this version and try update `AliasTarget`
=> Fix updated AliasTarget overwritten

examples/cache/cachecluster.yaml, pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticcachecluster_test.go, pkg/controller/cache/cluster/controller.go
Signed-off-by: Christopher Paul Haar <christopherpaul.haar@dkb.de>
changed version handling for cache cluster
Fixes #1617
I have:
added new example
```
kubectl get managed
NAME                                                          STATUS      READY   SYNCED   AGE
cachecluster.cache.aws.crossplane.io/aws-memcached-standard   available   True    True     19m
cachecluster.cache.aws.crossplane.io/redis-cache-cluster      available   True    True     19m
```
=> feat(cache): fix version handling for #1617

pkg/controller/rds/dbinstance/setup.go
When setting the new `caCertificateIdentifier` parameter for `DBInstances` the resource is continually updated with the following:
```
Normal  UpdatedExternalResource  16m (x66 over 81m)   managed/dbinstance.rds.aws.crossplane.io  Successfully requested update of external resource
```
This ensures that `caCertificateIdentifier` is handled correctly in the `lateInitialize()` function.
I have:
=> fix(rds): include caCertificateIdentifier in lateInitialize for dbinstance

apis/database/v1beta1/rdsinstance_types.go, package/crds/database.aws.crossplane.io_rdsinstances.yaml
Update for the description of rds MasterUsername constraints according to:
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html
Fixes #1701 
I have:
So it just updates a CRD description field no further testing is necessary.
=> chore(rds): update description for MasterUsername

go.mod, pkg/controller/s3/bucket/policy.go
Remove the policy autofill since it requires the ARN and is not available during bucket creation. Also the user might require to enter a string other than the bucket ARN.
Require the user to set the ARN himself.
Fixes #1716
I have:
Sample resource
=> fix(bucket): Remove policy resource autofill

pkg/controller/iam/instanceprofile/setup.go
When performing the PreDelete step on an `InstanceProfile` that detaches a role via `RemoveRoleFromInstanceProfileWithContext` it is possible that the role no longer exists. If so, the `InstanceProfile` can no longer be deleted succesfully, repeatedly failing the `PreDelete` step.
This ignores the error is `NoSuchEntity` is returned when detaching the role as the role not existing implies we should be able to proceed with the delete step for the instance profile.
Fixes #1713 
I have:
Use of fork in internal crossplane deployment, instance profiles no longer get stuck during teardown due to the role already being detached and deleted.
=> Skip error if role no longer exists in instance profile deletion

pkg/controller/ec2/vpccidrblock/controller.go
The VPCCIDRBlock association is never actually removed from the VPC when the VPCCIDRBlock is deleted, it is put into the `disassociated` state where it remains until the VPC is deleted.
This change modifies the Observe function to check to see if the managed resource has been deleted when it finds the VPCCIDRBlock is in the `disassociated` state and return `ResourceExists: false` so that the reconciler will remove the finalizer and allow the MR to be deleted.
Fixes #1729 
I have:
Verified that the VPCCIDRBlock resource is deleted properly when this fix is applied.
=> Handle VPCCIDRBlock delete case in Observe

apis/rds/v1alpha1/custom_types.go, examples/rds/db-aurora-globalcluster-full.yaml, package/crds/rds.aws.crossplane.io_dbclusters.yaml
Fixes #1668
When creating an Aurora Global cluster with more than 2 regional clusters, the password attribute is mandatory for the first one, but not for the second one. Right now, it's impossible to create global cluster with more than 2 regional cluster.
If you avoid setting up the `masterUserPasswordSecretRef`, Crossplane CRD will complain because this field is required and won't let you create the resource.
If you set up the `masterUserPasswordSecretRef`, the AWS API will complain that the cluster can't be created with the following error message
```
create failed: cannot create DBCluster in AWS: InvalidParameterCombination: Cannot specify password for cross region replication cluster
```
=> Remove `masterUserPasswordSecretRef` as a required attribute

examples/mwaa/infra.yaml, examples/s3/bucket-with-policy.yaml, examples/s3/bucket.yaml
Most regions have disabled ACLs for new buckets.
Update examples to code that works out of the box.
Setting BucketOwnerEnforced will disable ACLs explicitly.
Updates #1723
I have:
Created bucket in `eu-north-1`. Failes out of the box. Works with this update.
See https://github.com/crossplane-contrib/provider-aws/issues/1723 for more info.
=> S3 examples: ACLs no longer supported for new buckets in many regions

pkg/controller/ec2/vpcpeeringconnection/setup.go
Update the postObserve() function for VPCPeeringConnection to handle the delete case.  Also handle some corner cases to
prevent the resource from getting stuck during cleanup from error conditions.
Fixes #1732 
I have:
Created a VPCPeeringConnection and verified that the delete process works as expected and the resource does not get stuck.
Also verified that a failed VPCPeeringConnection does not get stuck, and the code does not try to apply peer options updates when the connection is not active.
=> Handle the VPCPeeringConnection delete case

pkg/controller/s3/bucket/publicAccessBlock.go, pkg/controller/s3/bucket/publicAccessBlock_test.go
Due to a combination of issues:
* late-init not allowing explicit "null"
* AWS recently introduced a change which adds a publicAccessBlockConfiguration by default
* AWS rejects an all-false publicAccessBlockConfiguration
it is not possible to create new public buckets with provider-aws at the
moment.
This change allows this by sending DELETE when the user creates an
all-false publicAccessBlockConfiguration:
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
name: test-bucket
annotations:
crossplane.io/external-name: bucket-1234-hello
spec:
forProvider:
objectOwnership: BucketOwnerEnforced
locationConstraint: us-east-1
publicAccessBlockConfiguration:
blockPublicPolicy: false
blockPublicAcls: false
ignorePublicAcls: false
restrictPublicBuckets: false
name: …
=> s3: Allow explicitly disabling PublicAccessBlockConfiguration

apis/sns/v1beta1/subscription_types.go, apis/sns/v1beta1/zz_generated.deepcopy.go, package/crds/sns.aws.crossplane.io_subscriptions.yaml, pkg/clients/sns/subscription.go
Add FilterPolicyScope SNS property
I have:
Tested on custom image devopsmindset/provider-aws:v0.0.0-2805.gc24807d8 with proper sns
=> Add FilterPolicyScope SNS property

pkg/controller/s3/bucket/policy.go, pkg/controller/s3/bucket/policy_test.go
In the observe policy in the bucket, the comparison of JSON strings was changed to the comparison between actual JSON objects to prevent the update loop. This way it recognizes that the two objects are the same.
We love pull requests that resolve an open Crossplane issue. If yours does, you
can uncomment the below line to indicate which issue your PR fixes, for example
"Fixes #500":
-->
Fixes #1757
I have:
- [ X] Run `make reviewable test` to ensure this PR is ready for review.
=> fix(s3) compare unmarshaled policy

pkg/controller/iam/role/controller.go, pkg/controller/iam/role/controller_test.go
Adds the ARN for a Role to ConnectionDetails in external observations so that it gets published if a connection secret is requested.
Fixes #1063 
I have:
Unit test amended
Tested on local development environment using the following role and confirmed the connection secret contained the correct arn.
```
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
name: "test-role"
spec:
forProvider:
description: Test Role Desc
assumeRolePolicyDocument: |
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"Service": [
"ec2.amazonaws.com"
]
},
"Action": [
"sts:AssumeRole"
]
}
]
}
tags:
- key: ManagedBy
value: crossplane/provider-aws
writeConnectionSecretToRef:
name: "test-role-connection"
namespace: "default"
```
```
kubectl get secret test-role-connection -o …
```
=> 1063: Write IAM Role ARN to connection secret if secret ref is given

go.mod, pkg/controller/s3/bucket/policy.go, pkg/controller/s3/bucket/policy_test.go, pkg/utils/policy/compare.go, pkg/utils/policy/parse.go, pkg/utils/policy/parse_test.go, pkg/utils/policy/testdata/UnmarshalArrays.json, pkg/utils/policy/testdata/UnmarshalSinglesAsList.json, pkg/utils/policy/types.go
AWS converts bool values in policy conditions to strings when getting them from the API.
This adds a new policy parser based on structs that can handle AWS policies correctly, including single items instead of lists.
Fixes #1771
I have:
Using the example provided in #1771. Added it as a unit test as well.
=> fix(bucket): Convert bools to string in policy

pkg/clients/aws.go
Replaces the hardcoded web identity token filepath for with the environment variable `AWS_WEB_IDENTITY_TOKEN_FILE`.
Fixes #1775
I have:
n.a.
=> fix: Get web identity token filepath from environment

pkg/clients/iam/policy.go, pkg/clients/iam/policy_test.go, pkg/controller/iam/policy/controller.go
Fixes the issue of single items in IAM policies. This treats:
```
action: "s3:PutObject"
```
as
```
action: ["s3:PutObject"]
```
Fixes #932 
Replaces #942
Related to #1772 
I have:
Unit tests
=> fix(iam/policy): Treat single items as array

pkg/clients/iam/policy.go, pkg/controller/iam/policy/controller_test.go
Fixes a bug that was introduced in #1774 which causes reconcile to fail during parsing of an URL-encoded policy document.
I have:
Unit tests and the existing examples.
=> fix(iam): Decode policy document before parsing

pkg/clients/sns/topic.go, pkg/clients/sns/topic_test.go, pkg/controller/sns/topic/controller.go
In the observed policy on the topic, the comparison of JSON strings was changed to comparing actual JSON objects to prevent the update loop. This way it recognizes that the two objects are the same.
I have:
I have added a unit test to check this case.
=> fix(topic): Improve topic policy json diff check

examples/efs/filesystem.yaml, pkg/controller/efs/filesystem/setup.go, pkg/controller/efs/tags.go
Fixes #1284
add tag update functionality to EFS Filesystem
Similar to RDS Optiongroup, I put the tags-update-call into isUpToDate() and not into postUpdate(). (see here: https://github.com/crossplane-contrib/provider-aws/blob/9205a212d0c301cca16697c1c159d4de60cc2826/pkg/controller/rds/optiongroup/setup.go#L115-L122)
The reason is probably the same: AWS denies the "regular" UpdateFileSystem()-Call, if there is no actual change included. See the received error:
> {RespMetadata: {StatusCode: 400, RequestID: ""}, 
ErrorCode: "BadRequest", Message_: "The file system won't be updated. The requested throughput mode or provisioned throughput value are the same as the current mode and value."}
I have:
Manually with example
=> feat(efs/filesystem): update tags

pkg/controller/rds/dbinstance/setup.go
Between version 0.40.0 and 0.40.1 the enginVersion parameter for rds dbinstances got lost.
Therefore dbengines will always be created in the default version. This pull requests adds the engine Version in the preCreate step of the setup
Fixes #1798 
I have:
Tested manually 
=> fix: add enginVersion when creating rds dbinstance

apis/ecs/v1alpha1/custom_types.go, package/crds/ecs.aws.crossplane.io_services.yaml, pkg/controller/ecs/service/setup.go
Fix ECS Service deletion when the task are in error
Currently with the validation, if the ecs service creates a task that is not possible to spin up (e.g. wrong image), it is also not possible to delete the service, because the cr.Status.AtProvider.RunningCount and cr.Status.AtProvider.PendingCount won't be greater than 0.
In aws console it was also possible to delete the service (with task in error) by selecting the "force" option
I have:
Created a ECS Task Definition with non existing image, created a ECS Service pointing to this Task Definition, and then removed the Service CR
=> feat(ecs)!: Make force deletion explicit

examples/database/rdsinstance.yaml, pkg/clients/database/rds.go, pkg/controller/rds/dbinstance/setup.go
In the controllers of the resources database `RDSInstance` and rds `DBInstance` an extra check for the parameter `OptionGroupName` is added as this needs to be checked against the entries of `OptionGroupMemberships` given by the Describe output.
Fixes #1795 (similar `CloudwatchLogsExportConfiguration` issue will be addressed in separate PR)
**Note**: rds `DBCluster` also has the field `OptionGroupName` , so I tried implementing the same logic here too. However I got this error: 
> create failed: cannot create DBCluster in AWS: InvalidParameterCombination: Option groups are not supported for DB Clusters
So one may consider removing the field here? (see also no such field 
at terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster)
I have:
Manually
=> fix(rdsinstance/dbinstance): check optiongroupname correctly

pkg/controller/kafka/cluster/setup.go
This update should fix the error  "cannot update Security of Cluster in AWS: BadRequestException: The request does not include any updates to the security setting of the cluster. Verify the request, then try again."
I have:
=> fix: enable encryptionatrest and inCluster

examples/eks/addon.yaml, pkg/controller/eks/addon/setup.go, pkg/controller/eks/addon/setup_test.go
eks addon configurationValues is supported already in the spec but is not included in `isUpToDate` and therefore can never be changed with the provider.
https://github.com/crossplane-contrib/provider-aws/blob/master/apis/eks/v1alpha1/zz_addon.go#L40-L43
This PR adds the custom `isUpToDate` in order to update the `configurationValues`
The configurationValues is a string value but both json and yaml are supported. (See - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/)
Note the implementation for the string comparison.
Whitespace and indendation is difficult to get correct when using a string value.
This PR does UnMarshal and Marshal the json or yaml to ensure that the comparison is more accurate.  It lessens the risk that this provider will continually …
=> fix(eks): Add reconciliation for addon configurationValues

.golangci.yml
Increase the linter timeout to 30 minutes to avoid failing pipelines due to context deadlines.
I have:
=> chore(ci): Increase golangci timeout to 30min

pkg/controller/ec2/vpcendpoint/setup.go, pkg/controller/ec2/vpcendpoint/setup_test.go, pkg/controller/ec2/vpcendpointserviceconfiguration/setup.go, pkg/controller/ec2/vpcendpointserviceconfiguration/setup_test.go, pkg/controller/ec2/vpcpeeringconnection/setup.go, pkg/controller/ec2/vpcpeeringconnection/setup_test.go
Fixes possible in nil pointer derefs during tag initialization in the following EC2 controllers:
* VPCEndpoint
* VPCEndpointConfiguration
* VPCPeeringConnection
Fixes #1842 
I have:
Unit tests
=> fix(ec2): Possible nil derefs in ec2 controllers

pkg/controller/efs/utils/tags.go, pkg/controller/efs/utils/tags_test.go
Ignores AWS internal tags starting with `aws:` that cannot be added or removed and would cause an error if done so.
Fixes #1847
cc @denniskorbginski
I have:
Unit tests
=> fix(efs): Ignore AWS system tags

pkg/controller/mq/setup.go, pkg/controller/mwaa/setup.go
Uses the correct package names for `mwaa` and `mq`. No functional code changes were made.
I have:
n.a.
=> fix: Package names for mwaa and mq

cmd/provider/main.go, go.mod, go.sum, pkg/clients/config.go, pkg/utils/metrics/setup.go
This change will add a new Prometheus metric, `aws_api_calls_total`, exposed by controller-runtime that counts all requests made to the AWS APIs. This is useful when using expensive APIs like the Service Catalog API ($0.0007/request) for accounting purposes on accounts with multiple clusters.
I have:
This has been built and deployed to a test cluster where it was successfully observed to cause no errors when calling either v1 or v2 SDK methods, and successfully included the new metric on the `/metrics` endpoint.
=> feat: expose metrics for all AWS API calls

pkg/controller/aws.go
Fixes #1874 by adding missing setup functions. 
It appears #1827 missed a few api groups during the refactor.
To identify missing groups I simply ran `find pkg/controller -name 'setup.go' -maxdepth 2 | sort` and compared to the existing `aws.go` file and added missing lines. Not sure if I missed anything else so happy to hear feedback on the approach.
I have:
After making my changes and running the provider locally I've executed:
```
kubectl apply -f examples/dynamodb/table.yaml
```
And saw successful handling of DynamoDB resources:
```
NAME                                                                     READY   SYNCED   EXTERNAL-NAME
table.dynamodb.aws.crossplane.io/sample-table                            True    True     sample-table …
```
=> fix(aws): Add missing api groups setup functions

pkg/controller/kinesis/stream/setup.go
When you have a different external-name compared to name and a bug occurres and generates 2 different streams one with the original name and other with the external name, also solves the problem related with getting the correct stream status.
Signed-off-by: Domene Esteban, Nil
<nildomenee@gmail.com>
Fixes #1751 
I have:
Tested locally using Localstack creating multiple Streams with different configurations.
=> fix(kinesis): fix bug related with the use of external-name

pkg/clients/database/rds.go, pkg/clients/database/rds_test.go
Adds tag list sorting before comparing them in `RDSInstance`.
Fixes #494
Fixes #1436
I have:
Unit tests
=> fix(database): Sort tags before compare

apis/kafka/v1alpha1/custom_types.go, apis/kafka/v1alpha1/referencers.go, apis/kafka/v1alpha1/zz_generated.resolvers.go
Adds a custom resolver for `spec.forProvider.configurationInfo.arn` that returns the actually reqired ARN of the configuration instead of the external name.
Fixes #1673
I have:
n.a.
=> fix(kafka): Resolve configuration ARN instead of external name

pkg/controller/kms/key/setup.go, pkg/utils/policy/compare_test.go, pkg/utils/policy/parse.go, pkg/utils/policy/testdata/Issue1892_a.json, pkg/utils/policy/testdata/Issue1892_a_min.json, pkg/utils/policy/testdata/Issue1892_b.json, pkg/utils/policy/testdata/Issue1892_b_min.json
Avoid unnecessary JSON diffs for KMS key policies by parsing them into a resource policy struct before comparing them, similar to #1757.
Fixes #1892
I have:
Unit tests
=> fix(kms): Parse key policies before compare

pkg/controller/mq/broker/setup.go
Adds a small check that unset `EncryptionOptions` in `preCreate` if engine type `RabbitMQ`.
Fixes #1643
I have:
n.a.
=> fix(mq): Do not set EncryptionOptions for RabbitMQ

pkg/clients/rds/common.go, pkg/clients/rds/common_test.go, pkg/utils/kube/context_namespace.go
This adds a function that infers the namespace of the RDS password cache secret from the following locations (in order):
1. `POD_NAMESPACE` env var
2. `/var/run/secrets/kubernetes.io/serviceaccount/namespace` file
3. fallback to `crossplane-system`
Until now `crossplane-system` was the hardcoded value.
Fixes #1834
Please note that this might cause a regeneration of passwords if the provider is running in another namespace than `crossplane-system`, but, due to the change, is now looking for the secret in another namespace where it does not exist.
I have:
n.a.
=> fix(rds): Infer cache secret namespace from pod environment

.github/workflows/ci.yml
Removes the `codeql` check that was introduced with #1888 because it takes a very long time to run and we are not using the results anywhere.
I have:
n.a.
=> chore(ci): Disable codeql step

apis/database/v1beta1/rdsinstance_types.go, package/crds/database.aws.crossplane.io_rdsinstances.yaml, pkg/clients/database/rds.go, pkg/clients/database/rds_test.go
Only pass `spec.forProvider.availabilityZone` during update calls if `spec.forProvider.multiAZ` is false.
Fixes #1870
I have:
Unit tests
=> fix(database): Ignore AvailabilityZone if MultiAZ is set

pkg/controller/autoscaling/autoscalinggroup/setup.go
=>  fix(autoscaling): fix diff issue of auto scaling group

apis/kafka/generator-config.yaml, apis/kafka/v1alpha1/zz_cluster.go, apis/kafka/v1alpha1/zz_generated.deepcopy.go, package/crds/kafka.aws.crossplane.io_clusters.yaml, pkg/controller/kafka/cluster/setup.go
For `kafka.Cluster`:
- adaptation in `getClusterPolicyState` to allow triggering deletion of `ClusterPolicy` when user sets `clusterPolicy: null` in claim 
- ~~cache~~ the `CurrentVersion` of the `ClusterPolicy` to enable making consecutive `PutClusterPolicy` calls
EDIT: add + use new field `Status.AtProvider.ClusterPolicyVersion` to "cache" the `CurrentVersion` of the `ClusterPolicy` for update. This way user has also access to that data, e.g. for making manual  `PutClusterPolicy` calls.
Fixes #1920
I have:
manually
=> fix(kafka/cluster): clusterpolicy update + delete

apis/acm/v1alpha1/certificate_types.go, apis/acm/v1beta1/certificate_types.go, package/crds/acm.aws.crossplane.io_certificates.yaml
Just fixing a spelling mistake that was bothering me whilst I was looking through the provider docs.
Fixes #
I have:
=> fix(acm): correct description for dvo

go.mod, pkg/controller/efs/accesspoint/setup.go
Small refactoring that uses the native `context.Context` instead of the stub in `golang.org/x/net`.
I have:
n.a.
=> refactor(efs): Use native context instead of golang.org/x/net/context

go.mod, go.sum
Bumps crossplane-runtime to `v1.13.0` (identical to `v0.20.1`).
I have:
n.a.
=> chore: Bump crossplane-runtime to v1.13.0

pkg/controller/rds/dbinstance/setup.go
In isUpToDate for rds dbinstance it is checked if tags need to be added or removed. Currently the property "tagsChanged", that is amongst other checks used to determine if the dbinstance has changed, is only set to true if both tags get added AND removed. I changed this to set the value to true if tags need to be added OR removed.
Fixes #
I have:
Tested locally
=> fix: tags change if added or removed

pkg/utils/connect/aws/config.go
Use a shared client/credentials to avoid calling AssumeRoleWithWebIdentity for each reconcile.
aws.Config (v1/v2) is thread safe and checks token expiry/handles renewal. To handle 
Fixes #828
I have:
Ran for one week. Creating PR for discussion, how can we avoid a global variable?
As you can see below we get a significant reduction in the number of API calls to AWS:
=> fix: Avoid AssumeRoleWithWebIdentity for each reconcile

pkg/controller/ec2/address/controller.go, pkg/controller/ec2/instance/controller.go, pkg/controller/ec2/subnet/controller.go, pkg/controller/ec2/volume/setup.go, pkg/controller/ec2/vpc/controller.go, pkg/controller/ec2/vpcendpoint/setup.go, pkg/controller/eks/addon/setup.go, pkg/controller/elbv2/target/controller.go, pkg/controller/firehose/deliverystream/setup.go, pkg/controller/globalaccelerator/endpointgroup/setup.go, pkg/controller/kinesis/stream/setup.go, pkg/controller/mq/broker/setup.go, pkg/controller/mq/user/setup.go, pkg/controller/prometheusservice/alertmanagerdefinition/setup.go, pkg/controller/prometheusservice/rulegroupsnamespace/setup.go, pkg/controller/prometheusservice/workspace/setup.go, pkg/controller/ram/resourceshare/setup.go
The default behaviour of a controller is to use
`managed.NewNameWithExternalName`. Controllers need to pass `managed.WithInitializers()` to change the behaviour.
After the runtime upgrade and tagging removal, some of the empty `managed.WithInitializers()` got removed resulting in a different behaviour.
Readd them restore the previous behaviour.
Partially reverts #1935.
I have:
No, testing was performed. Just comparison to the previous version.
=> fix: Readd empty initializers after runtime update

pkg/clients/iam/role.go, pkg/clients/iam/role_test.go
Fixes # https://github.com/crossplane-contrib/provider-aws/issues/1945
Stop considering AWS initialized fields in diff. 
Let me know if there's another way that's more idiomatic to Crossplane.
I have:
I've added a test to cover this scenario.
=> fix(iam): Stop considering AWS initialized fields in diff

pkg/controller/mq/user/setup.go
Uses the external name instead of the metadata.name for `User`. Also adds the `managed.NewNameAsExternalName` initializer to stick with the existing behaviour.
I have:
=> fix(mq): Use external name instead of metadata.name for user

pkg/controller/glue/crawler/setup.go
With the aws sdk bump from  https://github.com/crossplane-contrib/provider-aws/pull/1523 `glue.Crawler` got a new parameter/field `lakeFormationConfiguration`, which needs to be lateinit to avoid an update-loop.
I have:
manually
=> fix(glue/crawler): lateinit lakeFormationConfiguration

pkg/clients/database/fake/fake.go, pkg/clients/database/rds.go, pkg/clients/database/rds_test.go, pkg/controller/database/rdsinstance/rdsinstance.go, pkg/controller/database/rdsinstance/rdsinstance_test.go
for `database.RDSInstance`:
- fix `isUpToDate()` logic to trigger update on tag-only-change (used cache scheme/solution from `rds.DBInstance`)
- add `RemoveTagsFromResource()` from AWS API to `update()` (removing tags was apparently not possible before...)
- adapt unit-tests
Fixes #1962
I have:
manually (update tag-only, update other db parameter)
=> fix(database): tag-only-change triggers update + add RemoveTag call

pkg/controller/rds/dbcluster/setup.go, pkg/controller/rds/dbcluster/setup_test.go
Adds the diff check for `spec.forProvider.serverlessV2ScalingConfiguration` to `isUpToDate.
I have:
Unit tests
=> fix(rds/dbcluster): Add check for ServerlessV2ScalingConfiguration

apis/rds/generator-config.yaml, apis/rds/v1alpha1/zz_db_instance.go, apis/rds/v1alpha1/zz_generated.deepcopy.go, package/crds/rds.aws.crossplane.io_dbinstances.yaml, pkg/controller/rds/dbinstance/setup.go
This prevents the controller from sending `VPCSecurityGroupIDs` during update or create for DB instances that belong to a DB cluster.
Fixes https://github.com/crossplane-contrib/provider-aws/issues/1799
I have:
Manually
=> fix(rds/dbinstance): Ignore VPCSecurityGroupIDs for cluster instances

pkg/controller/lambda/function/setup.go, pkg/controller/lambda/function/setup_test.go
This removes the nil check in the function controller to send an empty array for VPC config and environment if the properties are nil.
Fixes https://github.com/crossplane-contrib/provider-aws/issues/1872
I have:
Manually and unit tests.
=> fix(lambda): Push empty environment of vpc config if nil

pkg/clients/sqs/queue.go, pkg/clients/sqs/queue_test.go, pkg/clients/sqs/testdata/queue_policy.json, pkg/clients/sqs/testdata/queue_policy.min.json, pkg/clients/sqs/testdata/queue_policy2.json, pkg/controller/sqs/queue/controller.go
Parse JSON policies and use `cmp.Diff` instead of plain string comparison.
I have:
=> fix(sqs): Structured policy compare

pkg/controller/s3/bucket/notificationConfig.go
Adds a call of `PutBucketNotificationConfiguration` that resets the configuration back to empty if the spec field is nil.
Fixes https://github.com/crossplane-contrib/provider-aws/issues/1140
I have:
=> fix(bucket): Reset notification configuration

pkg/clients/eks/nodegroup.go, pkg/clients/eks/nodegroup_test.go
Adds a check and update mechanic for EKS nodegroup taints to the controller that works similar to tags adding / removal.
Fixes https://github.com/crossplane-contrib/provider-aws/issues/1952
I have:
Unit tests
=> fix(eks): Update NodeGroup taints

apis/iam/v1beta1/rolepolicy_types.go, package/crds/iam.aws.crossplane.io_rolepolicies.yaml
Explicitly sets the type for `spec.forProvider.document` in `iam.RolePolicy`.
Fixes https://github.com/crossplane-contrib/provider-aws/issues/1990
I have:
n.a.
=> fix(iam): Add schema type to RolePolicy document

cluster/local/integration_tests.sh
=> chore(ci): Fix e2e tests

pkg/controller/database/rdsinstance/rdsinstance.go
for `database.rdsinstance`:
- implement the same logic to skip the isUpToDate()-check on deletion as https://github.com/crossplane-contrib/provider-aws/pull/1979 did for the ACK controllers
This fixes e.g. a common case of a missing k8s secret blocking the deletion, if it was deleted from the cluster before the MR.
I have:
manually
=> fix(database): skip isUpToDate on deletion

pkg/controller/database/rdsinstance/rdsinstance.go, pkg/controller/database/rdsinstance/rdsinstance_test.go
in rdsInstance when running an update always set `ResourceCredentialsSecretUserKey` in the ConnectionDetails if masterUsername exists.
Fixes #1999
I have:
Created an RDSInstance, Deleted it when deletionPolicy = Orphan.
Re-added the RDSInstance, checked the secret contained `username`
=> fix(rdsinstance): Updates will now set ResourceCredentialsSecretUserKey in ConnectionDetails if masterUsername is set

pkg/controller/efs/mounttarget/setup.go
Adds `WithPollInterval` to `efs.MountTarget` so that the requeue-after time uses the --poll argument override. 
Fixes #2014
I have:
minor change, passed all existing tests. 
=> fix(efs): Add poll-interval to EFS mount target

pkg/controller/s3/bucket/taggingConfig.go, pkg/controller/s3/bucket/taggingConfig_test.go
Ignore s3 bucket systemd tags(with prefix `aws:`) on observed resource side because these cannot be updated/deleted, otherwise it cause an error
Example: the controller takes control over existing s3 bucket which has systemd tag(s) and tries to reconcile tag set with desired state which doesn't include tags at all or regular tags only. As result the controller gets an error due it is impossible to delete system tag
I have:
- manual testing
- unit tests
=> fix(s3 bucket): Ignore AWS system tags

apis/ec2/manualv1alpha1/instances_types.go, apis/ec2/manualv1alpha1/zz_generated.deepcopy.go, package/crds/ec2.aws.crossplane.io_instances.yaml, pkg/clients/ec2/instance.go, pkg/clients/ec2/instance_test.go, pkg/controller/ec2/instance/controller.go
This ensures that when tags change, the EC2 instance reconciles the update. Previously the ec2 instance controller supported updating tags via `CreateTags` but did not perform reconciliation when tags changed as it was not included in the check for if the EC2 instance was up to date.
However, the way `Update` is currently implemented had the implicit assumption that the EC2 instance must be stopped for all updates, which is true for all the ModifyInstanceAttribute calls, however, tags can be applied at runtime. This changes the logic of the controller to (1) include the instance attributes in the instance observations, (2) only attempt to modify instance attributes if the observation does not match the spec.
I have:
This code has been tested on and deployed in our own fork used in …
=> ec2: include attributes in instance observation, fix reconciling tags

pkg/controller/ec2/securitygroup/controller.go
Resource tags are used to ensure that only IAM roles with the right access can modify the resources. This ensures that the security groups will have the right tags from creation time. Without this change, IAM policy based on tags may fail to run subsequent steps of security group creation.
This change makes security groups created with the tags rather than waiting for the first observation / update to add tags.
I have:
Tested on our own internal production fork and staging environments.
=> ec2: Create security group with tags in the spec

pkg/clients/ec2/instance.go, pkg/controller/ec2/instance/controller.go
The EC2 instance controller synchronously makes several DescribeInstanceAttribut calls to the EC2 API and does not use the results. This slows down the reconcile time for a single observation.
This removes the API calls for attributes that are returned in `RunInstances`.
I have:
Tested in staging/production in our fork. See drastic decrease in reconcile time for the ec2 instance resource.
Related to #2029
=> Reduce ec2 instance controller API calls for an observation

pkg/controller/rds/dbinstance/setup.go
AWS seems to be giving different responses for IOPS/StorageThroughput (either 0 or nil) depending on whether the instance was created as `gp2` or modified from another storageType (e.g. `gp3`) to `gp2`,
This changes their `isUptoDate()` checks to consider both 0 and nil to be equivalent.
Also I used the opportunity and added missing parameters to the built diff for the logs.
I have:
manually
=> fix(dbinstance): in isUpToDate consider 0 and nil to be equal for iops/storageThroughput

pkg/clients/resourcerecordset/resourcerecordset.go, pkg/clients/resourcerecordset/resourcerecordset_test.go
For records that have MultiValueAnswer and SetIdentifier fields.
ResourceRecordSets with MultiValueAnswer and SetIdentifier fields
were always considered out of date and were upserted on every reconciliation.
I have:
- Additional test case
- Manual integration testing
=> Fix changes detection for route53.ResourceRecordSet

pkg/clients/resourcerecordset/resourcerecordset.go
Otherwise AWS returns ALL routes with name >= requested one.
Fetching unnecessary records results in slow & inefficient reconciliations
when account has a lot or route53 resords.
I have:
- Manual integration testing
=> Call route53.ListResourceRecordSets with MaxItems = 1

pkg/controller/ecs/service/setup.go
Currently, ECS Service resource is only taken into consideration the `.Status` field to decide on the readiness of the Crossplane resource.
I think this is an overlook, and Crossplane should also take into consideration the `DesiredCount/RunningCount`, since it is part of the input Spec. Returning _ready_ based only on the `.Status` might result in returning to the client a _ready_ state when in fact, no tasks are running yet.
Before wrapping up the PR with tests, I would like to get some feedback from you to undertstand if you agree with this change or not. 
I have:
Thanks.
=> fix: take into consideration the DesiredCount/RunningCount for resource readiness

apis/acm/v1alpha1/certificate_types.go, apis/acm/v1alpha1/zz_generated.deepcopy.go, apis/acmpca/v1alpha1/certificateauthority_types.go, apis/acmpca/v1beta1/certificateauthority_types.go, apis/apigatewayv2/v1alpha1/referencers.go, go.mod, go.sum, pkg/clients/acmpca/certificateauthority.go, pkg/clients/acmpca/certificateauthority_test.go, pkg/controller/acmpca/certificateauthority/controller_test.go
This removes the import statements in `apis` for `github.com/aws/*` and replaces all imported types with plain strings.
It allows importing `apis` in other Go modules without the necessity to import AWS SDK dependencies.
It makes no breaking changes since the imported types where only just string type aliases.
I have:
n.a.
=> refactor(apis): Remove AWS imports

pkg/controller/s3/bucket/taggingConfig.go, pkg/controller/s3/bucket/taggingConfig_test.go
Adds check to catch when the AWS S3 API throws a `NoSuchTagSet` error code if a bucket has no tag set associated with the bucket, and return a nil TagSet.
Fixes #2052
I have:
minor change, passed all existing and new tests. 
=> fix(S3): Add check for S3 tagging api error code when empty TagSet

pkg/clients/iam/role.go, pkg/clients/iam/role_test.go, pkg/controller/iam/role/controller_test.go, pkg/utils/policy/compare.go
To not trigger update event and update role in AWS when AWS changes formatting in policy document.
Policy checker in `pkg/utils/policy/old` considers that policies are different if one of them has `"Action": "x"` and another one has `"Action": ["x"]`. This PR fixes it.
I have:
- existing and new test cases
=> Use new policy checker for iam.roles

go.mod, pkg/controller/ec2/instance/controller.go, pkg/controller/ec2/instance/controller_test.go
Instance observation makes 4 AWS API calls. Running this calls concurrently reduces reconciliation time. Here is 0.99 quantile of reconciliation duration
I have:
with existing unit tests
=> fix(ec2): Call describe-instance API concurrently

pkg/clients/iam/role_test.go, pkg/utils/policy/compare_test.go, pkg/utils/policy/convert.go, pkg/utils/policy/parse_test.go, pkg/utils/policy/testdata/PrincipalsOrder_a.json, pkg/utils/policy/testdata/PrincipalsOrder_b.json, pkg/utils/policy/testdata/PrincipalsOrder_c.json, pkg/utils/policy/types.go, pkg/utils/policy/types_test.go
AWS returns principals items in a random order so provider-aws should ignore it to not consider policies changed.
I have:
- Existing and new tests
=> Ignore principals order when comparing policies

pkg/controller/s3/bucket/convert/converter_types.go, pkg/controller/s3/bucket/convert/zz_converter.go, pkg/controller/s3/bucket/notificationConfig.go
for `Bucket.s3` :
- add sanitize functions for the observed `NotificationConfigurations` `LambdaFunctionConfigurations` and `TopicConfigurations` (copying the same logic behavior as for `QueueConfigurations`)
because for these AWS also returns the `Filter.Key.FilterRules.Name` as "Prefix"/"Suffix" but expects "prefix"/"suffix":
Fixes #2013
I have:
manually
=> fix(bucket): also sanitize observed FilterRules.Name of lambda and topic configs

pkg/clients/rds/common.go, pkg/controller/rds/dbinstance/setup.go
Currently, when changing the engine version of a rds db instance, the new version is not send to aws. This leads to a) the database does not get updated and b) an update loop, as the isUpToDate call always returns false.
Fixes #
I have:
=> fix: add engine version for dbinstance update

.github/workflows/ci.yml, .gitmodules, Makefile, cluster/local/integration_tests.sh
- Update build module to use the latest supported version and change the up version that is compatible with docker > 1.25
- `vendor` and ` vendor.check` were deprecated, updated the CI to use the new version `modules.download` and ` modules.check` 
```sh
Go Targets:
modules.download Download Go modules.
modules.check    Fail the build if Go modules have changed.
``` 
I have:
- Build in MacOS with Docker 
- Run actions 
=> chores: Update build submodule and up up cli version

pkg/controller/lambda/function/setup.go
for `Function.lambda`:
- set MR to `Ready: True` when Function is in `state: Inactive` when` stateReason: Idle` (AWS sets Function to Idle after 14 days: https://docs.aws.amazon.com/lambda/latest/dg/snapstart-activate.html#snapstart-function-states)
- for all other cases keep setting MR to `Ready: False` when Function is in `state: Inactive`
with previous/current behavior the resource is set to `Ready: False` when idle 
The previous/current handling differs from the way Upbound Function.lambda behaves. This change aims to adapt this.
I have:
manually
=> fix(lambda/function): resource is ready when function is inactive due to idle

pkg/controller/ecs/service/setup.go
Fixes
The value of `DesiredCount` and `RunningCount` are equal, so the `Condition` should be `Available`
I have:
=> fix(ecs): DesiredCount/RunningCount check

cmd/provider/main.go
Closes https://github.com/crossplane-contrib/provider-aws/issues/2081
I have:
=> fix: Explicitly provide no-op logger by default

apis/database/v1beta1/rdsinstance_types.go, pkg/clients/database/rds.go, pkg/clients/database/rds_test.go
for `RDSInstance.database`:
- allow empty array as value in `spec.paramaters.enableCloudwatchLogsExports`
- fix isUpTodate-check for `EnableCloudwatchLogsExports`
I have:
na
=> fix(database): allow empty array as value in enableCloudwatchLogsExports + fix isuptodate check

pkg/clients/eks/eks.go
Fixes the diff of subnetIds.
Fixes:
```
cannot update EKS cluster configuration: InvalidParameterException:
No changes needed for the provided vpc config.
```
I have:
- Reordered the subnetIds to create the mentioned error, tested if it appears with the fix
=> fix(eks): SubnetIds diff

pkg/controller/cloudfront/distribution/setup.go, pkg/utils/pointer/pointer.go
This is Fixes #1210, the issue is arised due to the usage of the function `ToIntAsInt64` returns nil when the value is `0`. Since the AWS API for CloudFront expects an actual "Quantity: 0" value, returning nil makes the API complain with something like:
```
create failed: cannot create Distribution in AWS: InvalidParameter: 10
validation error(s) found.
- missing required field,
CreateDistributionInput.DistributionConfig.CacheBehaviors.Quantity.
- missing required field,
CreateDistributionInput.DistributionConfig.CustomErrorResponses.Quantity.
...
```
This creates the utility function `ToIntAsInt64Zero` to allow the value `0` to be converted, thus fulfilling the requirement for the CloudFront API to have a real value, even if is zero.
I have:
Tested it in a productive environment where …
=> fix(cloudfront): Send zero instead of nil during create/update

apis/ecs/generator-config.yaml, apis/ecs/v1alpha1/zz_generated.deepcopy.go, apis/ecs/v1alpha1/zz_service.go, package/crds/ecs.aws.crossplane.io_services.yaml, pkg/controller/ecs/service/setup.go
Adds the list of task ARNs to the service status.
I have:
- Manual
=> feat(ecs): Add taskArns to service status

apis/s3/v1beta1/lifecycleConfiguration_types.go, apis/s3/v1beta1/replicationConfiguration_types.go, package/crds/s3.aws.crossplane.io_buckets.yaml
Hello,
It's currently not possible to create a bucket with `GLACIER_IR` as a replicationConfiguration storageClass:
```
The Bucket "my-test-bucket-mxapp-bucket" is invalid: spec.forProvider.replicationConfiguration.rules[0].destination.storageClass: Unsupported value: "GLACIER_IR": supported values: "STANDARD", "GLACIER", "STANDARD_IA", "ONEZONE_IA", "INTELLIGENT_TIERING", "DEEP_ARCHIVE"
```
As per https://docs.aws.amazon.com/AmazonS3/latest/API/API_Transition.html and https://docs.aws.amazon.com/AmazonS3/latest/API/API_NoncurrentVersionTransition.html GLACIER_IR should be part of the NoncurrentVersionTransition and Transition types for the lifecycle and replication configurations.
I have:
Thanks for reviewing, please let me know if something is missing for the MR.
=> fix(s3): Add missing GLACIER_IR storage type in replication and lifecycle Configuration types

pkg/utils/connect/aws/config.go
Fixes web identity usage when using providerconfig.spec.credentials.source InjectedIdentity.
Sample config:
```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
name: default
spec:
credentials:
source: InjectedIdentity
```
Sample error message when not providing a web identity token file, e.g. via AWS_WEB_IDENTITY_TOKEN_FILE, in the provider-aws pod with InjectedIdentity:
```
failed to describe DBParameterGroup: WebIdentityErr: failed fetching WebIdentity token: 
caused by: WebIdentityErr: unable to read file at 
caused by: open : no such file or directory
```
This fix enables (config v1) services to use any credential provider via the default credential provider chain.
As a result v1 services can be used with container credential providers like pod identity.
I have: …
=> fix(sdk-config): drop web identity usage from v1 default config

OWNERS.md
This PR is just a small update from #2138 to correct a typo in the github user name for https://github.com/christophrj 
I have:
I've verified the link goes to https://github.com/christophrj 😇 
=> chore: Update OWNERS.md with correct christophrj

pkg/clients/ecs/taskdefinitionfamily/task_definition_family.go, pkg/controller/ecs/service/setup.go
Fixes:
- Updating Volumes in TaskDefinitionFamily (LateInit)
- Diffs on TaskDefinitionFamily/ECS Service
I have:
- Updating Environment on TaskDefinitionFamily and check if update loop occurs
- Updating Volumes on TaskDefinitionFamily and check if update loop occurs
=> fix(ecs): Fix LateInitialize & Slice diffs

pkg/controller/transfer/server/custom.go, pkg/controller/transfer/server/setup.go
=> feat(transfer): add vpcendpoint dns entries to connection secrets

pkg/clients/database/rds.go, pkg/clients/database/rds_test.go, pkg/controller/database/rdsinstance/rdsinstance.go, pkg/controller/database/rdsinstance/rdsinstance_test.go
for RDSInstance.database:
- do not request Modify, when ModifyDBInstanceInput only includes `DBInstanceIdentifier` and the Modify-Flags(`AllowMajorVersionUpgrade`, `ApplyImmediately`)
When user only changed Tags, this could lead to getting the MR stuck, if `ApplyImmediately: false` was set.
AWS then blocks the request and the whole update-fails:
> "update failed: cannot modify RDS instance: api error InvalidParameterCombination: No modifications were requested"
This rarely happened, due to AWS curiously not rejecting empty Modify-Calls with `ApplyImmediately: true`.
I have:
manually
=> fix(rdsinstance.database): do not send empty modify-calls

apis/database/v1beta1/rdsinstance_types.go, package/crds/database.aws.crossplane.io_rdsinstances.yaml, pkg/clients/database/rds.go, pkg/clients/database/rds_test.go, pkg/controller/database/rdsinstance/rdsinstance_test.go
for `RDSInstance.database`:
- remove lateinit overwrite of `engineVersion` when only major is set
- this is no longer needed since we check in isUpToDate the `engineVersion` in detail (considering major and minor)
- now fill  - already existing status field... - with observed `engineVersion` in AWS
- change printcolumn to `.status.atProvider.engineVersion`
Fixes:
for setups where MRs were applied automatically (e.g. via Composition/XR) the `spec.forProvider.engineVersion` would constantly flicker due to this lateinit part, when user set only the major version (which is valid by AWS; and makes sense in combination with `autoMinorVersionUpgrade`)
I have:
manually
=> fix(rdsinstance.database): do not overwrite engineVersion if only major was set + add engineVersion to observe

.github/workflows/backport.yml, .github/workflows/ci.yml, .github/workflows/commands.yml, .github/workflows/promote.yml, .github/workflows/tag.yml, pkg/clients/ec2/securitygroup_diff.go, pkg/controller/mq/configuration/utils/xmlparse.go, pkg/utils/pointer/pointer.go, pkg/utils/policy/types.go
Bump linter to v1.63.4.
Keep go.mod at go 1.21 because it is not necessary to bump
Depends on https://github.com/crossplane-contrib/provider-aws/pull/2154
Fixes #
I have:
=> chore(ci): Use Go 1.23.5 to build images

.github/workflows/ci.yml, pkg/clients/ec2/securitygroup_diff.go, pkg/controller/mq/configuration/utils/xmlparse.go, pkg/utils/pointer/pointer.go, pkg/utils/policy/types.go
Signed-off-by: Simon Wakenhut <Simon.Wakenhut-extern@deutschebahn.com>
(cherry picked from commit 4dd45e7)
Manual backport of https://github.com/crossplane-contrib/provider-aws/pull/2155
I have:
=> [Backport release-0.51] chore(ci): Use Go 1.23.5 to build images

pkg/controller/lambda/permission/policy.go, pkg/controller/lambda/permission/policy_test.go
When using roles as principle in permissions.lambda the key is "AWS", which got lost when unmarshaling the returned policy.
I have:
Ran provider locally against AWS and added unittest
=> fix(lambda): Policy parsing for permissions when using roles as principles

apis/secretsmanager/generator-config.yaml, apis/secretsmanager/v1beta1/zz_generated.deepcopy.go, apis/secretsmanager/v1beta1/zz_secret.go, package/crds/secretsmanager.aws.crossplane.io_secrets.yaml, pkg/controller/secretsmanager/secret/zz_conversions.go
- added versionids to secretsmanager.secret in order to facilitate migration cases
I have:
- built new version, manually tested that status is showing
=> chore(secretmanager): add versionids to status

pkg/clients/ecs/tags.go, pkg/controller/ecs/service/setup.go
for `Service.ecs`:
- add logic to allow updating Tags
also fixes: Service MR being stuck in update-loop, when tags in claim change
I have:
manually
=> fix(ecs/service): add functionality to update tags

pkg/controller/ec2/instance/controller.go, pkg/controller/ec2/instance/controller_test.go
This PR fixes an issue in the EC2 instance controller where an empty tag list causes the `CreateTags` API call to fail, preventing the instance’s external name from being set. 
Currently, `Create` always attempts to call `CreateTags`, even when no tags are provided. However, AWS rejects `CreateTags` with an empty tag list, returning an `InvalidParameterValue`.
Since this error occurs before `SetExternalName` is called, the Crossplane reconciliation loop fails to detect that the instance was already created and keeps creating new instances in an infinite loop.
I have:
I have added a SuccessfulWithNoTags test to explicitly check that CreateTags is not called when no tags are provided.
=> fix(ec2.instance): permit to create instance with no tags

pkg/controller/efs/filesystem/setup.go
Fixes #2135
This change enables the update of Throughputmode and BackupPolicy. 
I have:
1. apply efs1.yml:
```yaml
kind: FileSystem
metadata:
name: greattestingfilesystem
spec:
deletionPolicy:  Delete
forProvider:
backup:            false
encrypted:         false
performanceMode:  generalPurpose
region:            eu-west-3
throughputMode:  elastic
name: aws-community-provider
```
2. apply efs2.yml
```yaml
apiVersion: efs.aws.crossplane.io/v1alpha1
kind: FileSystem
metadata:
name: greattestingfilesystem
spec:
deletionPolicy:  Delete
forProvider:
backup:            true
encrypted:         true
performanceMode:  generalPurpose
region:            eu-west-3
throughputMode:  bursting
name: aws-community-provider
```
3. confirm that the throughputmode and …
=> fix(efs): Adjusted Filesystem Update

apis/database/v1beta1/rdsinstance_types.go, apis/rds/generator-config.yaml, apis/rds/v1alpha1/zz_db_cluster.go, apis/rds/v1alpha1/zz_db_instance.go, apis/rds/v1alpha1/zz_generated.deepcopy.go, package/crds/database.aws.crossplane.io_rdsinstances.yaml, package/crds/rds.aws.crossplane.io_dbclusters.yaml, package/crds/rds.aws.crossplane.io_dbinstances.yaml, pkg/clients/database/rds.go, pkg/controller/rds/dbcluster/setup.go, pkg/controller/rds/dbinstance/setup.go
- added kmsKeyId to  status of dbinstance.rds, dbcluster.rds & rdsinstance.database APIs; 
- displays if storageEncrypted is enabled;
Fixes #
I have:
- built provider, tested with all three MR types
=> feat(rds): add kmsKeyId to status

pkg/clients/ec2/routetable.go, pkg/clients/ec2/routetable_test.go, pkg/clients/ec2/tags_v1beta1.go
This PR reverts partially reverts the changes of 138b8cf to not detect changes when only the order of the tags change between what is returned by AWS and what is being submitted on the `RouteTable` CR.
The revert of this change will avoid detecting order-related differences because the `SortTagsV1Beta1(targetCopy.Tags, in.Tags)` function changes the order of `targetCopy.Tags` and `in.Tags` by reference which enables a proper comparison afterwards in:
`jsonPatch, err := jsonpatch.CreateJSONPatch(*currentParams, targetCopy)`
The `currentParams.Tags` will have the same tag order of `in.Tags` from the `LateInitializeRT(currentParams, &in)`.
Note: the `CompareTags` added in 138b8cf is effectively doing nothing as the result is not being used and nothing is changed by reference.
Fixes #2196
I …
=> fix(ec2): Partial revert of 138b8cf to fix issue crossplane-contrib#2196

examples/ecs/service.yaml, pkg/controller/ecs/service/setup.go
When using host network mode users do not need to pass the network config , but the codes passes and empty object thus having issues creating a service with no network configuration , So when user is not passing any network configuration I removed if it is an empty object
Fixes #
This fixes https://github.com/crossplane-contrib/provider-aws/issues/2233
Added in the new examples I used to test the code , service are getting created without the network configuration now 
=> fix(ecs): issue with empty network configuration parameter
