Jenkinsfile
This PR is attempting to get official builds running on Jenkins in a new stack-aws pipeline: https://jenkinsci.upbound.io/blue/organizations/jenkins/crossplane%2Fstack-aws/activity
We'll want to have the same full functionality that the main crossplane repo has, such as SonarCloud checks and Integration tests, but I'm stripping the Jenkinsfile down for now just to get the build pipeline off the ground.
=>  Get official builds running for stack-aws repo

Gopkg.lock, config/crd/cache.aws.crossplane.io_replicationgroupclasses.yaml, config/crd/cache.aws.crossplane.io_replicationgroups.yaml, config/crd/compute.aws.crossplane.io_eksclusterclasses.yaml, config/crd/compute.aws.crossplane.io_eksclusters.yaml, config/crd/database.aws.crossplane.io_rdsinstanceclasses.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml, config/crd/identity.aws.crossplane.io_iamrolepolicyattachments.yaml, config/crd/identity.aws.crossplane.io_iamroles.yaml, config/crd/network.aws.crossplane.io_internetgateways.yaml, config/crd/network.aws.crossplane.io_routetables.yaml, config/crd/network.aws.crossplane.io_securitygroups.yaml, config/crd/network.aws.crossplane.io_subnets.yaml, config/crd/network.aws.crossplane.io_vpcs.yaml, config/crd/storage.aws.crossplane.io_dbsubnetgroups.yaml, config/crd/storage.aws.crossplane.io_s3bucketclasses.yaml, config/crd/storage.aws.crossplane.io_s3buckets.yaml, pkg/controller/aws/cache/claim.go, pkg/controller/aws/compute/claim.go, pkg/controller/aws/rds/claim.go, pkg/controller/aws/s3/claim.go
See https://github.com/crossplaneio/crossplane-runtime/pull/24 for context. That PR must first be merged, and then this PR updated to depend on the latest build, before this PR can be merged.
Reviewers, please double check the kinds I've provided to each predicate to ensure they make sense; it's especially easy to mix up `FooGroupVersionKind` with `FooClassGroupVersionKind`.
I have:
=> Fix support for static provisioning

Gopkg.lock, pkg/controller/aws/cache/claim.go, pkg/controller/aws/compute/claim.go, pkg/controller/aws/rds/claim.go, pkg/controller/aws/s3/claim.go
=> claim predicates: remove hasdirectclassreferencekind in favor of ismanagedkind

Jenkinsfile, Makefile, cluster/local/helm-rbac.yaml, cluster/local/integration_tests.sh
Same as crossplaneio/stack-azure#29.
Fixes crossplaneio/crossplane#759
I have:
=> integration tests: initial implementation

go.mod, go.sum, pkg/controller/cache/claim.go
See https://github.com/crossplaneio/crossplane-runtime/pull/55
I have:
=> Update crossplane-runtime to fix static provisioning

config/stack/manifests/resources/dbsubnetgroup.ui-schema.yaml, config/stack/manifests/resources/ekscluster.ui-schema.yaml, config/stack/manifests/resources/eksclusterclass.ui-schema.yaml, config/stack/manifests/resources/iamrole.ui-schema.yaml, config/stack/manifests/resources/iamrolepolicyattachment.ui-schema.yaml, config/stack/manifests/resources/internetgateway.ui-schema.yaml, config/stack/manifests/resources/provider.ui-schema.yaml, config/stack/manifests/resources/rdsinstance.ui-schema.yaml, config/stack/manifests/resources/rdsinstanceclass.ui-schema.yaml, config/stack/manifests/resources/replicationgroup.ui-schema.yaml, config/stack/manifests/resources/replicationgroupclass.ui-schema.yaml, config/stack/manifests/resources/routetable.ui-schema.yaml, config/stack/manifests/resources/s3bucket.ui-schema.yaml, config/stack/manifests/resources/s3bucketclass.ui-schema.yaml, config/stack/manifests/resources/securitygroup.ui-schema.yaml, config/stack/manifests/resources/subnet.ui-schema.yaml, config/stack/manifests/resources/vpc.ui-schema.yaml, config/stack/samples/install.stack.yaml, config/stack/samples/local.install.stack.yaml
Per the [Stack UI Schema Status Spec](https://github.com/crossplaneio/crossplane/blob/4cf353351fc7fa3d58210fc790a6b30e7f74309b/design/one-pager-stack-status-spec.md#design), resources provided by a Stack may report to UI tools the status of the provisioned resource.
One approach to hint the UI, it a so-called [fallback option](https://github.com/crossplaneio/crossplane/blob/4cf353351fc7fa3d58210fc790a6b30e7f74309b/design/one-pager-stack-status-spec.md#fallback-option).  This approach defers to a "READY" additionalPrinterColumn defined in the CRD. Use of this approach would not require a `ui-schema.yaml` but resources in this Stack do not report the necessary READY column.
Because this Stack takes advantage of the Crossplane Runtime's Conditioned Status pattern, there is a predictable path …
=> stacks: report Ready status for all managed types using ui-schema

apis/compute/v1alpha2/types.go, apis/database/v1alpha2/dbsubnetgroup_types.go, apis/database/v1beta1/rdsinstance_types.go, apis/identity/v1alpha2/iamrolepolicyattachment_types.go, apis/network/v1alpha2/internetgateway_types.go, apis/network/v1alpha2/routetable_types.go, apis/network/v1alpha2/securitygroup_types.go, apis/network/v1alpha2/subnet_types.go
https://github.com/golang/go/wiki/CodeReviewComments#error-strings
Updating these to match the Azure changes.
I have:
=> Avoid punctuation in error strings

config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml
Looks like #56 already got merged so opening this as a follow-up!
I have:
=> version: bump docs version to v1alpha3

apis/cache/v1beta1/replication_group_types.go, apis/database/v1beta1/rdsinstance_types.go, config/crd/cache.aws.crossplane.io_replicationgroups.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml
rds and elasticache: update printer columns
I have:
=> rds and elasticache: update printer columns

pkg/controller/cache/managed.go, pkg/controller/cache/managed_test.go, pkg/controller/database/rdsinstance.go, pkg/controller/database/rdsinstance_test.go
=> Elasticache deletion and update calls better UX

pkg/clients/rds/rds.go, pkg/clients/rds/rds_test.go
This method prevents us having to explicitly filter out or unset attribute referencers before comparing objects to determine whether our external resource is up to date. Note the references will exist in the generated patch we use to update our external resource, but should be ignored.
I have:
=> Automatically ignore attribute referencers when comparing

Jenkinsfile, Makefile, go.sum
Causes CI to check for dirty go modules and fail if so.
I have:
=> Check for dirty go modules in CI

go.mod, go.sum, pkg/clients/eks/eks.go, pkg/clients/eks/eks_test.go, pkg/controller/compute/eks.go, pkg/controller/compute/eks_test.go
Implements https://github.com/crossplaneio/crossplane/issues/861 for AWS.
I have:
=> eks: publish raw kubeconfig in connection details secret

cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml
Per https://github.com/crossplaneio/crossplane/blob/1fb67d0/docs/release/release-process.md#stack-release-process
I have:
[`app.yaml`]: https://github.com/crossplaneio/stack-azure/blob/master/config/stack/manifests/app.yaml
=> Prepare to release v0.3.0

config/crd/cache.aws.crossplane.io_replicationgroupclasses.yaml, config/crd/cache.aws.crossplane.io_replicationgroups.yaml, config/crd/compute.aws.crossplane.io_eksclusterclasses.yaml, config/crd/compute.aws.crossplane.io_eksclusters.yaml, config/crd/database.aws.crossplane.io_dbsubnetgroups.yaml, config/crd/database.aws.crossplane.io_rdsinstanceclasses.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml, config/crd/identity.aws.crossplane.io_iamrolepolicyattachments.yaml, config/crd/identity.aws.crossplane.io_iamroles.yaml, config/crd/network.aws.crossplane.io_internetgateways.yaml, config/crd/network.aws.crossplane.io_routetables.yaml, config/crd/network.aws.crossplane.io_securitygroups.yaml, config/crd/network.aws.crossplane.io_subnets.yaml, config/crd/network.aws.crossplane.io_vpcs.yaml, config/crd/storage.aws.crossplane.io_s3bucketclasses.yaml, config/crd/storage.aws.crossplane.io_s3buckets.yaml, go.mod, go.sum, pkg/clients/s3/s3.go, pkg/controller/cache/claim.go, pkg/controller/compute/claim.go, pkg/controller/database/claim.go, pkg/controller/s3/claim.go
=> Bump crossplane-runtime for updated ReclaimPolicy semantics

cluster/local/integration_tests.sh, config/crd/cache.aws.crossplane.io_replicationgroupclasses.yaml, config/crd/cache.aws.crossplane.io_replicationgroups.yaml, config/crd/compute.aws.crossplane.io_eksclusterclasses.yaml, config/crd/compute.aws.crossplane.io_eksclusters.yaml, config/crd/database.aws.crossplane.io_dbsubnetgroups.yaml, config/crd/database.aws.crossplane.io_rdsinstanceclasses.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml, config/crd/identity.aws.crossplane.io_iamrolepolicyattachments.yaml, config/crd/identity.aws.crossplane.io_iamroles.yaml, config/crd/network.aws.crossplane.io_internetgateways.yaml, config/crd/network.aws.crossplane.io_routetables.yaml, config/crd/network.aws.crossplane.io_securitygroups.yaml, config/crd/network.aws.crossplane.io_subnets.yaml, config/crd/network.aws.crossplane.io_vpcs.yaml, config/crd/storage.aws.crossplane.io_s3bucketclasses.yaml, config/crd/storage.aws.crossplane.io_s3buckets.yaml, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, go.mod, go.sum, pkg/clients/s3/s3.go, pkg/controller/cache/claim.go, pkg/controller/compute/claim.go, pkg/controller/database/claim.go, pkg/controller/s3/claim.go
=> Prep release 0.3.1

apis/cache/v1beta1/replication_group_types.go, apis/compute/v1alpha3/types.go, apis/database/v1alpha3/dbsubnetgroup_types.go, apis/database/v1beta1/rdsinstance_types.go, apis/identity/v1alpha3/iamrole_types.go, apis/identity/v1alpha3/iamrolepolicyattachment_types.go, apis/network/v1alpha3/internetgateway_types.go, apis/network/v1alpha3/routetable_types.go, apis/network/v1alpha3/securitygroup_types.go, apis/network/v1alpha3/subnet_types.go, apis/network/v1alpha3/vpc_types.go, apis/storage/v1alpha3/bucket_types.go, apis/v1alpha3/types.go, config/crd/aws.crossplane.io_providers.yaml, config/crd/cache.aws.crossplane.io_replicationgroupclasses.yaml, config/crd/cache.aws.crossplane.io_replicationgroups.yaml, config/crd/compute.aws.crossplane.io_eksclusters.yaml, config/crd/database.aws.crossplane.io_dbsubnetgroups.yaml, config/crd/database.aws.crossplane.io_rdsinstanceclasses.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml, config/crd/identity.aws.crossplane.io_iamrolepolicyattachments.yaml, config/crd/identity.aws.crossplane.io_iamroles.yaml, config/crd/network.aws.crossplane.io_internetgateways.yaml, config/crd/network.aws.crossplane.io_routetables.yaml, config/crd/network.aws.crossplane.io_securitygroups.yaml, config/crd/network.aws.crossplane.io_subnets.yaml, config/crd/network.aws.crossplane.io_vpcs.yaml, config/crd/storage.aws.crossplane.io_s3buckets.yaml
Validates the `spec` and `forProvider` are present on all managed resources so that we don't hit nil pointer exceptions in controllers.
I have:
=> api: require spec and forProvider in all resources

apis/cache/v1beta1/replication_group_types.go, config/crd/cache.aws.crossplane.io_replicationgroupclasses.yaml
=> replicationgroup: ReplicationGroupClass should be cluster-scoped

config/stack/manifests/resources/dbsubnetgroup.ui-schema.yaml, config/stack/manifests/resources/ekscluster.ui-schema.yaml, config/stack/manifests/resources/eksclusterclass.ui-schema.yaml, config/stack/manifests/resources/iamrole.ui-schema.yaml, config/stack/manifests/resources/iamrolepolicyattachment.ui-schema.yaml, config/stack/manifests/resources/internetgateway.ui-schema.yaml, config/stack/manifests/resources/provider.ui-schema.yaml, config/stack/manifests/resources/rdsinstance.ui-schema.yaml, config/stack/manifests/resources/rdsinstanceclass.ui-schema.yaml, config/stack/manifests/resources/replicationgroup.ui-schema.yaml, config/stack/manifests/resources/replicationgroupclass.ui-schema.yaml, config/stack/manifests/resources/routetable.ui-schema.yaml, config/stack/manifests/resources/s3bucket.ui-schema.yaml, config/stack/manifests/resources/s3bucketclass.ui-schema.yaml, config/stack/manifests/resources/securitygroup.ui-schema.yaml, config/stack/manifests/resources/subnet.ui-schema.yaml, config/stack/manifests/resources/vpc.ui-schema.yaml
Per https://github.com/crossplaneio/crossplane/pull/1145
Signed-off-by: Steven Rathbauer <steven@rathpc.com>
=> Update resourceConditionPaths --> new printerColumns syntax

cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml, examples/stack-aws.yaml
Bumps references and docs for stack-aws v0.5.0 and Crossplane 0.7
I have:
=> v0.5.0: docs and references prep

cmd/stack/main.go, go.mod, go.sum, pkg/controller/aws.go, pkg/controller/cache/claim.go, pkg/controller/cache/managed.go, pkg/controller/compute/claim.go, pkg/controller/compute/eks.go, pkg/controller/compute/eks_test.go, pkg/controller/compute/secret.go, pkg/controller/compute/target.go, pkg/controller/database/claim.go, pkg/controller/database/dbsubnetgroup/controller.go, pkg/controller/database/rdsinstance.go, pkg/controller/identity/iamrole/controller.go, pkg/controller/identity/iamrolepolicyattachment/controller.go, pkg/controller/network/internetgateway/controller.go, pkg/controller/network/routetable/controller.go, pkg/controller/network/securitygroup/controller.go, pkg/controller/network/subnet/controller.go, pkg/controller/network/vpc/controller.go, pkg/controller/s3/claim.go, pkg/controller/s3/s3bucket.go, pkg/controller/s3/s3bucket_test.go
https://github.com/crossplaneio/crossplane-runtime/pull/108
This commit updates all stack-aws controllers to use the logging and event recording functionality added in the above crossplane-runtime PR. Legacy controllers are minimally updated to avoid package scoped loggers.
I have:
=> Plumb up logging and event recording implementations

cmd/stack/main.go
Fixing a copy-paste bug in error output.
I have:
=> Wait a minute, this isn't GCP!

go.sum, pkg/controller/s3/s3bucket.go, pkg/controller/s3/s3bucket_test.go
https://github.com/crossplaneio/crossplane-runtime/issues/1
Per the above issue the utils package is deprecated. As best I can tell these are the only uses of these functions, which duplicate existing client functions.
I have:
=> Use string pointer functions from pkg/clients

.golangci.yml
We don't hold generated code to the same standard as human authored code.
I have:
=> Don't lint generated files

go.mod, go.sum, pkg/controller/cache/managed.go, pkg/controller/database/rdsinstance.go, pkg/controller/s3/s3bucket_test.go
The former has been replaced by the latter.
I have:
=> Switch util.GeneratePassword to password.Generate

apis/cache/v1beta1/register.go, apis/compute/v1alpha3/register.go, apis/database/v1alpha3/register.go, apis/database/v1beta1/register.go, apis/identity/v1alpha3/register.go, apis/network/v1alpha3/register.go, apis/storage/v1alpha3/register.go, apis/v1alpha3/register.go, go.mod, go.sum, pkg/controller/cache/claim.go, pkg/controller/cache/managed.go, pkg/controller/compute/claim.go, pkg/controller/compute/eks.go, pkg/controller/compute/secret.go, pkg/controller/compute/target.go, pkg/controller/database/claim.go, pkg/controller/database/dbsubnetgroup/controller.go, pkg/controller/database/rdsinstance.go, pkg/controller/identity/iamrole/controller.go, pkg/controller/identity/iamrolepolicyattachment/controller.go, pkg/controller/network/internetgateway/controller.go, pkg/controller/network/routetable/controller.go, pkg/controller/network/securitygroup/controller.go, pkg/controller/network/subnet/controller.go, pkg/controller/network/vpc/controller.go, pkg/controller/s3/claim.go, pkg/controller/s3/s3bucket.go
Per https://github.com/crossplaneio/crossplane/issues/1254
I have:
=> Use GroupKind, not Kind, for controller names

cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml, examples/stack-aws.yaml
Prep docs and references for `v0.6.0` release.
I have:
=> [v0.6.0]: prep docs and references

Jenkinsfile, README.md, config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml
Does as the title suggests.
I have:
=> Update remaining references to crossplaneio

examples/aws-setup-provider/setup.sh
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>
Port the PR from crossplane/crossplane#1286
I have:
=> Port the PR crossplane/crossplane#1286 to stack-aws

go.mod, go.sum
Pin crossplane dependencies prior to 0.7 release
I have:
=> Pin crossplane dependencies prior to 0.7 release

README.md, cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml, examples/stack-aws.yaml
Prep docs and references for v0.7.0 release
I have:
=> [release-0.7] Prep docs and references for v0.7.0 release

pkg/clients/rds/rds.go
…er conversion
Cherry pick of https://github.com/crossplane/provider-aws/pull/178 to `master` branch.
I have:
=> rds: fix value copy operation of tags and process features

cluster/local/integration_tests.sh, examples/stack-aws.yaml
Updates docs and references to point to `v0.7.1` for patch release.
I have:
=> [release 0.7] Prep docs and references for v0.7.1 release

go.mod, go.sum, pkg/controller/network/securitygroup/controller_test.go, pkg/controller/s3/claim_test.go
This brings in some fixes that allow us to rebind claims and keep propagating secrets after they've been backed up and restored.
I have:
=> Bump crossplane and runtime dependencies

README.md, cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml, config/stack/samples/install.stack.yaml, examples/stack-aws.yaml
Prep docs and references for v0.8.0 release.
*Note: docs links will be picked up and generated automatically after tag*
I have:
=> [release-0.8] Prep docs and references for v0.8.0 release

pkg/controller/cache/cachesubnetgroup/controller.go
Signed-off-by: sahil-lakhwani <sahilakhwani@gmail.com>
This PR registers the simple reference resolver for CacheSubnetGroup Controller.
I have:
=> cachesubnet: register reference resolver

cluster/local/integration_tests.sh, config/stack/manifests/resources/eksclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml, config/stack/manifests/resources/rdsinstanceclass.resource.yaml, config/stack/manifests/resources/replicationgroupclass.resource.yaml, config/stack/manifests/resources/s3bucketclass.resource.yaml, config/stack/samples/install.stack.yaml, examples/stack-aws.yaml
Prep docs and references for v0.9.0 release
I have:
=> [release-0.9] Prep docs and references for v0.9.0 release

apis/cache/v1beta1/replication_group_types.go, apis/compute/v1alpha3/types.go, apis/database/v1beta1/dbsubnetgroup_types.go, apis/database/v1beta1/rdsinstance_types.go, apis/identity/v1beta1/iamrole_types.go, apis/identity/v1beta1/iamrolepolicyattachment_types.go, apis/network/v1alpha3/internetgateway_types.go, apis/network/v1alpha3/routetable_types.go, apis/network/v1alpha3/securitygroup_types.go, apis/network/v1alpha3/subnet_types.go, apis/network/v1alpha3/vpc_types.go, apis/storage/v1alpha3/bucket_types.go, config/crd/cache.aws.crossplane.io_replicationgroups.yaml, config/crd/compute.aws.crossplane.io_eksclusters.yaml, config/crd/database.aws.crossplane.io_dbsubnetgroups.yaml, config/crd/database.aws.crossplane.io_rdsinstances.yaml, config/crd/identity.aws.crossplane.io_iamrolepolicyattachments.yaml, config/crd/identity.aws.crossplane.io_iamroles.yaml, config/crd/network.aws.crossplane.io_internetgateways.yaml, config/crd/network.aws.crossplane.io_routetables.yaml, config/crd/network.aws.crossplane.io_securitygroups.yaml, config/crd/network.aws.crossplane.io_subnets.yaml, config/crd/network.aws.crossplane.io_vpcs.yaml, config/crd/storage.aws.crossplane.io_s3buckets.yaml, pkg/controller/cache/managed.go, pkg/controller/database/rdsinstance.go, pkg/controller/network/vpc/controller.go
Some of the resources do not have them. I also added a small commit that sorts the tags in the taggers.
I have:
=> Add Ready and Synced printer columns

go.mod, go.sum
=> Pin crossplane and runtime dependencies

cluster/local/integration_tests.sh, config/package/manifests/resources/eksclusterclass.resource.yaml, config/package/manifests/resources/provider.resource.yaml, config/package/manifests/resources/rdsinstanceclass.resource.yaml, config/package/manifests/resources/replicationgroupclass.resource.yaml, config/package/manifests/resources/s3bucketclass.resource.yaml, config/package/samples/install.package.yaml, examples/stack-aws.yaml
=> Pin artifacts and images to v0.10.0

apis/compute/container.go, apis/database/database.go, apis/eks/eks.go, apis/storage/storage.go
It appears during one of the kubebuilder transitions that these group
tags were added to the group-level package. In practice, we declare the
groups at the version level in each directory's doc.go. Therefore, these
tags do not impact generation and are not consistent across the repo.
I have:
=> Remove extraneous group declarations

examples/network/internetgatway.yaml, examples/network/routetable.yaml, examples/network/securitygroup.yaml, examples/network/subnet.yaml, examples/network/vpc.yaml
Signed-off-by: sahil-lakhwani <sahilakhwani@gmail.com>
As #250 moved the AWS network resources to a new group, these examples need an update.
I have:
=> network examples: change group name

pkg/clients/rds/rds.go, pkg/clients/rds/rds_test.go
Signed-off-by: Chris <chris.vodak@gmail.com>
Adding more unit tests to RDS Client
Fixes #247
I have:
=> Adding RDS Client tests

apis/notification/v1alpha1/zz_generated.managed.go, config/crd/notification.aws.crossplane.io_snssubscriptions.yaml, config/crd/notification.aws.crossplane.io_snstopics.yaml, pkg/controller/notification/snssubscription/controller.go, pkg/controller/notification/snssubscription/controller_test.go, pkg/controller/notification/snstopic/controller.go, pkg/controller/notification/snstopic/controller_test.go
Signed-off-by: sahil-lakhwani <sahilakhwani@gmail.com>
This PR updates provider references for the SNS resources to use the crossplane-runtime reference type.
I have:
=> sns: update provider reference

pkg/clients/iam/iam.go
S3 Bucket is still working with legacy patterns & controllers that do not handle deletion cases well. This fix alleviates the issue where some of the side effect resources like IAM user is already deleted, deletion gets stuck.
Fixes #287 
I have:
=> s3 bucket: fix not found errors during deletion

config/package/manifests/resources/eksclusterclass.resource.yaml, config/package/manifests/resources/provider.resource.yaml, config/package/manifests/resources/rdsinstanceclass.resource.yaml, config/package/manifests/resources/replicationgroupclass.resource.yaml, config/package/manifests/resources/s3bucketclass.resource.yaml
Updates docs links to match new pattern on https://doc.crds.dev
I have:
=> Update docs links to match new pattern

cluster/local/integration_tests.sh, config/package/manifests/resources/aws.crossplane.io/provider.resource.yaml, config/package/manifests/resources/cache.aws.crossplane.io/replicationgroupclass.resource.yaml, config/package/manifests/resources/compute.aws.crossplane.io/eksclusterclass.resource.yaml, config/package/manifests/resources/database.aws.crossplane.io/rdsinstanceclass.resource.yaml, config/package/manifests/resources/storage.aws.crossplane.io/s3bucketclass.resource.yaml, config/package/samples/install.package.yaml, examples/stack-aws.yaml
Prep docs and references for v0.11.0 release.
I have:
=> [release-0.11] prep docs and references

cluster/local/integration_tests.sh, config/package/manifests/resources/aws.crossplane.io/provider.resource.yaml, config/package/manifests/resources/cache.aws.crossplane.io/replicationgroupclass.resource.yaml, config/package/manifests/resources/compute.aws.crossplane.io/eksclusterclass.resource.yaml, config/package/manifests/resources/database.aws.crossplane.io/rdsinstanceclass.resource.yaml, config/package/manifests/resources/storage.aws.crossplane.io/s3bucketclass.resource.yaml, config/package/samples/install.package.yaml, examples/stack-aws.yaml
Prep docs and references for v0.11.1 release
I have:
=> [release-0.11] Prep docs and references for v0.11.1 release

examples/storage/policy/bucket-policy-bucket.yaml, examples/storage/policy/bucket-policy-hardcode.yaml, examples/storage/policy/bucket-policy-label.yaml, examples/storage/policy/bucket-policy-partial.yaml, examples/storage/policy/bucket-policy-public.yaml, pkg/controller/s3/s3bucketpolicy/s3bucketpolicy.go
This PR aims to add more examples for the S3BucketPolicy, this should hopefully provide more context for some of the features provided by the resource. There is also a minor bugfix/optimization that I squshed into this PR.
Partial Fix for #321 
I have:
- [:heavy_check_mark:] Run `make reviewable` to ensure this PR is ready for review.
- [:heavy_check_mark:] Ensured this PR contains a neat, self documenting set of commits.
- [:heavy_check_mark:] Updated any relevant [documentation], [examples], or [release notes].
- [:heavy_check_mark:] Updated the dependencies in [`app.yaml`] to include any new role permissions.
[release notes]: …
=> Adds examples for S3BucketPolicy

apis/ec2/v1alpha1/zz_generated.managed.go, config/crd/ec2.aws.crossplane.io_elasticips.yaml, pkg/clients/ec2/elasticip.go, pkg/controller/ec2/elasticip/controller.go, pkg/controller/ec2/elasticip/controller_test.go
`ElasticIP` has been implemented while https://github.com/crossplane/provider-aws/pull/320 was still open and that broke master. This PR does the migration for ElasticIP, too.
I have:
=> elasticip: update to new provider and providerconfig

pkg/clients/rds/rds.go, pkg/clients/rds/rds_test.go, pkg/controller/database/rdsinstance.go, pkg/controller/database/rdsinstance_test.go
Fixes #329 
RDSInstances will now only update the master password if there's a difference between the exported secret (if exists) and the referenced input secret from `masterPasswordSecretRef`.
I have:
=> Fix RDS Instance Password Reset Loop

go.mod, go.sum, pkg/controller/acm/controller.go, pkg/controller/acmpca/certificateauthority/controller.go, pkg/controller/acmpca/certificateauthoritypermission/controller.go, pkg/controller/applicationintegration/sqs/controller.go, pkg/controller/cache/cachesubnetgroup/controller.go, pkg/controller/cache/managed.go, pkg/controller/database/rdsinstance.go, pkg/controller/ec2/elasticip/controller.go, pkg/controller/ec2/internetgateway/controller.go, pkg/controller/ec2/routetable/controller.go, pkg/controller/ec2/securitygroup/controller.go, pkg/controller/ec2/subnet/controller.go, pkg/controller/ec2/vpc/controller.go, pkg/controller/ecr/repository/controller.go, pkg/controller/eks/cluster.go, pkg/controller/eks/nodegroup/controller.go, pkg/controller/identity/iamgrouppolicyattachment/controller.go, pkg/controller/identity/iamgroupusermembership/controller.go, pkg/controller/identity/iampolicy/controller.go, pkg/controller/notification/snssubscription/controller.go, pkg/controller/notification/snstopic/controller.go, pkg/controller/redshift/controller.go, pkg/controller/route53/hostedzone/controller.go, pkg/controller/route53/resourcerecordset/controller.go, pkg/controller/s3/s3bucketpolicy/s3bucketpolicy.go
…izer
See https://github.com/crossplane/crossplane/issues/1686 for more context.
I have:
=> Update all managed resources to use providerconfig defaulting

apis/notification/v1alpha1/snstopic_types.go, config/crd/notification.aws.crossplane.io_snstopics.yaml
=> Fixed typo in notification.aws.crossplane.io DeliveryRetryPolicy description

apis/ecr/v1alpha1/common.go, pkg/controller/acm/controller.go
Removes some superfluous fmt.Print statements.
I have:
N/A
=> Remove debugging print statements

pkg/clients/aws.go, pkg/clients/dynamodb/dynamodb.go, pkg/clients/ecr/repository.go, pkg/clients/ecr/repository_test.go, pkg/clients/eks/eks.go, pkg/clients/elasticloadbalancing/elb/elb.go, pkg/clients/rds/rds.go, pkg/clients/redshift/redshift.go, pkg/clients/resourcerecordset/resourcerecordset.go, pkg/clients/sqs/queue.go, pkg/controller/acmpca/certificateauthoritypermission/controller.go, pkg/controller/acmpca/certificateauthoritypermission/controller_test.go, pkg/controller/ecr/repository/controller.go
I noticed that some controllers do not ignore `Region` and return false for up-to-date check continuously during my doc test.
Fixes #
I have:
Manually with `examples` folder.
=> Fix for up-to-date checks that include region

apis/acm/v1alpha1/referencers.go, apis/acmpca/v1alpha1/referencers.go, apis/cache/v1beta1/referencers.go, apis/database/v1beta1/referencers.go, apis/ec2/v1alpha4/referencers.go, apis/ec2/v1beta1/referencers.go, apis/eks/v1alpha1/referencers.go, apis/eks/v1beta1/referencers.go, apis/elasticloadbalancing/v1alpha1/referencers.go, apis/identity/v1alpha1/referencers.go, apis/identity/v1beta1/referencers.go, apis/notification/v1alpha1/referencers.go, apis/redshift/v1alpha1/referencers.go, apis/route53/v1alpha1/referencers.go, apis/s3/v1alpha1/referencers.go, apis/s3/v1beta1/referencers.go
See https://github.com/crossplane/crossplane/issues/1499
I have:
=> Wrap ref resolution errors with context

examples/s3/bucket.yaml, pkg/controller/s3/bucket/lifecycleConfig.go, pkg/controller/s3/bucket/replicationConfig.go, pkg/controller/s3/bucket/sseConfig.go, pkg/controller/s3/bucket/websiteConfig.go
Signed-off-by: Krish Chowdhary <krish@redhat.com>
Fixes #380 
I have:
I updated the s3 bucket example yaml, and ran with the fixes for issue #380. The error no longer occurred. 
=> s3 bucket: fixes resource ignore issue for errors, adds SSe to example

examples/s3/bucket.yaml, pkg/clients/s3/bucket.go, pkg/controller/s3/bucket/lifecycleConfig.go, pkg/controller/s3/bucket/lifecycleConfig_test.go, pkg/controller/s3/bucket/replicationConfig.go, pkg/controller/s3/bucket/taggingConfig.go, pkg/controller/s3/bucket/taggingConfig_test.go, pkg/controller/s3/testing/testHelper.go
Fixes #385 
I have:
Added additional unit tests, manual testing with an S3 bucket (updated example.yaml)
=> s3 bucket: adds sorting for tagging lists, minor refactoring around tags

apis/acm/v1alpha1/certificate_types.go, package/crds/acm.aws.crossplane.io_certificates.yaml
Updates the malformed kubebuilder validation annotations to the correct
format.
I have:
Install CRDs and create with invalid values in the modified fields.
=> Fix ACM Certificate enums

examples/ec2/elasticip.yaml, examples/ec2/natgateway.yaml
Ran into it while I was doing manual testing. I'll cherry-pick to `release-0.15` after this is merged to master.
I have:
Manually.
=> ec2 examples: fix natgateway example

examples/ec2/elasticip.yaml, examples/ec2/natgateway.yaml
Cherry-pick of https://github.com/crossplane/provider-aws/pull/434 to `release-0.15`
I have:
Manually. 
=> Cherry-pick doc update to 0.15.0

apis/sqs/v1beta1/queue_types.go, apis/sqs/v1beta1/referencers.go, apis/sqs/v1beta1/zz_generated.deepcopy.go, package/crds/sqs.aws.crossplane.io_queues.yaml
Add ref and selector fields for redrivePolicy.deadLetterQueueArn
Fixes #439 
I have:
not tested directly.
=> queue: add ref and selector fields for redrivePolicy.deadLetterQueueArn

OWNERS.md
Adds krishchow as an official provider-aws maintainer.
Fixes #438 
I have:
n/a
=> Add krishchow as provider-aws maintainer

pkg/clients/aws.go
Adds annotation parsing in the form of
```
aws.crossplane.io/endpointURL:
aws.crossplane.io/endpointSigningRegion:
```
When a new service is created, these annotations are used to add custom urls and signing regions to a service configuration. The service name is matched against the `apiVersion` so that a resolver function is generated specific to that service.
Fixes #199 
I have:
=> Custom Service Endpoint Support

pkg/controller/dynamodb/table/hooks.go
Fixes too frequent updates as described in https://github.com/crossplane/provider-aws/issues/464
Fixes #464
I have:
```yaml
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
name: test-table
spec:
forProvider:
attributeDefinitions:
- attributeName: testCol
attributeType: S
keySchema:
- attributeName: testCol
keyType: HASH
provisionedThroughput: 
readCapacityUnits: 1
writeCapacityUnits: 1
tags:
- key: environment
value: dev
- key: provisionedBy
value: Crossplane
```
works as expected.
=> dynamodb.table: update frequency fixed

AUTHENTICATION.md
Update `AUTHENTICATION.md` with workflow using `ControllerConfig`.
Fixes #437 
I have:
Doing full e2e test so keeping in draft for a moment.
=> Update AUTHENTICATION.md to use ControllerConfig

apis/dynamodb/v1alpha1/generator-config.yaml, go.mod, go.sum, pkg/controller/dynamodb/backup/hooks.go, pkg/controller/dynamodb/backup/zz_controller.go, pkg/controller/dynamodb/backup/zz_conversions.go, pkg/controller/dynamodb/globaltable/hooks.go, pkg/controller/dynamodb/globaltable/zz_controller.go, pkg/controller/dynamodb/globaltable/zz_conversions.go, pkg/controller/dynamodb/table/hooks.go, pkg/controller/dynamodb/table/hooks_test.go, pkg/controller/dynamodb/table/zz_controller.go, pkg/controller/dynamodb/table/zz_conversions.go
I've used DynamoDB to test my changes in https://github.com/aws/aws-controllers-k8s/pull/625 . The change is non-breaking.
I also added custom update & delete methods for `GlobalTable`.
Manually tested all three affected resources.
=> Update dynamodb with the latest ACK code generation

CODE_GENERATION.md, README.md
I was planning to write this after I get referencer field generation as well but several community members are asking how they can contribute to provider-aws using ACK so I decided to put it up there and make changes as we go.
Fixes https://github.com/crossplane/provider-aws/issues/482
I have:
Not needed.
=> Documentation to add new resource support using ACK

AUTHENTICATION.md
Updates on authentication.md: 
- Provider apiversion 
- Ensure ProviderConfig resource is available
- Remove unnecessary escape on  IAM Role
- Tested on my environment with Crossplane master + AWS EKS 1.16
=> Fixes on Authentication doc

CODE_GENERATION.md, README.md
Update to use new repo and add testing sections.
I have:
Manually.
=> Update CODE_GENERATION document

go.mod, go.sum
Update to what [code-generator](https://github.com/aws-controllers-k8s/code-generator) uses so that new fields are accommodated.
Fixes #
I have:
`make reviewable test`
=> update AWS Go SDK v1 version to what code-generator uses

INSTALL.md
Enhance `INSTALL.md` with instructions on how to run `provider-aws` locally. Especialy note that CRDs need to be applied manually to a fresh k8s cluster.
See #406 
#371 briefly mentions that you need to install CRDs.
No changes in code
=> Enhance doc with local run instructions

pkg/clients/iam/fake/iamrole.go, pkg/clients/iam/iamrole.go, pkg/clients/iam/iamrole_test.go, pkg/controller/identity/iamrole/controller.go
Fixes https://github.com/crossplane/crossplane/issues/2118
I have:
Unit test and manually.
=> iamrole: add update capability for tags

pkg/clients/aws_test.go, pkg/clients/ecr/repository_test.go, pkg/clients/iam/iamrole_test.go
Signed-off-by: Kellin McAvoy <kellinmcavoy@gmail.com>
Fixes flaky unit tests
I have:
Increase test count in Makefile to bump the default/CI test count.
=> Fix flaky tag comparison

apis/dynamodb/v1alpha1/zz_backup.go, apis/dynamodb/v1alpha1/zz_enums.go, apis/dynamodb/v1alpha1/zz_generated.deepcopy.go, apis/dynamodb/v1alpha1/zz_global_table.go, apis/dynamodb/v1alpha1/zz_groupversion_info.go, apis/dynamodb/v1alpha1/zz_table.go, apis/dynamodb/v1alpha1/zz_types.go, package/crds/dynamodb.aws.crossplane.io_tables.yaml, pkg/controller/dynamodb/backup/zz_controller.go, pkg/controller/dynamodb/backup/zz_conversions.go, pkg/controller/dynamodb/globaltable/hooks.go, pkg/controller/dynamodb/globaltable/zz_controller.go, pkg/controller/dynamodb/globaltable/zz_conversions.go, pkg/controller/dynamodb/table/hooks.go, pkg/controller/dynamodb/table/hooks_test.go, pkg/controller/dynamodb/table/zz_controller.go, pkg/controller/dynamodb/table/zz_conversions.go
dynamodb: update with codegen that has new error wrapper
Fixes #
I have:
Diff is fairly minimal, unit tests should suffice.
=> dynamodb: update with codegen that has new error wrapper

apis/sfn/v1alpha1/zz_activity.go, apis/sfn/v1alpha1/zz_enums.go, apis/sfn/v1alpha1/zz_groupversion_info.go, apis/sfn/v1alpha1/zz_state_machine.go, apis/sfn/v1alpha1/zz_types.go, pkg/controller/kms/key/setup.go, pkg/controller/kms/key/zz_controller.go, pkg/controller/sfn/activity/hooks.go, pkg/controller/sfn/activity/zz_controller.go, pkg/controller/sfn/activity/zz_conversions.go, pkg/controller/sfn/statemachine/hooks.go, pkg/controller/sfn/statemachine/zz_controller.go, pkg/controller/sfn/statemachine/zz_conversions.go
Updates the codegen output and makes necessary manual changes. No functionality change is expected.
Fixes #525 
I have:
I didn't find it worth testing honestly.
=> Update KMS and SFN generated controllers to new error wrapper

cluster/local/integration_tests.sh
Fixes https://github.com/crossplane/provider-aws/issues/547
I have:
`make reviewable` and `make -j4` work.
=> build: update build submodule

apis/cache/v1alpha1/cachecluster_types.go, apis/cache/v1alpha1/referencer.go, apis/s3/v1alpha3/referencers.go, apis/s3/v1beta1/referencers.go, pkg/clients/elasticache/elasticcachecluster_test.go, pkg/clients/sqs/fake/fake.go, pkg/clients/sqs/queue.go, pkg/clients/sqs/queue_test.go, pkg/controller/cache/cluster/controller.go, pkg/controller/cache/cluster/controller_test.go, pkg/controller/secretsmanager/controller.go, pkg/controller/sqs/queue/controller.go
This fixes a few license headers that were unintentionally condensed in
previous commits.
I have:
n/a
=> Fix condensed headers

go.mod, go.sum
update to current code-generator version https://github.com/aws-controllers-k8s/code-generator/blob/03ba59b/go.mod#L7
Fixes #
I have:
Unit tests and compile.
=> sdk: update to current code-generator version

pkg/clients/ec2/securitygroup.go
Fixes https://github.com/crossplane/provider-aws/issues/515
Fixes #
I have:
N/A
=> ec2.securitygroup: fix typo in late-init code

pkg/controller/s3/bucketpolicy/bucketpolicy.go
This one seems to be missed in https://github.com/crossplane/provider-aws/pull/475
Fixes https://crossplane.slack.com/archives/C01718T2476/p1614625734070700?thread_ts=1614161970.017100&cid=C01718T2476
I have:
Unit test.
=> bucketpolicy: use awsclient err wrapper

CODE_GENERATION.md
Updates the Setup functions to pass the provider rate limiter and teh
default managed rate limiter to the controller.
I have:
n/a
=> Update CODE_GENERATION.md setup funcs with rate limiter

go.mod, go.sum
Updates crossplane-runtime dependency to v0.13.0.
I have:
`make build`
=> Update crossplane-runtime to v0.13.0

AUTHENTICATION.md
Updates the AUTHENTICATION.md guide to install crossplane from stable
channel. When this doc was first introduced the alpha channel was being
used but it has been deprecated as of v1.0.0.
I have:
n/a
=> Install stable crossplane in auth guide

pkg/controller/ec2/securitygroup/controller_test.go
Add tests I missed to sg tags.
I have:
Test code only. Tested.
=> ec2.securitygroup: Add tests for tags

CODE_GENERATION.md
Signed-off-by: Hitesh Ghia <hiteshghia@gmail.com>
Adding more details to the in-cluster testing section in CODE_GENERATION.md
I have:
=> Improve CODE_GENERATION In-cluster testing section

cluster/local/integration_tests.sh, go.mod, go.sum
Updating them before the release.
I have:
N/A
=> update build submodule and crossplane-tools

cluster/local/integration_tests.sh
Signed-off-by: Muvaffak Onus <me@muvaf.com>
Update version to get the [fix](https://github.com/upbound/build/pull/149) related to publishing artifacts.
I have:
N/A
=> build: update version to get the fix related to publishing artifacts

apis/acmpca/v1alpha1/certificateauthority_types.go, package/crds/acmpca.aws.crossplane.io_certificateauthorities.yaml
https://github.com/crossplane/provider-aws/issues/651
Fixes #651
Fixed typo to allow the creation of Subordinate CA.
I have:
=> fix: acm-pca. fixed typo SUBORDINATE

package/crossplane.yaml
Per crossplane/crossplane#2299
I have:
I'm confident enough from testing a similar change at crossplane/provider-azure#244.
=> Use recommended packaging format

package/crossplane.yaml
Per crossplane/crossplane#2299 , we'd like to have a patch release of providers to expose that metadata.
I have:
N/A
=> Backport new package metadata format to 0.18

CODE_GENERATION.md, Makefile
I updated the guide to use the new `make services SERVICES=rds,kms` target and also added `make services.all` target to run generator for all existing services. I plan to add `make services.all` to `make generate` but that will come in with another PR as the diff is quite large. Once that's merged, we'll make sure all generated code is kept up-to-date by `make reviewable` and `make check-diff`
I have:
Manually.
=> Update code generation guide with make target

examples/apigatewayv2/ws-api.yaml, examples/apigatewayv2/ws-model.yaml
Adds a model resource and a WEBSOCKET API for it to reference. Models
are only compatible with WEBSOCKET protocol.
xref https://github.com/cncf/crossplane-conformance/issues/4
I have:
Validated manually.
=> Add valid model resource

examples/eks/cluster.yaml, examples/eks/fargateprofile.yaml, examples/eks/nodegroup.yaml, examples/iam/role.yaml, examples/iam/rolepolicyattachment.yaml, examples/secretsmanager/secret.yaml
Addresses conformance test failures in various resources:
- EKS Cluster
- Fargate Profile
- NodeGroup
- Secrets
Fixes #
I have:
Manually deployed affected services and confirmed they showed up healthy.
=> Addressing various failures in running conformance tests

Makefile, pkg/controller/apigatewayv2/api/zz_controller.go, pkg/controller/apigatewayv2/apimapping/zz_controller.go, pkg/controller/apigatewayv2/authorizer/zz_controller.go, pkg/controller/apigatewayv2/deployment/zz_controller.go, pkg/controller/apigatewayv2/domainname/zz_controller.go, pkg/controller/apigatewayv2/integration/zz_controller.go, pkg/controller/apigatewayv2/integrationresponse/zz_controller.go, pkg/controller/apigatewayv2/model/zz_controller.go, pkg/controller/apigatewayv2/route/zz_controller.go, pkg/controller/apigatewayv2/routeresponse/zz_controller.go, pkg/controller/apigatewayv2/stage/zz_controller.go, pkg/controller/apigatewayv2/vpclink/zz_controller.go, pkg/controller/cloudfront/distribution/zz_controller.go, pkg/controller/dynamodb/globaltable/zz_controller.go, pkg/controller/dynamodb/table/zz_controller.go, pkg/controller/efs/filesystem/zz_controller.go, pkg/controller/rds/dbcluster/zz_controller.go, pkg/controller/rds/dbparametergroup/zz_controller.go, pkg/controller/rds/globalcluster/zz_controller.go, pkg/controller/secretsmanager/secret/zz_controller.go, pkg/controller/sfn/statemachine/zz_controller.go
Signed-off-by: Muvaffak Onus <me@muvaf.com>
update code generator to remove the unnecessary error handling in update.
Fixes #
I have:
`make reviewable`
=> update code generator

examples/s3/bucket.yaml, examples/s3/bucketpolicy-json.yaml, examples/s3/bucketpolicy.yaml
This uses a bucket name that is slightly less likely to conflict (it will likely only conflict with other users of this example). It also updates the policy examples to use the same region as the bucket they apply to.
I have:
I've applied the updated examples and confirmed they become ready.
=> Smooth out S3 examples

examples/acm/certificate.yaml, examples/acmpca/certificateauthority.yaml, examples/apigatewayv2/domainname.yaml, examples/ec2/securitygroup.yaml, examples/eks/cluster.yaml, examples/eks/nodegroup.yaml, examples/elasticloadbalancing/elbattachment.yaml, examples/kms/key.yaml, examples/notification/snssubscription.yaml, examples/servicediscovery/httpnamespace.yaml, examples/servicediscovery/privatednsnamespace.yaml, examples/servicediscovery/publicdnsnamespace.yaml
Once this commit is merged I'll have validated (in service of https://github.com/cncf/crossplane-conformance/issues/4) that everything in the `examples/` directory works - sometimes with a little (documented) human intervention. The one remaining exception is the API Gateway v2 managed resources.
I have:
I've spun up all of these examples (in some cases with a little manual intervention).
=> Further adventures in AWS examples

pkg/controller/ecr/repositorypolicy/controller.go
Signed-off-by: chris <cvodak@ea.com>
Fixes #714 
I have:
Created a repo and policy for it, deleted repo first and made sure could still then delete policy
=> add repo not exist to ignore

apis/acmpca/v1alpha1/certificateauthoritypermission_types.go, apis/acmpca/v1alpha1/zz_generated.deepcopy.go, examples/acmpca/certificateauthoritypermission.yaml, examples/iam/group.yaml, examples/iam/grouppolicyattachment.yaml, examples/iam/groupusermembership.yaml, package/crds/acmpca.aws.crossplane.io_certificateauthoritypermissions.yaml, pkg/controller/acmpca/certificateauthoritypermission/controller.go, pkg/controller/acmpca/certificateauthoritypermission/controller_test.go, pkg/controller/identity/iamgrouppolicyattachment/controller.go, pkg/controller/identity/iamgrouppolicyattachment/controller_test.go, pkg/controller/identity/iamgroupusermembership/controller.go, pkg/controller/identity/iamgroupusermembership/controller_test.go
Quick fixes for https://github.com/crossplane/provider-aws/pull/727 added on top of the base commits.
Also fixes https://github.com/crossplane/provider-aws/issues/726.
I have:
Manually by creating all related IAM resources and both `acmpca` resources.
=> Ensure all managed resources have external names

CODE_GENERATION.md
added link for Makefile in CODE_GENERATION.md and example to make it clear to add <serviceid>  for GENERATED_SERVICES
I have:
=> doc(makefile): add more informations for makefile

package/crds/ec2.aws.crossplane.io_vpcpeeringconnections.yaml, package/crds/rds.aws.crossplane.io_dbinstances.yaml, pkg/controller/ec2/routetable/controller.go, pkg/controller/ec2/routetable/controller_test.go
I noticed this struct field is no longer used.
I have:
I have not - this seems like a safe enough change that `make reviewable` alone is enough.
=> Remove superfluous Kubernetes client from RouteTable ExternalClient

OWNERS.md
Carl has been very active submitting and reviewing PRs, as well as helping the community by providing feedback on issues and answering questions on Slack!
I have:
N/A
=> Propose chlunde as a new maintainer

pkg/clients/eks/eks.go
fixes problem  `connect failed: cannot create new Kubernetes client: cannot create Kubernetes client: Unauthorized`
- get PresignGetCallerIdentity working again after https://github.com/crossplane/provider-aws/pull/602 was part of v.0.20.0 
Fixes https://github.com/crossplane/provider-aws/issues/892
I have:
log from authenticator-ef5149d99b00e4101f894bf4d79c0335
```
time="2021-10-31T19:01:12Z" level=info msg="access granted" arn="arn:aws:iam::255932642927:user/xxx" client="127.0.0.1:34196" groups="[system:masters]" method=POST path=/authenticate sts=sts.us-west-2.amazonaws.com uid="heptio-authenticator-aws:255932642927:xxxx" username=kubernetes-admin | time="2021-10-31T19:01:12Z" level=info msg="access granted" …
```
=> fix(eks-kubeconfig): eks-presignGetCallerIdentity

OWNERS.md
See https://github.com/crossplane/org/issues/20. @haarchri has been doing a lot of great work on this provider and has volunteered to help us maintain it. Thank you @haarchri!
I have:
N/A
=> Add haarchri as a maintainer

.github/ISSUE_TEMPLATE/release.md
Adds a release issue template that includes all necessary steps.
I have:
By running the release of `v0.21.0`
=> github: add release issue

pkg/controller/s3/bucket/CORSConfig_test.go, pkg/controller/s3/bucket/accelerateConfig_test.go, pkg/controller/s3/bucket/lifecycleConfig_test.go, pkg/controller/s3/bucket/loggingConfig_test.go, pkg/controller/s3/bucket/notificationConfig_test.go, pkg/controller/s3/bucket/replicationConfig_test.go, pkg/controller/s3/bucket/requestPaymentConfig_test.go, pkg/controller/s3/bucket/sseConfig_test.go, pkg/controller/s3/bucket/taggingConfig_test.go, pkg/controller/s3/bucket/versioningConfig_test.go, pkg/controller/s3/bucket/websiteConfig_test.go
This just removes gomega and renames a package import.
I have:
I've just run the unit tests. :)
=> S3 test nitpicks

pkg/controller/route53resolver/resolverendpoint/hooks.go, pkg/controller/route53resolver/resolverrule/hooks.go
old status:
```
NAME                                                                  READY   SYNCED   EXTERNAL-NAME
resolverrule.route53resolver.aws.crossplane.io/sample-resolver-rule   False   True     rslvr-rr-d64a11650e394f618
NAME                                                                 READY   SYNCED   EXTERNAL-NAME
resolverendpoint.route53resolver.aws.crossplane.io/sample-resolver   False   True     rslvr-out-a8fd90a254954092b
```
new status:
```
NAME                                                                  READY   SYNCED   EXTERNAL-NAME
resolverrule.route53resolver.aws.crossplane.io/sample-resolver-rule   True    True     rslvr-rr-d64a11650e394f618
NAME …
```
=> feat(route53resolver): added postObserve status

pkg/controller/database/rdsinstance.go, pkg/controller/database/rdsinstance_test.go
When creating a new database, late init would trigger a kubernetes
update in the `Observe` method, which in turn would trigger an error in
`crossplane-runtime`:
2021-09-12T15:29:23.921+0200	ERROR	controller-runtime.manager.controller.managed/rdsinstance.database.aws.crossplane.io	Reconciler error	{"reconciler group": "database.aws.crossplane.io", "reconciler kind": "RDSInstance", "name": "example-rds", "namespace": "", "error": "cannot update managed resource status: Operation cannot be fulfilled on rdsinstances.database.aws.crossplane.io \"example-rds\": the object has been modified; please apply your changes to the latest version and try again", "errorVerbose": "Operation cannot be fulfilled on rdsinstances.database.aws.crossplane.io \"example-rds\": the object has been modified; please …
=> rdsinstance: Use ResourceLateInitialized from crossplane-runtime

apis/servicediscovery/v1alpha1/custom_types.go
fix gofmt after #988 merge to master
https://github.com/crossplane/provider-aws/runs/4431925719?check_suite_focus=true#step:11:18
I have:
=> fix(fmt): #988 fix gofmt-servicediscovery

AUTHENTICATION.md, CODE_GENERATION.md
Signed-off-by: Steven Borrelli <steve@borrelli.org>
Updates documentation links to crossplane.io that return 404 or have new anchors. 
I have:
=> Update documentation links to crossplane.io

AUTHENTICATION.md
This PR aims to clarify the configuration needed to use kube2iam to authenticate to AWS in a non-EKS cluster
(cf. Slack discussion [here](https://crossplane.slack.com/archives/CEG3T90A1/p1639651106294400?thread_ts=1639591534.284400&cid=CEG3T90A1))
=> Add instructions to use kube2iam authentication

CODE_GENERATION.md
=> fix(docs): fix docs to current aws-go-sdk 1.37.10 for code-gen

cluster/local/integration_tests.sh
fixed e2e-test in provider-aws after https://github.com/crossplane/crossplane/pull/2804
you can see here that the e2e-test is failing: 
https://github.com/crossplane/provider-aws/runs/4716896964?check_suite_focus=true#step:12:79
Fixes #
I have:
=> fix(e2e-test) changed pkg.crossplane.io to v1

pkg/controller/glue/securityconfiguration/setup.go
cleanup glue securityconfig &cr.name to annotation
we missed one :/ https://github.com/crossplane/provider-aws/pull/1019
Fixes #
I have:
```
kubectl describe securityconfiguration.glue.aws.crossplane.io/glue-securityconfiguration
Name:         glue-securityconfiguration
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2022-01-06T08:17:26+01:00
crossplane.io/external-create-succeeded: 2022-01-06T08:17:27+01:00
crossplane.io/external-name: glue-securityconfiguration
API Version:  glue.aws.crossplane.io/v1alpha1
Kind:         SecurityConfiguration
Metadata:
Creation Timestamp:  2022-01-06T07:17:26Z
Finalizers:
finalizer.managedresource.crossplane.io
Generation:  2
Resource Version:  2840975
UID: …
```
=> cleanup glue securityconfig &cr.name to annotation

Makefile, apis/route53resolver/v1alpha1/zz_resolver_endpoint.go, apis/route53resolver/v1alpha1/zz_resolver_rule.go, apis/route53resolver/v1alpha1/zz_types.go, package/crds/route53resolver.aws.crossplane.io_resolverendpoints.yaml, package/crds/route53resolver.aws.crossplane.io_resolverrules.yaml, pkg/controller/route53resolver/resolverendpoint/zz_controller.go, pkg/controller/route53resolver/resolverendpoint/zz_conversions.go, pkg/controller/route53resolver/resolverrule/zz_controller.go, pkg/controller/route53resolver/resolverrule/zz_conversions.go
- added route53resolver to makefile for generated-services
- rerun make generate
I have:
=> fix(generated-services) added route53resolver to makefile

AUTHENTICATION.md
Fixes #None
Proposes various documentation improvements:
- Unifies the writing style
- Remove some steps that create unnecessary, temporary files and export variables and separate long commands into multiple lines
- Adds a table of contents to navigate users to the section they want to know
- Updates the versions of the references to https://crossplane.io
- Removes references to unstable versions of this provider
Signed-off-by: micnncim <micnncim@gmail.com>
I have:
No testing is necessary for this change.
=> Update format of authentication guide

apis/aws.go
I'm not exactly sure how this passed all of our tests but apparently some of the API versions are not registered, causing their controllers to crash.
I have:
Tested manually, making sure it doesn't crash in start up and also during operations.
=> apis: register missing api groups

CODE_GENERATION.md
Minor fixes of code generation doc which incorporate recent experience of generating #1159 
I have:
N/A
=> Fix code generation doc discrepancies with the current state

pkg/clients/ec2/fake/subnet.go, pkg/clients/ec2/fake/vpc.go, pkg/clients/ec2/subnet.go, pkg/clients/ec2/vpc.go, pkg/controller/ec2/subnet/controller.go, pkg/controller/ec2/vpc/controller.go, pkg/controller/ec2/vpc/controller_test.go, pkg/controller/s3/bucket/websiteConfig.go
- added option to diff add/delete tags for vpc and subnet 
- added default crossplane tags in subnet
Fixes #
I have:
created
updated
deleted
=> feat(ec2-tags): tags vpc/subnet default,add,delete

pkg/controller/ec2/vpcendpointserviceconfiguration/setup.go
=> fix(vpcendpointserviceconfiguration): fix missing field in status

apis/efs/v1alpha1/zz_generated.managed.go, package/crds/efs.aws.crossplane.io_accesspoints.yaml
make generate after efs-access point merge https://github.com/crossplane/provider-aws/pull/1201 to get latest master changes in
Fixes #
I have:
crete efs access points
=> fix(efs): generate latest master stuff for efs access point

apis/eks/manualv1alpha1/nodegroup_types.go, apis/eks/v1beta1/types.go, package/crds/eks.aws.crossplane.io_clusters.yaml, package/crds/eks.aws.crossplane.io_nodegroups.yaml, pkg/clients/eks/eks.go, pkg/clients/eks/eks_test.go, pkg/clients/eks/nodegroup.go, pkg/controller/eks/cluster_test.go, pkg/controller/eks/nodegroup/controller_test.go
=> Add additional fields to the atProvider status for eks Cluster and eks NodeGroup

pkg/controller/iam/openidconnectprovider/controller_test.go, pkg/controller/iam/policy/controller_test.go, pkg/controller/iam/role/controller.go, pkg/controller/iam/role/controller_test.go, pkg/controller/iam/user/controller.go, pkg/controller/iam/user/controller_test.go
added a test to detect infinite default tag adding to oidcProvider
added a test to detect infinite defalt tag adding to oicdProvider
added a test to detect infinite default tag addition to role
Signed-off-by: Cecilia Bernardi <cbernardi@expediagroup.com>
Fixed addition of default Crossplane tags at every reconciliation loop
Fixes #1352
I have:
=> fixed infinite default tags adding in iam user

apis/v1alpha1/storeconfig_types.go, package/crds/aws.crossplane.io_storeconfigs.yaml
Signed-off-by: GitHub <noreply@github.com>
Update description for StoreConfig 
I have:
Noop change.
=> storeconfig: fix typo

pkg/controller/s3/bucket/notificationConfig.go, pkg/controller/s3/bucket/notificationConfig_test.go
The AWS API returns QueueConfiguration.Filter.Key.FilterRules.Name as "Prefix"/"Suffix" but expects "prefix"/"suffix", this leads to inconsistency and a constant diff.
Fixes #1165
I have:
Test were added, see diff.
=> fix(s3.bucket): Fixes #1165, discrepancy in QueueConfiguration.Filter.Key.FilterRules.Name

examples/apigateway/method.yaml, examples/apigateway/restapi.yaml, pkg/controller/apigateway/method/setup.go, pkg/controller/aws.go
- introduce method resource implementation
- move all examples of apigateway to use example as name
I have:
Example yaml provided
=> introduce method resource, move all examples of apigateway to use example as name

pkg/clients/elasticache/elasticache.go, pkg/clients/elasticache/elasticache_test.go, pkg/controller/cache/managed.go
Add a short string based reason for is up to date. "" = up to date.
IsUpToDate here is implemented a different way than other controllers,
so I just made the smallest possible change for now.
I have:
Unit test updated to continue to work. Ran against real cluster.
=> replicationgroup: Add reason for diff on update

apis/rds/v1alpha1/zz_generated.deepcopy.go
Run make generate to unblock master
=> fix: Unblock master

.github/workflows/backport.yml, .github/workflows/ci.yml, .github/workflows/commands.yml, .github/workflows/promote.yml, .github/workflows/tag.yml, apis/cache/v1beta1/replication_group_types.go, apis/database/v1beta1/rdsinstance_types.go, apis/generate.go, apis/redshift/v1alpha1/redshift_types.go, apis/route53/v1alpha1/resourcerecordset_types.go, apis/s3/v1beta1/replicationConfiguration_types.go, go.mod, go.sum, package/crds/database.aws.crossplane.io_rdsinstances.yaml, pkg/clients/aws.go, pkg/controller/cloudfront/lateinit.go, pkg/controller/cognitoidentityprovider/groupusermembership/controller_test.go, pkg/controller/ec2/vpcendpoint/setup.go, pkg/controller/glue/database/setup.go, pkg/controller/kms/alias/conversions.go, pkg/controller/servicediscovery/commonnamespace/hooks.go, pkg/controller/transfer/server/setup.go
Go 1.19 is out.
go mod tidy -compat=1.18 -go=1.18
cd build/
git fetch
git checkout origin/master
sed -i s,ubuntu-18.04,ubuntu-20.04,g .github/workflows/*
vim .github/workflows/ci.yml
inspired by https://github.com/crossplane/crossplane-runtime/pull/342
I have:
Not yet
=> Upgrade to Go 1.18

pkg/controller/ec2/vpcpeeringconnection/setup.go
Signed-off-by: Romain Dauby <romain.dauby@gmail.com>
This is one of the multiple possible refactoring.
https://github.com/crossplane-contrib/provider-aws/pull/1459#issuecomment-1252487035
Fixes #1459
I have:
=> fix: lint cyclomatic complexity

OWNERS.md
added MisterMX as Maintainer in OWNERS.md
Fixes #1446
I have:
=> feat(maintainers): added MisterMX

.github/workflows/ci.yml, .github/workflows/promote.yml, Makefile, package/crossplane.yaml
Updates provider-aws package source to point to crossplane-contrib
github org.
Updates to use the crossplane-contrib org on Upbound Marketplace and
crossplanecontrib org on Dockerhub. Dockerhub does not allow for - in
org names.
Updates the github workflows involved in pushing packages to use
crossplane-contrib creds for Dockerhub.
I have:
I have updated secrets, but we'll need to verify successful push after merge.
=> Push package to crossplane-contrib orgs

cluster/UPGRADE.md
=> feat(upgrade): added upgrade.md entry for notification -> sns

pkg/clients/rds/rds.go
We added diff output for rds to check why instances keep rebooting
#1348 
I have:
=> feat: Added diff output for rds instances

pkg/clients/rds/rds.go, pkg/clients/rds/rds_test.go, pkg/controller/database/rdsinstance.go, pkg/controller/ec2/vpcendpoint/setup.go
Diff for ras is given to ExternalOberservation result
#1348
I have:
=> feat: Updated logging of rds diff

pkg/clients/rds/rds.go, pkg/controller/rds/dbinstance/setup.go
Added debug info for dbinstance
#1348 
I have:
=> feat: Added debug output to dbinstance

pkg/controller/rds/dbinstance/setup.go
If a rds dbinstance is deployed with AutoMinorVersionUpgrade set to true, and aws updates the minor version, the controller thinks there is a change. In this pull request, the isUpToDate method is updated to check only the major version of the db in this case.
Fixes #832
I have:
=> RDS dbinstance: Check only major version if AutoMinorVersionUpgrade is true

CONTRIBUTING.md
Signed-off-by: Muvaffak Onus <me@muvaf.com>
I've been using these steps to bump various CRDs to `v1beta1`. Having the steps documented will help others to make similar changes.
I'll polish it a bit and mark it as ready for review.
Fixes #
I have:
Running through the steps for a number of resources.
=> Add guidelines for bumping API version of a CRD

CODE_GENERATION.md
I have:
Ran build and inspected image, and Nagarjun Krishnan tested it.
`docker run  -v /var/run/docker.sock:/var/run/docker.sock --rm -it wagoodman/dive:latest  chlunde/provider-aws:v0.34.0-rc.0.21.g6bd92eec`
=> Update CODE_GENERATION.md with xpkg bundle changes

pkg/controller/lambda/function/setup.go
- Improves PR: https://github.com/crossplane-contrib/provider-aws/pull/1454 
- and makes it possible to change the imageURI on the fly without deleting and reapplying the function.
I have:
=> fix(function): check LastUpdateStatus before Update

apis/iam/v1beta1/role_types.go, package/crds/iam.aws.crossplane.io_roles.yaml
Signed-off-by: Pedro Nunes <37883272+pintonunes@users.noreply.github.com>
Added ARN column display to Role to maintain consistency with Policy
Fixes #1555
I have:
```
kubectl apply -f ./package/crds/iam.aws.crossplane.io_roles.yaml
kubectl get role.v1beta1.iam.aws.crossplane.io
NAME    ARN                                 READY   SYNCED   AGE
role1   arn:aws:iam::<account>:role/role1   True    True     22h
```
=> fix(iam): Added ARN column display to Role

package/crds/s3.aws.crossplane.io_buckets.yaml, pkg/controller/lambda/function/setup.go, pkg/controller/lambda/function/setup_test.go
Fixes: #1583
- Fixes wrong logic in isUpToDateCodeImage
- Reduces code by using builtin `aws.StringValue()`
- Add tests for isUpToDateCodeImage
- Add another test for isUpToDateEnvironment
- Remove superfluous `err` in tests of isUpToDateEnvironment
I have:
See added tests.
=> Fix wrong logic lambda code ecr image

pkg/clients/elasticloadbalancing/elb/elb.go
=> fix(elb): Linter error

apis/kafka/generator-config.yaml, pkg/controller/kafka/cluster/setup.go, pkg/controller/kafka/cluster/zz_conversions.go
Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com>
fix #1611
Fixes #
I have:
=> Fix kafka initializer

pkg/controller/kafka/cluster/setup.go
Replaced paces in two lines by tabs as there was a linter error
Fixes #
I have:
=> fix: fixing linter stuff

pkg/controller/opensearchservice/domain/setup.go
Update loop for open search domains fixed
Fixes #
I have:
Tested with life resource by debugging method
=> fix: allow unsorted array is comparison for opensearchdomain

pkg/controller/rds/dbclusterparametergroup/setup.go
AWS only allows a `ModifyDBClusterParameterGroup` request to contain 20 parameters at a single time. Previously every `ModifyDBClusterParameterGroup` request would contain every parameter defined in the custom resource.
When defining > 20 parameters in a custom resource, it will continually fail to update with the following:
```
Warning  CannotUpdateExternalResource  1s  managed/dbclusterparametergroup.rds.aws.crossplane.io  cannot update DBClusterParameterGroup in AWS: InvalidParameterCombination: Cannot modify more than 20 parameters in a single request
```
This contribution ensures only the parameters that have changed or have not been set will be included in an update, updates are also limited to 20 parameters. If > 20 parameters have changed, the truncated parameters will be included …
=> fix(rds): handle maximum parameters per dbclusterparametergroup update

pkg/controller/rds/dbparametergroup/setup.go
AWS only allows a `ModifyDBParameterGroup` request to contain 20 parameters at a single time. Previously every `ModifyDBParameterGroup` request would contain every parameter defined in the custom resource.
When defining > 20 parameters in a custom resource, it will continually fail to update with the following:
```
Warning  CannotUpdateExternalResource  1s  managed/dbparametergroup.rds.aws.crossplane.io  cannot update DBParameterGroup in AWS: InvalidParameterCombination: Cannot modify more than 20 parameters in a single request
```
This contribution ensures only the parameters that have changed or have not been set will be included in an update, updates are also limited to 20 parameters. If > 20 parameters have changed, the truncated parameters will be included in the next reconciliation. …
=> fix(rds): handle maximum parameters per dbparametergroup update

.github/workflows/ci.yml, Makefile, package/crds/cloudfront.aws.crossplane.io_distributions.yaml
implement crddiff from uptest
Fixes #
I have:
```
(⎈ |kind-sop-local:default)➜  provider-aws git:(feature/crddiff) ✗ GITHUB_BASE_REF=master MODIFIED_CRD_LIST=package/crds/cloudfront.aws.crossplane.io_distributions.yaml make crddiff
21:57:04 [ .. ] Checking breaking CRD schema changes
Checking package/crds/cloudfront.aws.crossplane.io_distributions.yaml for breaking API changes...
Breaking change detected!
Version "v1alpha1":
- Schema changed
- Properties changed
- Modified property: spec
- Properties changed
- Modified property: forProvider
- Properties changed
- Modified property: distributionConfig
- Properties changed
- Modified property: defaultCacheBehavior
- Properties changed
- Modified property: cachePolicyID
- Type changed from 'string' to 'boolean'
21:57:04 [ OK ] Checking …
```
=> feat(crddiff): implement crddiff from uptest

apis/sqs/v1beta1/queue_types.go, apis/sqs/v1beta1/zz_generated.deepcopy.go, package/crds/sqs.aws.crossplane.io_queues.yaml, pkg/clients/sqs/queue.go
This PR implements in SQS the SSE(server-side-encryption) 
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-server-side-encryption.html
I have:
=>  feat(sqs): add support to SSE-SQS

apis/sqs/v1beta1/queue_types.go, pkg/clients/sqs/queue.go
FIx lint stuffs and remove unnecessary conversion presented in [here](https://github.com/crossplane-contrib/provider-aws/actions/runs/4363335352/jobs/7629498369#step:8:26520)
I have:
=> fix(sqs): adjust lint; remove unnecessary conversion

AUTHENTICATION.md
=> Updating authentication documentation for kiam

AUTHENTICATION.md
Community repo was moved to crossplane-contrib a while ago. Use the same
path as on https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws
Fixes #1745
I have:
N/A
=> AUTHENTICATION.md: Update package path

pkg/controller/kafka/cluster/setup.go
Follow-up for #1714 that fixes some compiler errors that sneaked past the pipeline.
I have:
n.a.
=> fix(kafka): Compiler errors in cluster controller

pkg/clients/iam/policy.go, pkg/controller/iam/policy/controller_test.go
=> fix(iam): Decode policy document before parsing

pkg/controller/rds/dbcluster/setup.go
=> fix(rds/dbcluster): Add read replica endpoint to connection details

apis/iam/v1alpha1/custom_types.go, apis/iam/v1beta1/group_types.go, apis/iam/v1beta1/grouppolicyattachment_types.go, apis/iam/v1beta1/groupusermembership_types.go, apis/iam/v1beta1/policy_types.go, apis/iam/v1beta1/role_types.go, apis/iam/v1beta1/rolepolicyattachment_types.go, apis/iam/v1beta1/user_types.go, apis/iam/v1beta1/userpolicyattachment_types.go, package/crds/iam.aws.crossplane.io_grouppolicyattachments.yaml, package/crds/iam.aws.crossplane.io_groups.yaml, package/crds/iam.aws.crossplane.io_groupusermemberships.yaml, package/crds/iam.aws.crossplane.io_instanceprofiles.yaml, package/crds/iam.aws.crossplane.io_policies.yaml, package/crds/iam.aws.crossplane.io_rolepolicyattachments.yaml, package/crds/iam.aws.crossplane.io_roles.yaml, package/crds/iam.aws.crossplane.io_userpolicyattachments.yaml, package/crds/iam.aws.crossplane.io_users.yaml
Fixes spelling only for IAM
I have:
Not required, as not made any changes to behavior.
=> refactor(iam): Fix incorrect spelling

pkg/controller/dynamodb/table/hooks.go
Fixes #1823 
I have:
Rerun the unit-test
=> fix(dynamodb): Update Input with external-name for isUpToDate and postUpdate

pkg/controller/kafka/cluster/setup.go
I removed the test for encryption at rest for Kafka-cluster to prevent update loop. Trying to update leads to an aws error, and trying to update only encryption at transit leads to the error that there was no update. 
I have:
Running the code locally
=> fix(kafka): Remove check for encryption at rest to prevent update loop

pkg/clients/sns/testdata/policy_a.json, pkg/clients/sns/testdata/policy_a2.json, pkg/clients/sns/testdata/policy_b.json, pkg/clients/sns/topic.go, pkg/clients/sns/topic_test.go, pkg/controller/sns/topic/controller.go, pkg/utils/policy/convert.go, pkg/utils/policy/parse.go, pkg/utils/policy/parse_test.go, pkg/utils/policy/testdata/UnmarshalArrays.json, pkg/utils/policy/types.go
Compare topic policies using structural diff add it to update attributes if they are not semantically equal.
Fixes #1896
Also fixed a bug in the generic resource policy parser regarding multi value conditions.
I have:
Unit tests and the existing topic example.
=> fix(sns): Topic policy update

pkg/controller/firehose/deliverystream/zz_controller.go
fixes check-diff failure in recent builds
```
M pkg/controller/firehose/deliverystream/zz_controller.go
02:03:14 [FAIL] There are uncommitted changes after running make generate. Please ensure you commit all generated files in this branch after running make generate.
make: *** [build/makelib/common.mk:446: check-diff] Error 1
Error: Process completed with exit code 2.
```
Fixes #
I have:
=> fix: firehose deliverystream controller check-diff

pkg/controller/cloudwatchlogs/loggroup/setup.go
Allow adding, removing or changing KMSKeys on a Cloudwatch LogGroup.
Fixes #1991
I have:
manually
=> feat(loggroup): allow updating kmskey

pkg/controller/s3/bucket/taggingConfig.go
@MisterMX
I'm so sorry but it seems I missed a serious bug :(
`CreateOrUpdate` func retrives observed state of tags by `CacheBucketTaggingOutput`  but it doesn't handle case if  
`CacheBucketTaggingOutput` returns an error`NoSuchTagSet` which is okay and means tags just don't exist. 
I also fixed another bug: the controller doesn't remove not system tag(s) if `bucket.Spec.ForProvider.BucketTagging` is nil. 
This is fix for changes from this [PR](https://github.com/crossplane-contrib/provider-aws/pull/2018)
I have:
- manual testing
- unit tests
=> fix(s3 bucket): hotfix for ignoring AWS system tags

.github/workflows/ci.yml
update github workflow ci.yaml unit-tests publish action
I have:
=> chore: update workflow ci

pkg/controller/cache/replicationgroup/managed.go, pkg/controller/cache/replicationgroup/managed_test.go
Manual backport of https://github.com/crossplane-contrib/provider-aws/pull/2088
I have:
=> fix: attempt to fix the version problems of replicationgroups (#1)

pkg/controller/ecs/service/conversions.go, pkg/controller/ecs/service/conversions_test.go, pkg/controller/ecs/service/setup.go, pkg/controller/ecs/service/setup_test.go
Fixes updating a ECS Service.
I have:
- Create, Delete of a ECS service
- Update of parameters like `desiredCount`, `subnets`, `deploymentCircuitBreaker`, `taskDefinition`, ...
=> fix(ecs): Fix Service IsUpToDate/Update logic

pkg/clients/ec2/address.go, pkg/clients/ec2/internetgateway.go, pkg/clients/ec2/routetable.go, pkg/clients/ec2/subnet.go, pkg/clients/ec2/tags_test.go, pkg/clients/ec2/tags_v1beta1.go, pkg/clients/ec2/vpc.go, pkg/controller/ec2/natgateway/controller.go, pkg/controller/ec2/securitygroup/controller_test.go
Fixes EC2 tag comparison.
I have:
- Unit tests
=> fix(ec2): Fix tags compare

pkg/controller/ecs/service/setup.go
Fixes
- tag updates
- lateInit Diffs
- nil pointer when resource is deleted on AWS
I have:
- Checked lateInit diffs
- Checked what happens when AWS resource is deleted
=> fix(ecs): Fix isUpToDate diffs & missing lateInits

pkg/utils/connect/aws/config.go
Fixes web identity usage with injected identity as pointed out by @geoffreyme https://github.com/crossplane-contrib/provider-aws/pull/2127#issuecomment-2512047112
I have:
=> fix: Web identity with injected identity

OWNERS.md
Update owners with new maintainers.
I have:
n.a.
=> chore: Update owners

.github/workflows/backport.yml, .github/workflows/ci.yml, .github/workflows/commands.yml, .github/workflows/promote.yml, .github/workflows/tag.yml
=> chore(ci): Bump github actions

pkg/controller/mq/configuration/setup.go
Fixes #2166 
I have:
- tested creation of rabbitmq config & checked that old activemq diffing still holds as expected 
=> fix(mqconfiguration): fix data diff for rabbitmq enginetype

.github/workflows/ci.yml, Makefile
Adjust CI for #2176 
I have:
- currently only ghcr login has been tested; test publish on merge 
=> chore(ci): publish artifacts to ghcr.io/crossplane-contrib

tools/go.mod, tools/go.sum
Manual backport of https://github.com/crossplane-contrib/provider-aws/pull/2190/commits
I have:
=> chore(deps): bump golang.org/x/crypto from 0.27.0 to 0.31.0 in /tools

pkg/controller/transfer/user/setup.go, pkg/controller/transfer/user/setup_test.go
Currently the provider does not check if mappings are updated, a check has been added.
Fixes #
I have:
=> feat(transfer): add homedirectorymapping uptodate check

pkg/controller/secretsmanager/secret/setup.go
Fixes #2205
I have:
- manual tests with this branch's version 
=> fix(secretsmanager): fix isUpToDate for tags only

pkg/controller/ecs/service/conversions.go, pkg/controller/ecs/service/setup.go
Fixes:
- Possible nil pointer after failed update
- Diff of Service Connect configuration of an ECS Service
I have:
- Created ECS Service and updated Service Connect configuration
=> fix(ecs): service connect diff & nil pointer fix

OWNERS.md
=> docs(owners): closes #2176

pkg/controller/rds/dbinstance/setup.go
Fixes #2009: Time parse issue in compareTimeRanges (maintenanceWindow)
I have:
The following snippet will show the fix with a simplified function of the compareTimeRanges code.
https://go.dev/play/p/gNMLBbTgbtE 
=> fix(rds): Only ignore weekday when comparing maintenanceWindow

OWNERS.md
=> docs(owners): add newest owners
